#!/usr/bin/env bash
# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25
#
# Development orchestration script for TaskChampion MCP.
# Usage: ./dev.sh <action>
#
# Actions:
#   setup       — Install Python deps (uv), create venv, install dev dependencies
#   check       — Verify all required tools are installed and report versions
#   install     — Add taskchampion MCP entry to IDE config (windsurf/cursor/vscode/claude) [-r|--restart to restart IDE]
#   uninstall   — Remove taskchampion MCP entry from IDE config (windsurf/cursor/vscode/claude)
#   reinstall   — Reinstall taskchampion MCP entry (gracefully terminates IDE, then uninstall + install) [-r|--restart to restart IDE]
#   init        — First-run schema wizard: analyse tasks + taxonomy, generate schema
#   test        — Run the test suite
#   lint        — Run ruff linter
#   format      — Run ruff formatter
#   run         — Start the MCP server (stdio) for manual testing
#   inspect     — Start the MCP inspector for interactive debugging
#   publish     — Build and publish to PyPI + MCP Registry
#   clean       — Remove build artifacts, caches, venv
#   list        — List all project-related installed components
#   help        — Show this help message

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${PROJECT_DIR}/.venv"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; }

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_ide_terminate_gracefully() {
    # Gracefully terminate an IDE process if running
    local ide_name="$1"
    local process_name="$2"
    
    # Use case-insensitive full command line match for process detection
    if pgrep -fi "$process_name" &>/dev/null; then
        info "Gracefully terminating $ide_name..."
        # Try SIGTERM first (graceful shutdown)
        pkill -TERM -fi "$process_name" &>/dev/null || true
        
        # Wait up to 5 seconds for graceful shutdown
        local count=0
        while pgrep -fi "$process_name" &>/dev/null && [ $count -lt 5 ]; do
            sleep 1
            count=$((count + 1))
        done
        
        # If still running, force kill
        if pgrep -fi "$process_name" &>/dev/null; then
            warn "$ide_name did not shut down gracefully, force killing..."
            pkill -9 -fi "$process_name" &>/dev/null || true
            sleep 1
        fi
        
        ok "$ide_name terminated."
    else
        info "$ide_name is not running."
    fi
}

_ide_start() {
    # Start an IDE if it's available
    local ide_name="$1"
    local start_command="$2"
    
    if command -v "$start_command" &>/dev/null; then
        info "Starting $ide_name..."
        "$start_command" &>/dev/null &
        ok "$ide_name started."
    else
        warn "$start_command not found. Please start $ide_name manually."
    fi
}

_check_cmd() {
    local cmd="$1"
    local name="${2:-$1}"
    if command -v "$cmd" &>/dev/null; then
        local ver
        ver=$("$cmd" --version 2>/dev/null | head -1 || echo "unknown")
        ok "$name found: $ver"
        return 0
    else
        fail "$name not found on PATH"
        return 1
    fi
}

# ---------------------------------------------------------------------------
# Platform detection & Claude Desktop helpers
# ---------------------------------------------------------------------------

_detect_platform() {
    # Returns one of: macos | wsl | windows_shell | linux
    # wsl          — bash running inside Windows Subsystem for Linux
    # windows_shell — bash running inside Git Bash / MSYS2 / Cygwin on Windows
    # macos        — native macOS shell
    # linux        — native Linux shell (no Windows layer)
    case "$(uname -s)" in
        Darwin)
            echo "macos"
            ;;
        Linux)
            if grep -qiE "microsoft|WSL" /proc/version 2>/dev/null; then
                echo "wsl"
            else
                echo "linux"
            fi
            ;;
        MINGW*|MSYS*|CYGWIN*)
            echo "windows_shell"
            ;;
        *)
            echo "linux"
            ;;
    esac
}

_claude_desktop_config_path() {
    # Returns the platform-correct path to Claude Desktop's MCP config file.
    #
    # macOS        : ~/Library/Application Support/Claude/claude_desktop_config.json
    # WSL          : /mnt/c/Users/<user>/AppData/Roaming/Claude/claude_desktop_config.json
    # Git Bash     : $APPDATA/Claude/claude_desktop_config.json  (Windows-style, resolved by bash)
    # Linux        : ${XDG_CONFIG_HOME:-~/.config}/Claude/claude_desktop_config.json
    local platform
    platform="$(_detect_platform)"
    case "$platform" in
        macos)
            echo "$HOME/Library/Application Support/Claude/claude_desktop_config.json"
            ;;
        wsl)
            local win_appdata=""
            # $APPDATA is usually inherited from Windows into WSL environment
            if [ -n "${APPDATA:-}" ]; then
                win_appdata="$(wslpath "$APPDATA" 2>/dev/null || echo "")"
            fi
            # Fallback: query Windows USERNAME and build path manually
            if [ -z "$win_appdata" ]; then
                local win_user
                win_user="$(cmd.exe /c 'echo %USERNAME%' 2>/dev/null | tr -d '\r\n' || echo "")"
                [ -n "$win_user" ] && win_appdata="/mnt/c/Users/${win_user}/AppData/Roaming"
            fi
            if [ -n "$win_appdata" ]; then
                echo "${win_appdata}/Claude/claude_desktop_config.json"
            else
                warn "Cannot resolve Windows AppData in WSL; falling back to XDG path."
                # Capital "Claude" — matches Linux/macOS/Windows casing.
                echo "${XDG_CONFIG_HOME:-$HOME/.config}/Claude/claude_desktop_config.json"
            fi
            ;;
        windows_shell)
            # Git Bash / MSYS2: Windows injects $APPDATA as a Windows-style path;
            # bash here resolves it automatically (e.g. C:\Users\...\AppData\Roaming).
            if [ -n "${APPDATA:-}" ]; then
                echo "${APPDATA}/Claude/claude_desktop_config.json"
            else
                echo "${USERPROFILE:-$HOME}/AppData/Roaming/Claude/claude_desktop_config.json"
            fi
            ;;
        linux)
            # Capital "Claude" — Claude Desktop on Linux stores its config at
            # ~/.config/Claude/, matching the macOS/WSL/Windows casing. Linux
            # filesystems are case-sensitive, so a lowercase "claude" path
            # silently breaks the install: the file is created but Claude
            # Desktop never reads it.
            echo "${XDG_CONFIG_HOME:-$HOME/.config}/Claude/claude_desktop_config.json"
            ;;
    esac
}

_claude_desktop_server_command() {
    # Returns the command Claude Desktop should use to launch the MCP server.
    #
    # Key insight for WSL: Claude Desktop is a native Windows process, but Taskwarrior
    # and the Python venv live inside WSL.  The correct bridge is `wsl.exe -e <linux-cmd>`:
    # Claude Desktop (Windows) launches wsl.exe, which executes the command inside the
    # default WSL distro where both Python and `task` are available.  No Windows-side
    # Python or uv install is required.
    local platform
    platform="$(_detect_platform)"
    case "$platform" in
        wsl)
            # wsl.exe is always on the Windows PATH when WSL is installed
            echo "wsl.exe"
            ;;
        windows_shell)
            # Git Bash / MSYS2: venv was (should be) created here, so Scripts\python.exe exists
            echo "${VENV_DIR}/Scripts/python.exe"
            ;;
        *)
            # macOS / native Linux
            echo "${VENV_DIR}/bin/python"
            ;;
    esac
}

_claude_desktop_server_args() {
    # Returns a JSON array string for the MCP server args entry.
    local platform
    platform="$(_detect_platform)"
    case "$platform" in
        wsl)
            # Pass the Linux-side venv Python path directly to wsl.exe.
            # wsl.exe resolves it inside WSL — no path conversion needed since
            # VENV_DIR is already a valid WSL (Linux) path.
            echo "[\"-e\", \"${VENV_DIR}/bin/python\", \"-m\", \"taskchampion_mcp.server\"]"
            ;;
        *)
            echo "[\"-m\", \"taskchampion_mcp.server\"]"
            ;;
    esac
}

_claude_desktop_is_running() {
    # Returns 0 (true) if Claude Desktop is currently running, 1 if not.
    local platform
    platform="$(_detect_platform)"
    case "$platform" in
        wsl)
            tasklist.exe 2>/dev/null | grep -qi "Claude.exe"
            ;;
        windows_shell)
            tasklist 2>/dev/null | grep -qi "Claude.exe"
            ;;
        macos)
            pgrep -qf "Claude" 2>/dev/null
            ;;
        linux)
            pgrep -qf "claude-desktop" 2>/dev/null
            ;;
    esac
}

_claude_desktop_terminate() {
    # Gracefully stop Claude Desktop on the current platform.
    local platform
    platform="$(_detect_platform)"
    case "$platform" in
        macos)
            _ide_terminate_gracefully "Claude Desktop" "Claude"
            ;;
        wsl)
            if tasklist.exe 2>/dev/null | grep -qi "Claude.exe"; then
                info "Gracefully terminating Claude Desktop (Windows process)..."
                taskkill.exe /IM "Claude.exe" 2>/dev/null || true
                local count=0
                while tasklist.exe 2>/dev/null | grep -qi "Claude.exe" && [ $count -lt 5 ]; do
                    sleep 1; count=$((count + 1))
                done
                if tasklist.exe 2>/dev/null | grep -qi "Claude.exe"; then
                    warn "Claude Desktop did not stop gracefully; force-killing..."
                    taskkill.exe /F /IM "Claude.exe" 2>/dev/null || true
                    sleep 1
                fi
                ok "Claude Desktop terminated."
            else
                info "Claude Desktop is not running."
            fi
            ;;
        windows_shell)
            if tasklist 2>/dev/null | grep -qi "Claude.exe"; then
                info "Gracefully terminating Claude Desktop..."
                taskkill //IM "Claude.exe" 2>/dev/null || true
                sleep 3
                tasklist 2>/dev/null | grep -qi "Claude.exe" && \
                    { taskkill //F //IM "Claude.exe" 2>/dev/null || true; }
                ok "Claude Desktop terminated."
            else
                info "Claude Desktop is not running."
            fi
            ;;
        linux)
            _ide_terminate_gracefully "Claude Desktop" "claude-desktop"
            ;;
    esac
}

_claude_desktop_start() {
    # Launch Claude Desktop on the current platform.
    local platform
    platform="$(_detect_platform)"
    case "$platform" in
        macos)
            info "Starting Claude Desktop..."
            if open -a "Claude" &>/dev/null; then
                ok "Claude Desktop started."
            else
                warn "Could not start Claude Desktop. Please launch it manually."
            fi
            ;;
        wsl)
            info "Starting Claude Desktop (Windows)..."
            local localappdata_win
            localappdata_win="$(cmd.exe /c 'echo %LOCALAPPDATA%' 2>/dev/null | tr -d '\r\n')"
            if [ -n "$localappdata_win" ]; then
                local localappdata_wsl
                localappdata_wsl="$(wslpath "$localappdata_win" 2>/dev/null || echo "")"
                if [ -n "$localappdata_wsl" ] && [ -f "${localappdata_wsl}/AnthropicClaude/claude.exe" ]; then
                    cmd.exe /c "start \"\" \"${localappdata_win}\\AnthropicClaude\\claude.exe\"" &>/dev/null \
                        && ok "Claude Desktop started." \
                        || warn "Could not start Claude Desktop. Please launch it manually."
                    return
                fi
            fi
            warn "Claude Desktop executable not found. Please launch it manually."
            ;;
        windows_shell)
            info "Starting Claude Desktop..."
            local claude_exe="${LOCALAPPDATA:-${USERPROFILE}/AppData/Local}/AnthropicClaude/claude.exe"
            if [ -f "$claude_exe" ]; then
                cmd //c start "" "$claude_exe" &>/dev/null \
                    && ok "Claude Desktop started." \
                    || warn "Could not start Claude Desktop. Please launch it manually."
            else
                warn "Claude Desktop executable not found at: ${claude_exe}"
                warn "Please launch Claude Desktop manually."
            fi
            ;;
        linux)
            _ide_start "Claude Desktop" "claude-desktop"
            ;;
    esac
}

_ensure_uv() {
    if ! command -v uv &>/dev/null; then
        fail "uv is not installed. Install it: https://docs.astral.sh/uv/getting-started/installation/"
        exit 1
    fi
}

_ensure_venv() {
    if [ ! -d "$VENV_DIR" ]; then
        warn "Virtual environment not found. Run './dev.sh setup' first."
        exit 1
    fi
}

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------

action_setup() {
    info "Setting up development environment..."
    _ensure_uv

    info "Creating virtual environment with uv..."
    uv venv "$VENV_DIR" --python 3.12 2>/dev/null || uv venv "$VENV_DIR"

    info "Installing project in editable mode with dev dependencies..."
    uv pip install -e ".[dev]" --python "$VENV_DIR/bin/python"

    ok "Setup complete. Activate with: source .venv/bin/activate"
}

action_check() {
    info "Checking required tools..."
    echo ""

    local all_ok=true

    # Python
    if _check_cmd python3 "Python 3"; then
        python3 -c "import sys; v=sys.version_info; exit(0 if v >= (3,10) else 1)" 2>/dev/null \
            || { warn "Python 3.10+ required"; all_ok=false; }
    else
        all_ok=false
    fi

    # uv
    _check_cmd uv "uv (package manager)" || all_ok=false

    # Taskwarrior
    if command -v task &>/dev/null; then
        local tw_ver
        tw_ver=$(task _version 2>/dev/null || echo "unknown")
        ok "Taskwarrior found: v${tw_ver}"
        local major="${tw_ver%%.*}"
        if [ "$major" = "2" ]; then
            warn "Taskwarrior 2.x detected — this MCP targets 3.x"
        elif [ "$major" != "3" ]; then
            warn "Unexpected Taskwarrior version: $tw_ver"
        fi
    else
        fail "Taskwarrior (task) not found on PATH"
        all_ok=false
    fi

    # Timewarrior (optional)
    if command -v timew &>/dev/null; then
        local timew_ver
        timew_ver=$(timew --version 2>/dev/null | head -1 || echo "unknown")
        ok "Timewarrior found: ${timew_ver}"
    else
        warn "Timewarrior (timew) not found — time tracking tools will be disabled"
    fi

    # Virtual environment
    if [ -d "$VENV_DIR" ]; then
        ok "Virtual environment exists at ${VENV_DIR}"
    else
        warn "No virtual environment. Run './dev.sh setup'"
    fi

    # MCP SDK
    if [ -d "$VENV_DIR" ] && "$VENV_DIR/bin/python" -c "import mcp" 2>/dev/null; then
        local mcp_ver
        mcp_ver=$("$VENV_DIR/bin/python" -c "import importlib.metadata; print(importlib.metadata.version('mcp'))" 2>/dev/null || echo "unknown")
        ok "MCP SDK installed: v${mcp_ver}"
    else
        warn "MCP SDK not installed. Run './dev.sh setup'"
    fi

    # IDE MCP config files — check for existing taskchampion server entry
    echo ""
    info "Checking IDE MCP configurations..."
    local _claude_cfg
    _claude_cfg="$(_claude_desktop_config_path)"
    local mcp_configs=(
        "$HOME/.codeium/windsurf/mcp_config.json:Windsurf"
        "$HOME/.cursor/mcp.json:Cursor"
        "$HOME/.vscode/mcp.json:VS Code"
        "${_claude_cfg}:Claude Desktop"
    )
    local found_any_config=false
    for entry in "${mcp_configs[@]}"; do
        local cfg_path="${entry%%:*}"
        local cfg_name="${entry##*:}"
        if [ -f "$cfg_path" ]; then
            found_any_config=true
            if grep -qi "taskchampion" "$cfg_path" 2>/dev/null; then
                ok "${cfg_name}: taskchampion entry found in $(basename "$cfg_path")"
            else
                warn "${cfg_name}: config exists but no taskchampion entry (${cfg_path})"
            fi
        fi
    done
    if ! $found_any_config; then
        warn "No IDE MCP config files found. Configure your IDE to use taskchampion-mcp-server."
    fi

    echo ""
    if $all_ok; then
        ok "All required tools are available."
    else
        fail "Some tools are missing. See warnings above."
    fi
}

action_test() {
    _ensure_venv
    info "Running tests..."
    if [ $# -eq 0 ]; then
        "$VENV_DIR/bin/python" -m pytest -v
    else
        "$VENV_DIR/bin/python" -m pytest "$@"
    fi
}

action_lint() {
    _ensure_venv
    info "Running ruff linter..."
    "$VENV_DIR/bin/python" -m ruff check src/ tests/
}

action_format() {
    _ensure_venv
    info "Running ruff formatter..."
    "$VENV_DIR/bin/python" -m ruff format src/ tests/
}

action_run() {
    _ensure_venv
    info "Starting TaskChampion MCP server (stdio)..."
    "$VENV_DIR/bin/python" -m taskchampion_mcp.server
}

action_inspect() {
    _ensure_venv
    info "Starting MCP Inspector..."
    if command -v npx &>/dev/null; then
        npx -y @modelcontextprotocol/inspector "$VENV_DIR/bin/python" -m taskchampion_mcp.server
    else
        warn "npx not found. Install Node.js to use the MCP inspector."
        warn "Alternatively, run: uv run mcp dev src/taskchampion_mcp/server.py"
    fi
}

_claude_code_available() {
    # Returns 0 (true) if the 'claude' CLI is on PATH and supports `mcp` subcommand.
    command -v claude &>/dev/null && claude mcp --help &>/dev/null
}

_claude_code_has_entry() {
    # Returns 0 (true) if Claude Code has a 'taskchampion' MCP entry configured.
    claude mcp list 2>/dev/null | grep -qE '^taskchampion[: ]'
}

_install_claude_code_target() {
    # Wire taskchampion-MCP into Claude Code via `claude mcp add`.
    # Uses the dev .venv Python so iteration against the local checkout works
    # without re-publishing. For fresh remote boxes prefer the
    # `scripts/setup_remote.sh` bootstrap which uses a git-pinned `uv tool install`.
    local scope="${1:-user}"

    if ! _claude_code_available; then
        fail "Claude Code CLI ('claude' with 'mcp' subcommand) not found on PATH."
        echo "  Install: https://docs.anthropic.com/en/docs/claude-code"
        exit 1
    fi

    _ensure_venv

    local server_command="${VENV_DIR}/bin/python"

    info "Wiring taskchampion MCP into Claude Code (scope=${scope})..."

    # Remove any prior entry so add is idempotent (claude mcp add refuses on dup).
    if _claude_code_has_entry; then
        info "Removing existing 'taskchampion' entry first (idempotent install)..."
        claude mcp remove taskchampion 2>/dev/null || true
    fi

    if claude mcp add taskchampion -s "${scope}" -- "${server_command}" -m taskchampion_mcp.server; then
        ok "Claude Code: taskchampion entry written (scope=${scope})"
        echo ""
        info "Entry added via 'claude mcp add':"
        echo "  scope:   ${scope}"
        echo "  command: ${server_command}"
        echo "  args:    -m taskchampion_mcp.server"
        echo ""
        info "Verify with: claude mcp list"
        echo ""
        info "Claude Code is a CLI — no IDE restart needed. Next 'claude' invocation"
        info "will spawn the new MCP server and pick up the registered tool surface."
    else
        fail "Failed to add taskchampion to Claude Code MCP config."
        exit 1
    fi
}

_uninstall_claude_code_target() {
    if ! _claude_code_available; then
        warn "Claude Code CLI ('claude' with 'mcp' subcommand) not found on PATH; nothing to uninstall."
        return
    fi
    if _claude_code_has_entry; then
        info "Removing 'taskchampion' from Claude Code MCP config..."
        if claude mcp remove taskchampion 2>/dev/null; then
            ok "Removed."
        else
            warn "Removal command returned non-zero — entry may still exist."
        fi
    else
        info "No 'taskchampion' entry found in Claude Code MCP config."
    fi
}

_remove_mcp_entry() {
    # Remove the 'taskchampion' key from mcpServers in a JSON config file.
    # Uses Python for safe JSON manipulation.
    local cfg_path="$1"
    local cfg_name="$2"
    if [ ! -f "$cfg_path" ]; then
        return
    fi
    if ! grep -qi "taskchampion" "$cfg_path" 2>/dev/null; then
        return
    fi
    info "Removing taskchampion entry from ${cfg_name} config (${cfg_path})..."
    python3 -c "
import json, sys
path = sys.argv[1]
with open(path) as f:
    data = json.load(f)
servers = data.get('mcpServers', {})
if 'taskchampion' in servers:
    del servers['taskchampion']
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)
        f.write('\n')
    print('  Removed.')
else:
    print('  No taskchampion entry found.')
" "$cfg_path"
}

_upsert_mcp_entry() {
    # Insert or update the 'taskchampion' key in mcpServers of a JSON config file.
    # Creates the file (and parent dirs) if it doesn't exist.
    local cfg_path="$1"
    local cfg_name="$2"
    local server_command="$3"
    local server_args="$4"  # JSON array string, e.g. '["-m", "taskchampion_mcp.server"]'

    mkdir -p "$(dirname "$cfg_path")"

    python3 -c "
import json, sys, os

path, cmd, args_json = sys.argv[1], sys.argv[2], sys.argv[3]
args = json.loads(args_json)

if os.path.isfile(path):
    with open(path) as f:
        data = json.load(f)
else:
    data = {}

data.setdefault('mcpServers', {})
data['mcpServers']['taskchampion'] = {
    'command': cmd,
    'args': args,
}

with open(path, 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
" "$cfg_path" "$server_command" "$server_args"
}

action_install() {
    # -------------------------------------------------------------------------
    # DEVELOPER CONVENIENCE ONLY — NOT AN END-USER INSTALLER
    #
    # This command points Claude Desktop at the local dev build (your checkout).
    # It is intended for contributors iterating on the server source.
    #
    # For end-user installation see: https://github.com/GabiUp2/TaskChampion_MCP
    # The published path is:  uvx taskchampion-mcp          (Linux / macOS)
    #                         wsl.exe bash -lc "uvx taskchampion-mcp"  (WSL)
    # See ADR 18 for the full rationale.
    # -------------------------------------------------------------------------

    # Short-circuit: claude-code uses `claude mcp add` (CLI), not a JSON config
    # file — different API surface, no IDE process to restart. Handle before the
    # JSON-config machinery runs so we don't try to write a file Claude Code
    # doesn't read.
    if [ "${1:-}" = "claude-code" ]; then
        shift
        _install_claude_code_target "user"
        return
    fi

    _ensure_venv

    # Default server invocation (non-claude targets)
    local server_command="${VENV_DIR}/bin/python"
    local server_args='["-m", "taskchampion_mcp.server"]'

    # Claude Desktop config path is platform-aware (macOS / WSL / Windows / Linux differ)
    local _claude_cfg
    _claude_cfg="$(_claude_desktop_config_path)"

    # All known IDE MCP config locations
    local -A ide_configs=(
        [windsurf]="$HOME/.codeium/windsurf/mcp_config.json"
        [cursor]="$HOME/.cursor/mcp.json"
        [vscode]="$HOME/.vscode/mcp.json"
        [claude]="${_claude_cfg}"
    )
    local -A ide_labels=(
        [windsurf]="Windsurf"
        [cursor]="Cursor"
        [vscode]="VS Code"
        [claude]="Claude Desktop"
    )
    # IDE process names for graceful termination (use partial match patterns)
    local -A ide_processes=(
        [windsurf]="windsurf"
        [cursor]="cursor"
        [vscode]="code"
        [claude]="__claude_desktop__"   # sentinel — handled by _claude_desktop_terminate
    )
    # IDE start commands
    local -A ide_start_commands=(
        [windsurf]="windsurf"
        [cursor]="cursor"
        [vscode]="code"
        [claude]="__claude_desktop__"   # sentinel — handled by _claude_desktop_start
    )

    local target="${1:-}"
    local restart_after=false

    # Parse arguments for -r or --restart flag
    shift || true
    while [ $# -gt 0 ]; do
        case "$1" in
            -r|--restart)
                restart_after=true
                shift
                ;;
            *)
                # Unknown argument, might be the IDE target if target was empty
                if [ -z "$target" ]; then
                    target="$1"
                    shift
                else
                    fail "Unknown argument: $1"
                    echo "  Usage: ./dev.sh install <ide> [-r|--restart]"
                    exit 1
                fi
                ;;
        esac
    done

    if [ -n "$target" ]; then
        target="$(echo "$target" | tr '[:upper:]' '[:lower:]')"
        if [ -z "${ide_configs[$target]+x}" ]; then
            fail "Unknown IDE: $target"
            echo "  Available: ${!ide_configs[*]}"
            exit 1
        fi
        local cfg_path="${ide_configs[$target]}"
        local cfg_name="${ide_labels[$target]}"

        # Claude Desktop: hard-refuse if the app is running.
        # Claude Desktop owns claude_desktop_config.json and flushes its in-memory
        # state back to disk on exit — any mcpServers entry written while the app is
        # open will be silently overwritten when the user quits.  The only safe window
        # to write the config is when the app is not running.
        if [ "$target" = "claude" ] && _claude_desktop_is_running; then
            echo ""
            fail "Claude Desktop is currently running."
            echo ""
            echo "  Writing the MCP config while Claude Desktop is open is unsafe:"
            echo "  the app overwrites claude_desktop_config.json on exit, silently"
            echo "  discarding any changes made while it was running."
            echo ""
            echo "  Options:"
            echo "    ./dev.sh reinstall claude -r   — stops the app, writes config, restarts"
            echo "    Quit Claude Desktop manually, then re-run: ./dev.sh install claude"
            echo ""
            exit 1
        fi

        # Claude Desktop needs a platform-aware server command/args (Windows path on WSL/Git Bash)
        if [ "$target" = "claude" ]; then
            server_command="$(_claude_desktop_server_command)"
            server_args="$(_claude_desktop_server_args)"
        fi

        info "Installing taskchampion MCP entry into ${cfg_name} config..."
        _upsert_mcp_entry "$cfg_path" "$cfg_name" "$server_command" "$server_args"
        ok "${cfg_name}: taskchampion entry written to ${cfg_path}"
        echo ""
        info "Entry added:"
        echo "  command: ${server_command}"
        echo "  args:    $(echo "$server_args" | python3 -c 'import json,sys; print(" ".join(json.load(sys.stdin)))' 2>/dev/null || echo "$server_args")"
        echo ""

        if [ "$restart_after" = true ]; then
            info "Restarting ${cfg_name}..."
            if [ "$target" = "claude" ]; then
                _claude_desktop_terminate
                sleep 1
                _claude_desktop_start
            else
                local process_name="${ide_processes[$target]:-$target}"
                local start_command="${ide_start_commands[$target]:-$target}"
                _ide_terminate_gracefully "$cfg_name" "$process_name"
                sleep 1
                _ide_start "$cfg_name" "$start_command"
            fi
            echo ""
        else
            info "Next steps:"
            echo "  1. Restart your IDE to pick up the new MCP server"
            echo "     Or use: ./dev.sh install ${target} -r"
            echo "  2. Ask the LLM to help you configure your role level and schema/taxonomy"
            echo "     Example: 'Help me set up my TaskChampion role and task schema'"
        fi
        return
    fi

    # Interactive: show detected IDEs and let user pick
    echo "Available IDE targets:"
    echo ""
    local idx=1
    local -a keys=()
    for key in windsurf cursor vscode claude; do
        local cfg_path="${ide_configs[$key]}"
        local cfg_name="${ide_labels[$key]}"
        local status=""
        if [ -f "$cfg_path" ]; then
            if grep -qi "taskchampion" "$cfg_path" 2>/dev/null; then
                status=" ${GREEN}(already configured)${NC}"
            else
                status=" ${YELLOW}(config exists, no entry)${NC}"
            fi
        else
            local cfg_dir
            cfg_dir="$(dirname "$cfg_path")"
            if [ -d "$cfg_dir" ]; then
                status=" ${CYAN}(dir exists, will create config)${NC}"
            else
                status=""
            fi
        fi
        echo -e "  ${idx}) ${cfg_name}${status}"
        keys+=("$key")
        idx=$((idx + 1))
    done
    echo -e "  a) All of the above"
    echo ""
    read -rp "Select target(s) [1-4, a, or comma-separated]: " selection

    local selected=()
    if [[ "$selection" == "a" || "$selection" == "A" ]]; then
        selected=("${keys[@]}")
    else
        IFS=',' read -ra parts <<< "$selection"
        for part in "${parts[@]}"; do
            part="$(echo "$part" | tr -d ' ')"
            if [[ "$part" =~ ^[1-4]$ ]]; then
                selected+=("${keys[$((part - 1))]}")
            else
                warn "Skipping invalid selection: $part"
            fi
        done
    fi

    if [ ${#selected[@]} -eq 0 ]; then
        warn "No targets selected."
        return
    fi

    # Guard: refuse if Claude Desktop is selected and currently running
    for key in "${selected[@]}"; do
        if [ "$key" = "claude" ] && _claude_desktop_is_running; then
            echo ""
            fail "Claude Desktop is currently running — cannot install safely."
            echo ""
            echo "  Claude Desktop overwrites its config on exit."
            echo "  Quit Claude Desktop first, or use: ./dev.sh reinstall claude -r"
            echo ""
            exit 1
        fi
    done

    echo ""
    for key in "${selected[@]}"; do
        local cfg_path="${ide_configs[$key]}"
        local cfg_name="${ide_labels[$key]}"
        # Per-target server command/args
        local _sc="$server_command"
        local _sa="$server_args"
        if [ "$key" = "claude" ]; then
            _sc="$(_claude_desktop_server_command)"
            _sa="$(_claude_desktop_server_args)"
        fi
        info "Installing into ${cfg_name}..."
        _upsert_mcp_entry "$cfg_path" "$cfg_name" "$_sc" "$_sa"
        ok "${cfg_name}: ${cfg_path}"
    done

    echo ""
    info "MCP server entry written. Restart your IDE(s) to pick up the new server."
    echo ""

    # Ask if user wants to restart IDEs (only when a single target was selected)
    if [ ${#selected[@]} -eq 1 ]; then
        local key="${selected[0]}"
        local cfg_name="${ide_labels[$key]}"
        read -rp "Restart ${cfg_name} now? [y/N]: " restart_answer
        if [[ "$restart_answer" == "y" || "$restart_answer" == "Y" ]]; then
            if [ "$key" = "claude" ]; then
                _claude_desktop_terminate
                sleep 1
                _claude_desktop_start
            else
                local process_name="${ide_processes[$key]:-$key}"
                local start_command="${ide_start_commands[$key]:-$key}"
                _ide_terminate_gracefully "$cfg_name" "$process_name"
                sleep 1
                _ide_start "$cfg_name" "$start_command"
            fi
        else
            info "Next steps:"
            echo "  1. Restart your IDE to pick up the new MCP server"
            echo "  2. Ask the LLM to help you configure your role level and schema/taxonomy"
            echo "     Example: 'Help me set up my TaskChampion role and task schema'"
        fi
    else
        info "Next steps:"
        echo "  1. Restart your IDE(s) to pick up the new MCP server"
        echo "  2. Ask the LLM to help you configure your role level and schema/taxonomy"
        echo "     Example: 'Help me set up my TaskChampion role and task schema'"
    fi
    ok "Install complete."
}

action_uninstall() {
    # Short-circuit: claude-code uses `claude mcp remove`, not a JSON config edit.
    if [ "${1:-}" = "claude-code" ]; then
        _uninstall_claude_code_target
        return
    fi

    local _claude_cfg
    _claude_cfg="$(_claude_desktop_config_path)"

    # All known IDE MCP config locations
    local -A ide_configs=(
        [windsurf]="$HOME/.codeium/windsurf/mcp_config.json"
        [cursor]="$HOME/.cursor/mcp.json"
        [vscode]="$HOME/.vscode/mcp.json"
        [claude]="${_claude_cfg}"
    )
    local -A ide_labels=(
        [windsurf]="Windsurf"
        [cursor]="Cursor"
        [vscode]="VS Code"
        [claude]="Claude Desktop"
    )

    local target="${1:-}"

    if [ -n "$target" ]; then
        target="$(echo "$target" | tr '[:upper:]' '[:lower:]')"
        if [ -z "${ide_configs[$target]+x}" ]; then
            fail "Unknown IDE: $target"
            echo "  Available: ${!ide_configs[*]}"
            exit 1
        fi
        local cfg_path="${ide_configs[$target]}"
        local cfg_name="${ide_labels[$target]}"
        _remove_mcp_entry "$cfg_path" "$cfg_name"
        ok "${cfg_name}: taskchampion entry removed from ${cfg_path}"
        echo ""
        info "Restart your IDE to pick up the changes."
        return
    fi

    # Interactive: show detected IDEs and let user pick
    echo "Available IDE targets:"
    echo ""
    local idx=1
    local -a keys=()
    for key in windsurf cursor vscode claude; do
        local cfg_path="${ide_configs[$key]}"
        local cfg_name="${ide_labels[$key]}"
        local status=""
        if [ -f "$cfg_path" ]; then
            if grep -qi "taskchampion" "$cfg_path" 2>/dev/null; then
                status=" ${GREEN}(has taskchampion-mcp entry)${NC}"
            else
                status=" ${YELLOW}(no taskchampion-mcp entry)${NC}"
            fi
        else
            status=" ${YELLOW}(config not found)${NC}"
        fi
        echo -e "  ${idx}) ${cfg_name}${status}"
        keys+=("$key")
        idx=$((idx + 1))
    done
    echo -e "  a) All of the above"
    echo ""
    read -rp "Select target(s) to uninstall from [1-4, a, or comma-separated]: " selection

    local selected=()
    if [[ "$selection" == "a" || "$selection" == "A" ]]; then
        selected=("${keys[@]}")
    else
        IFS=',' read -ra parts <<< "$selection"
        for part in "${parts[@]}"; do
            part="$(echo "$part" | tr -d ' ')"
            if [[ "$part" =~ ^[1-4]$ ]]; then
                selected+=("${keys[$((part - 1))]}")
            else
                warn "Skipping invalid selection: $part"
            fi
        done
    fi

    if [ ${#selected[@]} -eq 0 ]; then
        warn "No targets selected."
        return
    fi

    echo ""
    for key in "${selected[@]}"; do
        local cfg_path="${ide_configs[$key]}"
        local cfg_name="${ide_labels[$key]}"
        _remove_mcp_entry "$cfg_path" "$cfg_name"
        ok "${cfg_name}: ${cfg_path}"
    done

    echo ""
    info "Restart your IDE to pick up the changes."
}

action_reinstall() {
    # Short-circuit: claude-code is a CLI — no IDE process to terminate/restart.
    # Reinstall is just uninstall + install (idempotent claude mcp add).
    if [ "${1:-}" = "claude-code" ]; then
        _uninstall_claude_code_target
        echo ""
        _install_claude_code_target "user"
        return
    fi

    local _claude_cfg
    _claude_cfg="$(_claude_desktop_config_path)"

    # All known IDE MCP config locations
    local -A ide_configs=(
        [windsurf]="$HOME/.codeium/windsurf/mcp_config.json"
        [cursor]="$HOME/.cursor/mcp.json"
        [vscode]="$HOME/.vscode/mcp.json"
        [claude]="${_claude_cfg}"
    )
    local -A ide_labels=(
        [windsurf]="Windsurf"
        [cursor]="Cursor"
        [vscode]="VS Code"
        [claude]="Claude Desktop"
    )
    # IDE process names for graceful termination (use partial match patterns)
    local -A ide_processes=(
        [windsurf]="windsurf"
        [cursor]="cursor"
        [vscode]="code"
        [claude]="__claude_desktop__"   # sentinel — handled by _claude_desktop_terminate
    )
    # IDE start commands
    local -A ide_start_commands=(
        [windsurf]="windsurf"
        [cursor]="cursor"
        [vscode]="code"
        [claude]="__claude_desktop__"   # sentinel — handled by _claude_desktop_start
    )

    local target="${1:-}"
    local restart_after=false

    # Parse arguments for -r or --restart flag
    shift || true
    while [ $# -gt 0 ]; do
        case "$1" in
            -r|--restart)
                restart_after=true
                shift
                ;;
            *)
                fail "Unknown argument: $1"
                echo "  Usage: ./dev.sh reinstall <ide> [-r|--restart]"
                exit 1
                ;;
        esac
    done

    if [ -z "$target" ]; then
        fail "reinstall requires an IDE target"
        echo "  Usage: ./dev.sh reinstall <ide> [-r|--restart]"
        echo "  Available: windsurf, cursor, vscode, claude"
        exit 1
    fi

    target="$(echo "$target" | tr '[:upper:]' '[:lower:]')"
    if [ -z "${ide_configs[$target]+x}" ]; then
        fail "Unknown IDE: $target"
        echo "  Available: ${!ide_configs[*]}"
        exit 1
    fi

    local cfg_name="${ide_labels[$target]}"
    local process_name="${ide_processes[$target]:-$target}"
    local start_command="${ide_start_commands[$target]:-$target}"

    info "Reinstalling taskchampion MCP entry for ${cfg_name}..."
    echo ""

    # Gracefully terminate the IDE if running
    if [ "$target" = "claude" ]; then
        _claude_desktop_terminate
    else
        _ide_terminate_gracefully "$cfg_name" "$process_name"
    fi
    echo ""

    # Uninstall and reinstall
    action_uninstall "$target"
    echo ""
    
    # Pass restart flag to install if needed
    if [ "$restart_after" = true ]; then
        action_install "$target" -r
    else
        action_install "$target"
        echo ""
        if [ "$target" = "claude" ]; then
            info "You can now start Claude Desktop again if needed."
            info "Or use: ./dev.sh reinstall claude -r"
        else
            info "You can now start ${cfg_name} again if needed."
            info "Or use: ./dev.sh reinstall ${target} -r"
        fi
    fi

    info "Reinstall complete."
}

action_smoke_test() {
    # Run the MCP protocol smoke test: start the server, handshake, assert tool surface.
    # This is the automated gate for the published distribution path — it validates that
    # the server speaks correct MCP without requiring a running Claude Desktop instance.
    # See ADR 18 and tests/smoke_test_mcp.py for rationale.
    _ensure_venv
    info "Running MCP protocol smoke test..."
    "$VENV_DIR/bin/python" tests/smoke_test_mcp.py
    local rc=$?
    if [ $rc -eq 0 ]; then
        ok "Smoke test passed."
    else
        fail "Smoke test FAILED. The server did not respond correctly to MCP handshake."
        exit 1
    fi
}

action_publish() {
    _ensure_venv
    _ensure_uv

    info "Publishing TaskChampion MCP..."
    echo ""

    # 1. Run tests first
    info "Step 1/4: Running tests..."
    "$VENV_DIR/bin/python" -m pytest tests/ -v --tb=short || {
        fail "Tests failed. Fix them before publishing."
        exit 1
    }
    ok "Tests passed."
    echo ""

    # 2. Build package
    info "Step 2/4: Building package..."
    rm -rf "$PROJECT_DIR/dist"
    uv build
    ok "Package built."
    echo ""

    # 3. Publish to PyPI
    info "Step 3/4: Publishing to PyPI..."
    echo "  This requires a PyPI API token or Trusted Publishing."
    read -rp "  Publish to PyPI now? [y/N]: " pypi_answer
    if [[ "$pypi_answer" == "y" || "$pypi_answer" == "Y" ]]; then
        if command -v twine &>/dev/null; then
            twine upload dist/*
        else
            uv run --with twine twine upload dist/*
        fi
        ok "Published to PyPI."
    else
        warn "Skipped PyPI. Upload manually: twine upload dist/*"
    fi
    echo ""

    # 4. Publish to MCP Registry
    info "Step 4/4: Publishing to MCP Registry..."
    if command -v mcp-publisher &>/dev/null; then
        read -rp "  Publish to MCP Registry now? [y/N]: " mcp_answer
        if [[ "$mcp_answer" == "y" || "$mcp_answer" == "Y" ]]; then
            mcp-publisher publish
            ok "Published to MCP Registry."
        else
            warn "Skipped MCP Registry. Run manually: mcp-publisher publish"
        fi
    else
        warn "mcp-publisher not found. Install it:"
        echo "  brew install mcp-publisher"
        echo "  # or: curl -L https://github.com/modelcontextprotocol/registry/releases/..."
    fi

    echo ""
    ok "Publish workflow complete."
    info "Don't forget to:"
    echo "  1. Tag the release: git tag v$("$VENV_DIR/bin/python" -c 'from taskchampion_mcp import __version__; print(__version__)')"
    echo "  2. Push tags: git push --tags"
    echo "  3. Create a GitHub Release with changelog"
}

action_init() {
    _ensure_venv
    info "Running first-run schema initialisation wizard..."
    "$VENV_DIR/bin/python" -m taskchampion_mcp.init_schema \
        --project-dir "$PROJECT_DIR" \
        "$@"
}

action_clean() {
    info "Cleaning build artifacts and caches..."
    rm -rf "$VENV_DIR"
    rm -rf "$PROJECT_DIR/dist"
    rm -rf "$PROJECT_DIR/build"
    rm -rf "$PROJECT_DIR/.pytest_cache"
    rm -rf "$PROJECT_DIR/.ruff_cache"
    find "$PROJECT_DIR/src" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    find "$PROJECT_DIR/tests" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    rm -rf "$PROJECT_DIR/src/taskchampion_mcp.egg-info"

    # Remove taskchampion entries from IDE MCP config files
    echo ""
    info "Removing taskchampion from IDE MCP configurations..."
    local _claude_cfg
    _claude_cfg="$(_claude_desktop_config_path)"
    _remove_mcp_entry "$HOME/.codeium/windsurf/mcp_config.json" "Windsurf"
    _remove_mcp_entry "$HOME/.cursor/mcp.json" "Cursor"
    _remove_mcp_entry "$HOME/.vscode/mcp.json" "VS Code"
    _remove_mcp_entry "${_claude_cfg}" "Claude Desktop"
    # Claude Code uses its own CLI surface; clean it too if the CLI is present.
    if _claude_code_available && _claude_code_has_entry; then
        info "Removing taskchampion from Claude Code MCP config..."
        claude mcp remove taskchampion 2>/dev/null && ok "Claude Code: removed." || warn "Claude Code: remove returned non-zero."
    fi

    ok "Clean complete."
}

action_list() {
    info "Project installation status:"
    echo ""

    echo "--- Project Files ---"
    echo "  Source:   src/taskchampion_mcp/"
    find "$PROJECT_DIR/src/taskchampion_mcp" -name "*.py" 2>/dev/null | sort | while read -r f; do
        echo "    $(basename "$f")"
    done

    echo "  Schemas:  schemas/"
    ls "$PROJECT_DIR/schemas/"*.toml 2>/dev/null | while read -r f; do
        echo "    $(basename "$f")"
    done

    echo "  Tests:    tests/"
    find "$PROJECT_DIR/tests" -name "test_*.py" 2>/dev/null | sort | while read -r f; do
        echo "    $(basename "$f")"
    done

    echo ""
    echo "--- Virtual Environment ---"
    if [ -d "$VENV_DIR" ]; then
        echo "  Path: $VENV_DIR"
        echo "  Python: $("$VENV_DIR/bin/python" --version 2>/dev/null || echo 'unknown')"
        echo "  Packages:"
        uv pip list --python "$VENV_DIR/bin/python" 2>/dev/null | head -20
        local total
        total=$(uv pip list --python "$VENV_DIR/bin/python" 2>/dev/null | wc -l)
        if [ "$total" -gt 20 ]; then
            echo "  ... and $((total - 20)) more"
        fi
    else
        echo "  Not created. Run './dev.sh setup'"
    fi

    echo ""
    echo "--- Config Locations ---"
    local xdg_config="${XDG_CONFIG_HOME:-$HOME/.config}"
    local xdg_data="${XDG_DATA_HOME:-$HOME/.local/share}"
    echo "  Config: ${xdg_config}/taskchampion-mcp/config.toml"
    echo "  Audit:  ${xdg_data}/taskchampion-mcp/audit.log"
    if [ -f "${xdg_config}/taskchampion-mcp/config.toml" ]; then
        ok "Config file exists"
    else
        warn "Config file not found (will use defaults)"
    fi
}

action_help() {
    echo "TaskChampion MCP — Development Script"
    echo ""
    echo "Usage: ./dev.sh <action>"
    echo ""
    echo "Actions:"
    echo "  setup     Install Python deps, create venv, install dev dependencies"
    echo "  check     Verify all required tools and report versions"
    echo "  install   Add taskchampion MCP entry to IDE config [windsurf|cursor|vscode|claude|claude-code]"
    echo "            Use -r or --restart to gracefully restart the IDE after installation"
    echo "            (claude-code uses 'claude mcp add' CLI; no IDE restart needed)"
    echo "  uninstall Remove taskchampion MCP entry from IDE config [windsurf|cursor|vscode|claude|claude-code]"
    echo "  reinstall Reinstall taskchampion MCP entry (gracefully terminates IDE, then uninstall + install)"
    echo "            [windsurf|cursor|vscode|claude|claude-code] Use -r or --restart to restart the IDE after reinstall"
    echo "  init      First-run schema wizard (analyse tasks + taxonomy, generate schema)"
    echo "  test      Run the test suite (pass extra pytest args after)"
    echo "  lint      Run ruff linter on src/ and tests/"
    echo "  format    Run ruff formatter on src/ and tests/"
    echo "  run       Start the MCP server in stdio mode"
    echo "  inspect   Start the MCP Inspector for interactive debugging"
    echo "  smoke-test  Start server, run MCP handshake, assert tool surface (CI gate for publish path)
  publish   Build and publish to PyPI + MCP Registry"
    echo "  clean     Remove build artifacts, caches, and virtual environment"
    echo "  list      Show all project-related installed components"
    echo "  help      Show this help message"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

case "${1:-help}" in
    setup)     action_setup ;;
    check)     action_check ;;
    install)   shift; action_install "$@" ;;
    uninstall) shift; action_uninstall "$@" ;;
    reinstall) shift; action_reinstall "$@" ;;
    init)      shift; action_init "$@" ;;
    test)      shift; action_test "$@" ;;
    lint)      action_lint ;;
    format)    action_format ;;
    run)       action_run ;;
    inspect)   action_inspect ;;
    smoke-test) action_smoke_test ;;
    publish)   action_publish ;;
    clean)     action_clean ;;
    list)      action_list ;;
    help)      action_help ;;
    *)
        fail "Unknown action: $1"
        echo ""
        action_help
        exit 1
        ;;
esac
