#!/usr/bin/env bash
# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25
#
# Development orchestration script for TaskChampion MCP.
# Usage: ./dev.sh <action>
#
# Actions:
#   setup       — Install Python deps (uv), create venv, install dev dependencies
#   check       — Verify all required tools are installed and report versions
#   install     — Add taskchampion MCP entry to IDE config (windsurf/cursor/vscode/claude) [-r|--restart to restart IDE]
#   uninstall   — Remove taskchampion MCP entry from IDE config (windsurf/cursor/vscode/claude)
#   reinstall   — Reinstall taskchampion MCP entry (gracefully terminates IDE, then uninstall + install) [-r|--restart to restart IDE]
#   init        — First-run schema wizard: analyse tasks + taxonomy, generate schema
#   test        — Run the test suite
#   lint        — Run ruff linter
#   format      — Run ruff formatter
#   run         — Start the MCP server (stdio) for manual testing
#   inspect     — Start the MCP inspector for interactive debugging
#   publish     — Build and publish to PyPI + MCP Registry
#   clean       — Remove build artifacts, caches, venv
#   list        — List all project-related installed components
#   help        — Show this help message

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${PROJECT_DIR}/.venv"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; }

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_ide_terminate_gracefully() {
    # Gracefully terminate an IDE process if running
    local ide_name="$1"
    local process_name="$2"
    
    # Use case-insensitive full command line match for process detection
    if pgrep -fi "$process_name" &>/dev/null; then
        info "Gracefully terminating $ide_name..."
        # Try SIGTERM first (graceful shutdown)
        pkill -TERM -fi "$process_name" &>/dev/null || true
        
        # Wait up to 5 seconds for graceful shutdown
        local count=0
        while pgrep -fi "$process_name" &>/dev/null && [ $count -lt 5 ]; do
            sleep 1
            count=$((count + 1))
        done
        
        # If still running, force kill
        if pgrep -fi "$process_name" &>/dev/null; then
            warn "$ide_name did not shut down gracefully, force killing..."
            pkill -9 -fi "$process_name" &>/dev/null || true
            sleep 1
        fi
        
        ok "$ide_name terminated."
    else
        info "$ide_name is not running."
    fi
}

_ide_start() {
    # Start an IDE if it's available
    local ide_name="$1"
    local start_command="$2"
    
    if command -v "$start_command" &>/dev/null; then
        info "Starting $ide_name..."
        "$start_command" &>/dev/null &
        ok "$ide_name started."
    else
        warn "$start_command not found. Please start $ide_name manually."
    fi
}

_check_cmd() {
    local cmd="$1"
    local name="${2:-$1}"
    if command -v "$cmd" &>/dev/null; then
        local ver
        ver=$("$cmd" --version 2>/dev/null | head -1 || echo "unknown")
        ok "$name found: $ver"
        return 0
    else
        fail "$name not found on PATH"
        return 1
    fi
}

_ensure_uv() {
    if ! command -v uv &>/dev/null; then
        fail "uv is not installed. Install it: https://docs.astral.sh/uv/getting-started/installation/"
        exit 1
    fi
}

_ensure_venv() {
    if [ ! -d "$VENV_DIR" ]; then
        warn "Virtual environment not found. Run './dev.sh setup' first."
        exit 1
    fi
}

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------

action_setup() {
    info "Setting up development environment..."
    _ensure_uv

    info "Creating virtual environment with uv..."
    uv venv "$VENV_DIR" --python 3.12 2>/dev/null || uv venv "$VENV_DIR"

    info "Installing project in editable mode with dev dependencies..."
    uv pip install -e ".[dev]" --python "$VENV_DIR/bin/python"

    ok "Setup complete. Activate with: source .venv/bin/activate"
}

action_check() {
    info "Checking required tools..."
    echo ""

    local all_ok=true

    # Python
    if _check_cmd python3 "Python 3"; then
        python3 -c "import sys; v=sys.version_info; exit(0 if v >= (3,10) else 1)" 2>/dev/null \
            || { warn "Python 3.10+ required"; all_ok=false; }
    else
        all_ok=false
    fi

    # uv
    _check_cmd uv "uv (package manager)" || all_ok=false

    # Taskwarrior
    if command -v task &>/dev/null; then
        local tw_ver
        tw_ver=$(task _version 2>/dev/null || echo "unknown")
        ok "Taskwarrior found: v${tw_ver}"
        local major="${tw_ver%%.*}"
        if [ "$major" = "2" ]; then
            warn "Taskwarrior 2.x detected — this MCP targets 3.x"
        elif [ "$major" != "3" ]; then
            warn "Unexpected Taskwarrior version: $tw_ver"
        fi
    else
        fail "Taskwarrior (task) not found on PATH"
        all_ok=false
    fi

    # Timewarrior (optional)
    if command -v timew &>/dev/null; then
        local timew_ver
        timew_ver=$(timew --version 2>/dev/null | head -1 || echo "unknown")
        ok "Timewarrior found: ${timew_ver}"
    else
        warn "Timewarrior (timew) not found — time tracking tools will be disabled"
    fi

    # Virtual environment
    if [ -d "$VENV_DIR" ]; then
        ok "Virtual environment exists at ${VENV_DIR}"
    else
        warn "No virtual environment. Run './dev.sh setup'"
    fi

    # MCP SDK
    if [ -d "$VENV_DIR" ] && "$VENV_DIR/bin/python" -c "import mcp" 2>/dev/null; then
        local mcp_ver
        mcp_ver=$("$VENV_DIR/bin/python" -c "import importlib.metadata; print(importlib.metadata.version('mcp'))" 2>/dev/null || echo "unknown")
        ok "MCP SDK installed: v${mcp_ver}"
    else
        warn "MCP SDK not installed. Run './dev.sh setup'"
    fi

    # IDE MCP config files — check for existing taskchampion server entry
    echo ""
    info "Checking IDE MCP configurations..."
    local mcp_configs=(
        "$HOME/.codeium/windsurf/mcp_config.json:Windsurf"
        "$HOME/.cursor/mcp.json:Cursor"
        "$HOME/.vscode/mcp.json:VS Code"
        "${XDG_CONFIG_HOME:-$HOME/.config}/claude/claude_desktop_config.json:Claude Desktop"
    )
    local found_any_config=false
    for entry in "${mcp_configs[@]}"; do
        local cfg_path="${entry%%:*}"
        local cfg_name="${entry##*:}"
        if [ -f "$cfg_path" ]; then
            found_any_config=true
            if grep -qi "taskchampion" "$cfg_path" 2>/dev/null; then
                ok "${cfg_name}: taskchampion entry found in $(basename "$cfg_path")"
            else
                warn "${cfg_name}: config exists but no taskchampion entry (${cfg_path})"
            fi
        fi
    done
    if ! $found_any_config; then
        warn "No IDE MCP config files found. Configure your IDE to use taskchampion-mcp-server."
    fi

    echo ""
    if $all_ok; then
        ok "All required tools are available."
    else
        fail "Some tools are missing. See warnings above."
    fi
}

action_test() {
    _ensure_venv
    info "Running tests..."
    if [ $# -eq 0 ]; then
        "$VENV_DIR/bin/python" -m pytest -v
    else
        "$VENV_DIR/bin/python" -m pytest "$@"
    fi
}

action_lint() {
    _ensure_venv
    info "Running ruff linter..."
    "$VENV_DIR/bin/python" -m ruff check src/ tests/
}

action_format() {
    _ensure_venv
    info "Running ruff formatter..."
    "$VENV_DIR/bin/python" -m ruff format src/ tests/
}

action_run() {
    _ensure_venv
    info "Starting TaskChampion MCP server (stdio)..."
    "$VENV_DIR/bin/python" -m taskchampion_mcp.server
}

action_inspect() {
    _ensure_venv
    info "Starting MCP Inspector..."
    if command -v npx &>/dev/null; then
        npx -y @modelcontextprotocol/inspector "$VENV_DIR/bin/python" -m taskchampion_mcp.server
    else
        warn "npx not found. Install Node.js to use the MCP inspector."
        warn "Alternatively, run: uv run mcp dev src/taskchampion_mcp/server.py"
    fi
}

_remove_mcp_entry() {
    # Remove the 'taskchampion' key from mcpServers in a JSON config file.
    # Uses Python for safe JSON manipulation.
    local cfg_path="$1"
    local cfg_name="$2"
    if [ ! -f "$cfg_path" ]; then
        return
    fi
    if ! grep -qi "taskchampion" "$cfg_path" 2>/dev/null; then
        return
    fi
    info "Removing taskchampion entry from ${cfg_name} config (${cfg_path})..."
    python3 -c "
import json, sys
path = sys.argv[1]
with open(path) as f:
    data = json.load(f)
servers = data.get('mcpServers', {})
if 'taskchampion' in servers:
    del servers['taskchampion']
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)
        f.write('\n')
    print('  Removed.')
else:
    print('  No taskchampion entry found.')
" "$cfg_path"
}

_upsert_mcp_entry() {
    # Insert or update the 'taskchampion' key in mcpServers of a JSON config file.
    # Creates the file (and parent dirs) if it doesn't exist.
    local cfg_path="$1"
    local cfg_name="$2"
    local server_command="$3"
    local server_args="$4"  # JSON array string, e.g. '["-m", "taskchampion_mcp.server"]'

    mkdir -p "$(dirname "$cfg_path")"

    python3 -c "
import json, sys, os

path, cmd, args_json = sys.argv[1], sys.argv[2], sys.argv[3]
args = json.loads(args_json)

if os.path.isfile(path):
    with open(path) as f:
        data = json.load(f)
else:
    data = {}

data.setdefault('mcpServers', {})
data['mcpServers']['taskchampion'] = {
    'command': cmd,
    'args': args,
}

with open(path, 'w') as f:
    json.dump(data, f, indent=2)
    f.write('\n')
" "$cfg_path" "$server_command" "$server_args"
}

action_install() {
    _ensure_venv

    local server_command="${VENV_DIR}/bin/python"
    local server_args='["-m", "taskchampion_mcp.server"]'

    # All known IDE MCP config locations
    local -A ide_configs=(
        [windsurf]="$HOME/.codeium/windsurf/mcp_config.json"
        [cursor]="$HOME/.cursor/mcp.json"
        [vscode]="$HOME/.vscode/mcp.json"
        [claude]="${XDG_CONFIG_HOME:-$HOME/.config}/claude/claude_desktop_config.json"
    )
    local -A ide_labels=(
        [windsurf]="Windsurf"
        [cursor]="Cursor"
        [vscode]="VS Code"
        [claude]="Claude Desktop"
    )
    # IDE process names for graceful termination (use partial match patterns)
    local -A ide_processes=(
        [windsurf]="windsurf"
        [cursor]="cursor"
        [vscode]="code"
        [claude]="claude"
    )
    # IDE start commands
    local -A ide_start_commands=(
        [windsurf]="windsurf"
        [cursor]="cursor"
        [vscode]="code"
        [claude]="claude"
    )

    local target="${1:-}"
    local restart_after=false

    # Parse arguments for -r or --restart flag
    shift || true
    while [ $# -gt 0 ]; do
        case "$1" in
            -r|--restart)
                restart_after=true
                shift
                ;;
            *)
                # Unknown argument, might be the IDE target if target was empty
                if [ -z "$target" ]; then
                    target="$1"
                    shift
                else
                    fail "Unknown argument: $1"
                    echo "  Usage: ./dev.sh install <ide> [-r|--restart]"
                    exit 1
                fi
                ;;
        esac
    done

    if [ -n "$target" ]; then
        target="$(echo "$target" | tr '[:upper:]' '[:lower:]')"
        if [ -z "${ide_configs[$target]+x}" ]; then
            fail "Unknown IDE: $target"
            echo "  Available: ${!ide_configs[*]}"
            exit 1
        fi
        local cfg_path="${ide_configs[$target]}"
        local cfg_name="${ide_labels[$target]}"
        local process_name="${ide_processes[$target]:-$target}"
        local start_command="${ide_start_commands[$target]:-$target}"

        info "Installing taskchampion MCP entry into ${cfg_name} config..."
        _upsert_mcp_entry "$cfg_path" "$cfg_name" "$server_command" "$server_args"
        ok "${cfg_name}: taskchampion entry written to ${cfg_path}"
        echo ""
        info "Entry added:"
        echo "  command: ${server_command}"
        echo "  args:    -m taskchampion_mcp.server"
        echo ""

        if [ "$restart_after" = true ]; then
            info "Restarting ${cfg_name}..."
            _ide_terminate_gracefully "$cfg_name" "$process_name"
            sleep 1
            _ide_start "$cfg_name" "$start_command"
            echo ""
        else
            info "Next steps:"
            echo "  1. Restart your IDE to pick up the new MCP server"
            echo "     Or use: ./dev.sh install ${target} -r"
            echo "  2. Ask the LLM to help you configure your role level and schema/taxonomy"
            echo "     Example: 'Help me set up my TaskChampion role and task schema'"
        fi
        return
    fi

    # Interactive: show detected IDEs and let user pick
    echo "Available IDE targets:"
    echo ""
    local idx=1
    local -a keys=()
    for key in windsurf cursor vscode claude; do
        local cfg_path="${ide_configs[$key]}"
        local cfg_name="${ide_labels[$key]}"
        local status=""
        if [ -f "$cfg_path" ]; then
            if grep -qi "taskchampion" "$cfg_path" 2>/dev/null; then
                status=" ${GREEN}(already configured)${NC}"
            else
                status=" ${YELLOW}(config exists, no entry)${NC}"
            fi
        else
            local cfg_dir
            cfg_dir="$(dirname "$cfg_path")"
            if [ -d "$cfg_dir" ]; then
                status=" ${CYAN}(dir exists, will create config)${NC}"
            else
                status=""
            fi
        fi
        echo -e "  ${idx}) ${cfg_name}${status}"
        keys+=("$key")
        idx=$((idx + 1))
    done
    echo -e "  a) All of the above"
    echo ""
    read -rp "Select target(s) [1-4, a, or comma-separated]: " selection

    local selected=()
    if [[ "$selection" == "a" || "$selection" == "A" ]]; then
        selected=("${keys[@]}")
    else
        IFS=',' read -ra parts <<< "$selection"
        for part in "${parts[@]}"; do
            part="$(echo "$part" | tr -d ' ')"
            if [[ "$part" =~ ^[1-4]$ ]]; then
                selected+=("${keys[$((part - 1))]}")
            else
                warn "Skipping invalid selection: $part"
            fi
        done
    fi

    if [ ${#selected[@]} -eq 0 ]; then
        warn "No targets selected."
        return
    fi

    echo ""
    for key in "${selected[@]}"; do
        local cfg_path="${ide_configs[$key]}"
        local cfg_name="${ide_labels[$key]}"
        info "Installing into ${cfg_name}..."
        _upsert_mcp_entry "$cfg_path" "$cfg_name" "$server_command" "$server_args"
        ok "${cfg_name}: ${cfg_path}"
    done

    echo ""
    info "MCP server entry:"
    echo "  command: ${server_command}"
    echo "  args:    -m taskchampion_mcp.server"
    echo ""

    # Ask if user wants to restart IDEs
    if [ ${#selected[@]} -eq 1 ]; then
        local key="${selected[0]}"
        local cfg_name="${ide_labels[$key]}"
        local process_name="${ide_processes[$key]:-$key}"
        local start_command="${ide_start_commands[$key]:-$key}"
        read -rp "Restart ${cfg_name} now? [y/N]: " restart_answer
        if [[ "$restart_answer" == "y" || "$restart_answer" == "Y" ]]; then
            _ide_terminate_gracefully "$cfg_name" "$process_name"
            sleep 1
            _ide_start "$cfg_name" "$start_command"
        else
            info "Next steps:"
            echo "  1. Restart your IDE to pick up the new MCP server"
            echo "  2. Ask the LLM to help you configure your role level and schema/taxonomy"
            echo "     Example: 'Help me set up my TaskChampion role and task schema'"
        fi
    else
        info "Next steps:"
        echo "  1. Restart your IDE(s) to pick up the new MCP server"
        echo "  2. Ask the LLM to help you configure your role level and schema/taxonomy"
        echo "     Example: 'Help me set up my TaskChampion role and task schema'"
    fi
    ok "Install complete."
}

action_uninstall() {
    # All known IDE MCP config locations
    local -A ide_configs=(
        [windsurf]="$HOME/.codeium/windsurf/mcp_config.json"
        [cursor]="$HOME/.cursor/mcp.json"
        [vscode]="$HOME/.vscode/mcp.json"
        [claude]="${XDG_CONFIG_HOME:-$HOME/.config}/claude/claude_desktop_config.json"
    )
    local -A ide_labels=(
        [windsurf]="Windsurf"
        [cursor]="Cursor"
        [vscode]="VS Code"
        [claude]="Claude Desktop"
    )

    local target="${1:-}"

    if [ -n "$target" ]; then
        target="$(echo "$target" | tr '[:upper:]' '[:lower:]')"
        if [ -z "${ide_configs[$target]+x}" ]; then
            fail "Unknown IDE: $target"
            echo "  Available: ${!ide_configs[*]}"
            exit 1
        fi
        local cfg_path="${ide_configs[$target]}"
        local cfg_name="${ide_labels[$target]}"
        _remove_mcp_entry "$cfg_path" "$cfg_name"
        ok "${cfg_name}: taskchampion entry removed from ${cfg_path}"
        echo ""
        info "Restart your IDE to pick up the changes."
        return
    fi

    # Interactive: show detected IDEs and let user pick
    echo "Available IDE targets:"
    echo ""
    local idx=1
    local -a keys=()
    for key in windsurf cursor vscode claude; do
        local cfg_path="${ide_configs[$key]}"
        local cfg_name="${ide_labels[$key]}"
        local status=""
        if [ -f "$cfg_path" ]; then
            if grep -qi "taskchampion" "$cfg_path" 2>/dev/null; then
                status=" ${GREEN}(has taskchampion-mcp entry)${NC}"
            else
                status=" ${YELLOW}(no taskchampion-mcp entry)${NC}"
            fi
        else
            status=" ${YELLOW}(config not found)${NC}"
        fi
        echo -e "  ${idx}) ${cfg_name}${status}"
        keys+=("$key")
        idx=$((idx + 1))
    done
    echo -e "  a) All of the above"
    echo ""
    read -rp "Select target(s) to uninstall from [1-4, a, or comma-separated]: " selection

    local selected=()
    if [[ "$selection" == "a" || "$selection" == "A" ]]; then
        selected=("${keys[@]}")
    else
        IFS=',' read -ra parts <<< "$selection"
        for part in "${parts[@]}"; do
            part="$(echo "$part" | tr -d ' ')"
            if [[ "$part" =~ ^[1-4]$ ]]; then
                selected+=("${keys[$((part - 1))]}")
            else
                warn "Skipping invalid selection: $part"
            fi
        done
    fi

    if [ ${#selected[@]} -eq 0 ]; then
        warn "No targets selected."
        return
    fi

    echo ""
    for key in "${selected[@]}"; do
        local cfg_path="${ide_configs[$key]}"
        local cfg_name="${ide_labels[$key]}"
        _remove_mcp_entry "$cfg_path" "$cfg_name"
        ok "${cfg_name}: ${cfg_path}"
    done

    echo ""
    info "Restart your IDE to pick up the changes."
}

action_reinstall() {
    # All known IDE MCP config locations
    local -A ide_configs=(
        [windsurf]="$HOME/.codeium/windsurf/mcp_config.json"
        [cursor]="$HOME/.cursor/mcp.json"
        [vscode]="$HOME/.vscode/mcp.json"
        [claude]="${XDG_CONFIG_HOME:-$HOME/.config}/claude/claude_desktop_config.json"
    )
    local -A ide_labels=(
        [windsurf]="Windsurf"
        [cursor]="Cursor"
        [vscode]="VS Code"
        [claude]="Claude Desktop"
    )
    # IDE process names for graceful termination (use partial match patterns)
    local -A ide_processes=(
        [windsurf]="windsurf"
        [cursor]="cursor"
        [vscode]="code"
        [claude]="claude"
    )
    # IDE start commands
    local -A ide_start_commands=(
        [windsurf]="windsurf"
        [cursor]="cursor"
        [vscode]="code"
        [claude]="claude"
    )

    local target="${1:-}"
    local restart_after=false

    # Parse arguments for -r or --restart flag
    shift || true
    while [ $# -gt 0 ]; do
        case "$1" in
            -r|--restart)
                restart_after=true
                shift
                ;;
            *)
                fail "Unknown argument: $1"
                echo "  Usage: ./dev.sh reinstall <ide> [-r|--restart]"
                exit 1
                ;;
        esac
    done

    if [ -z "$target" ]; then
        fail "reinstall requires an IDE target"
        echo "  Usage: ./dev.sh reinstall <ide> [-r|--restart]"
        echo "  Available: windsurf, cursor, vscode, claude"
        exit 1
    fi

    target="$(echo "$target" | tr '[:upper:]' '[:lower:]')"
    if [ -z "${ide_configs[$target]+x}" ]; then
        fail "Unknown IDE: $target"
        echo "  Available: ${!ide_configs[*]}"
        exit 1
    fi

    local cfg_name="${ide_labels[$target]}"
    local process_name="${ide_processes[$target]:-$target}"
    local start_command="${ide_start_commands[$target]:-$target}"

    info "Reinstalling taskchampion MCP entry for ${cfg_name}..."
    echo ""

    # Gracefully terminate the IDE if running
    _ide_terminate_gracefully "$cfg_name" "$process_name"
    echo ""

    # Uninstall and reinstall
    action_uninstall "$target"
    echo ""
    
    # Pass restart flag to install if needed
    if [ "$restart_after" = true ]; then
        action_install "$target" -r
    else
        action_install "$target"
    fi
    echo ""

    info "Reinstall complete."
    if [ "$restart_after" = false ]; then
        info "You can now start ${cfg_name} again if needed."
        info "Or use: ./dev.sh reinstall ${target} -r"
    fi
}

action_publish() {
    _ensure_venv
    _ensure_uv

    info "Publishing TaskChampion MCP..."
    echo ""

    # 1. Run tests first
    info "Step 1/4: Running tests..."
    "$VENV_DIR/bin/python" -m pytest tests/ -v --tb=short || {
        fail "Tests failed. Fix them before publishing."
        exit 1
    }
    ok "Tests passed."
    echo ""

    # 2. Build package
    info "Step 2/4: Building package..."
    rm -rf "$PROJECT_DIR/dist"
    uv build
    ok "Package built."
    echo ""

    # 3. Publish to PyPI
    info "Step 3/4: Publishing to PyPI..."
    echo "  This requires a PyPI API token or Trusted Publishing."
    read -rp "  Publish to PyPI now? [y/N]: " pypi_answer
    if [[ "$pypi_answer" == "y" || "$pypi_answer" == "Y" ]]; then
        if command -v twine &>/dev/null; then
            twine upload dist/*
        else
            uv run --with twine twine upload dist/*
        fi
        ok "Published to PyPI."
    else
        warn "Skipped PyPI. Upload manually: twine upload dist/*"
    fi
    echo ""

    # 4. Publish to MCP Registry
    info "Step 4/4: Publishing to MCP Registry..."
    if command -v mcp-publisher &>/dev/null; then
        read -rp "  Publish to MCP Registry now? [y/N]: " mcp_answer
        if [[ "$mcp_answer" == "y" || "$mcp_answer" == "Y" ]]; then
            mcp-publisher publish
            ok "Published to MCP Registry."
        else
            warn "Skipped MCP Registry. Run manually: mcp-publisher publish"
        fi
    else
        warn "mcp-publisher not found. Install it:"
        echo "  brew install mcp-publisher"
        echo "  # or: curl -L https://github.com/modelcontextprotocol/registry/releases/..."
    fi

    echo ""
    ok "Publish workflow complete."
    info "Don't forget to:"
    echo "  1. Tag the release: git tag v$("$VENV_DIR/bin/python" -c 'from taskchampion_mcp import __version__; print(__version__)')"
    echo "  2. Push tags: git push --tags"
    echo "  3. Create a GitHub Release with changelog"
}

action_init() {
    _ensure_venv
    info "Running first-run schema initialisation wizard..."
    "$VENV_DIR/bin/python" -m taskchampion_mcp.init_schema \
        --project-dir "$PROJECT_DIR" \
        "$@"
}

action_clean() {
    info "Cleaning build artifacts and caches..."
    rm -rf "$VENV_DIR"
    rm -rf "$PROJECT_DIR/dist"
    rm -rf "$PROJECT_DIR/build"
    rm -rf "$PROJECT_DIR/.pytest_cache"
    rm -rf "$PROJECT_DIR/.ruff_cache"
    find "$PROJECT_DIR/src" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    find "$PROJECT_DIR/tests" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    rm -rf "$PROJECT_DIR/src/taskchampion_mcp.egg-info"

    # Remove taskchampion entries from IDE MCP config files
    echo ""
    info "Removing taskchampion from IDE MCP configurations..."
    _remove_mcp_entry "$HOME/.codeium/windsurf/mcp_config.json" "Windsurf"
    _remove_mcp_entry "$HOME/.cursor/mcp.json" "Cursor"
    _remove_mcp_entry "$HOME/.vscode/mcp.json" "VS Code"
    _remove_mcp_entry "${XDG_CONFIG_HOME:-$HOME/.config}/claude/claude_desktop_config.json" "Claude Desktop"

    ok "Clean complete."
}

action_list() {
    info "Project installation status:"
    echo ""

    echo "--- Project Files ---"
    echo "  Source:   src/taskchampion_mcp/"
    find "$PROJECT_DIR/src/taskchampion_mcp" -name "*.py" 2>/dev/null | sort | while read -r f; do
        echo "    $(basename "$f")"
    done

    echo "  Schemas:  schemas/"
    ls "$PROJECT_DIR/schemas/"*.toml 2>/dev/null | while read -r f; do
        echo "    $(basename "$f")"
    done

    echo "  Tests:    tests/"
    find "$PROJECT_DIR/tests" -name "test_*.py" 2>/dev/null | sort | while read -r f; do
        echo "    $(basename "$f")"
    done

    echo ""
    echo "--- Virtual Environment ---"
    if [ -d "$VENV_DIR" ]; then
        echo "  Path: $VENV_DIR"
        echo "  Python: $("$VENV_DIR/bin/python" --version 2>/dev/null || echo 'unknown')"
        echo "  Packages:"
        uv pip list --python "$VENV_DIR/bin/python" 2>/dev/null | head -20
        local total
        total=$(uv pip list --python "$VENV_DIR/bin/python" 2>/dev/null | wc -l)
        if [ "$total" -gt 20 ]; then
            echo "  ... and $((total - 20)) more"
        fi
    else
        echo "  Not created. Run './dev.sh setup'"
    fi

    echo ""
    echo "--- Config Locations ---"
    local xdg_config="${XDG_CONFIG_HOME:-$HOME/.config}"
    local xdg_data="${XDG_DATA_HOME:-$HOME/.local/share}"
    echo "  Config: ${xdg_config}/taskchampion-mcp/config.toml"
    echo "  Audit:  ${xdg_data}/taskchampion-mcp/audit.log"
    if [ -f "${xdg_config}/taskchampion-mcp/config.toml" ]; then
        ok "Config file exists"
    else
        warn "Config file not found (will use defaults)"
    fi
}

action_help() {
    echo "TaskChampion MCP — Development Script"
    echo ""
    echo "Usage: ./dev.sh <action>"
    echo ""
    echo "Actions:"
    echo "  setup     Install Python deps, create venv, install dev dependencies"
    echo "  check     Verify all required tools and report versions"
    echo "  install   Add taskchampion MCP entry to IDE config [windsurf|cursor|vscode|claude]"
    echo "            Use -r or --restart to gracefully restart the IDE after installation"
    echo "  uninstall Remove taskchampion MCP entry from IDE config [windsurf|cursor|vscode|claude]"
    echo "  reinstall Reinstall taskchampion MCP entry (gracefully terminates IDE, then uninstall + install)"
    echo "            [windsurf|cursor|vscode|claude] Use -r or --restart to restart the IDE after reinstall"
    echo "  init      First-run schema wizard (analyse tasks + taxonomy, generate schema)"
    echo "  test      Run the test suite (pass extra pytest args after)"
    echo "  lint      Run ruff linter on src/ and tests/"
    echo "  format    Run ruff formatter on src/ and tests/"
    echo "  run       Start the MCP server in stdio mode"
    echo "  inspect   Start the MCP Inspector for interactive debugging"
    echo "  publish   Build and publish to PyPI + MCP Registry"
    echo "  clean     Remove build artifacts, caches, and virtual environment"
    echo "  list      Show all project-related installed components"
    echo "  help      Show this help message"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

case "${1:-help}" in
    setup)     action_setup ;;
    check)     action_check ;;
    install)   shift; action_install "$@" ;;
    uninstall) shift; action_uninstall "$@" ;;
    reinstall) shift; action_reinstall "$@" ;;
    init)      shift; action_init "$@" ;;
    test)      shift; action_test "$@" ;;
    lint)      action_lint ;;
    format)    action_format ;;
    run)       action_run ;;
    inspect)   action_inspect ;;
    publish)   action_publish ;;
    clean)     action_clean ;;
    list)      action_list ;;
    help)      action_help ;;
    *)
        fail "Unknown action: $1"
        echo ""
        action_help
        exit 1
        ;;
esac
