#!/usr/bin/env bash
# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25
#
# Development orchestration script for TaskChampion MCP.
# Usage: ./dev.sh <action>
#
# Actions:
#   setup       — Install Python deps (uv), create venv, install dev dependencies
#   check       — Verify all required tools are installed and report versions
#   test        — Run the test suite
#   lint        — Run ruff linter
#   format      — Run ruff formatter
#   run         — Start the MCP server (stdio) for manual testing
#   inspect     — Start the MCP inspector for interactive debugging
#   clean       — Remove build artifacts, caches, venv
#   list        — List all project-related installed components
#   help        — Show this help message

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${PROJECT_DIR}/.venv"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; }

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_check_cmd() {
    local cmd="$1"
    local name="${2:-$1}"
    if command -v "$cmd" &>/dev/null; then
        local ver
        ver=$("$cmd" --version 2>/dev/null | head -1 || echo "unknown")
        ok "$name found: $ver"
        return 0
    else
        fail "$name not found on PATH"
        return 1
    fi
}

_ensure_uv() {
    if ! command -v uv &>/dev/null; then
        fail "uv is not installed. Install it: https://docs.astral.sh/uv/getting-started/installation/"
        exit 1
    fi
}

_ensure_venv() {
    if [ ! -d "$VENV_DIR" ]; then
        warn "Virtual environment not found. Run './dev.sh setup' first."
        exit 1
    fi
}

# ---------------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------------

action_setup() {
    info "Setting up development environment..."
    _ensure_uv

    info "Creating virtual environment with uv..."
    uv venv "$VENV_DIR" --python 3.12 2>/dev/null || uv venv "$VENV_DIR"

    info "Installing project in editable mode with dev dependencies..."
    uv pip install -e ".[dev]" --python "$VENV_DIR/bin/python"

    ok "Setup complete. Activate with: source .venv/bin/activate"
}

action_check() {
    info "Checking required tools..."
    echo ""

    local all_ok=true

    # Python
    if _check_cmd python3 "Python 3"; then
        python3 -c "import sys; v=sys.version_info; exit(0 if v >= (3,10) else 1)" 2>/dev/null \
            || { warn "Python 3.10+ required"; all_ok=false; }
    else
        all_ok=false
    fi

    # uv
    _check_cmd uv "uv (package manager)" || all_ok=false

    # Taskwarrior
    if command -v task &>/dev/null; then
        local tw_ver
        tw_ver=$(task _version 2>/dev/null || echo "unknown")
        ok "Taskwarrior found: v${tw_ver}"
        local major="${tw_ver%%.*}"
        if [ "$major" = "2" ]; then
            warn "Taskwarrior 2.x detected — this MCP targets 3.x"
        elif [ "$major" != "3" ]; then
            warn "Unexpected Taskwarrior version: $tw_ver"
        fi
    else
        fail "Taskwarrior (task) not found on PATH"
        all_ok=false
    fi

    # Timewarrior (optional)
    if command -v timew &>/dev/null; then
        local timew_ver
        timew_ver=$(timew --version 2>/dev/null | head -1 || echo "unknown")
        ok "Timewarrior found: ${timew_ver}"
    else
        warn "Timewarrior (timew) not found — time tracking tools will be disabled"
    fi

    # Virtual environment
    if [ -d "$VENV_DIR" ]; then
        ok "Virtual environment exists at ${VENV_DIR}"
    else
        warn "No virtual environment. Run './dev.sh setup'"
    fi

    # MCP SDK
    if [ -d "$VENV_DIR" ] && "$VENV_DIR/bin/python" -c "import mcp" 2>/dev/null; then
        local mcp_ver
        mcp_ver=$("$VENV_DIR/bin/python" -c "import importlib.metadata; print(importlib.metadata.version('mcp'))" 2>/dev/null || echo "unknown")
        ok "MCP SDK installed: v${mcp_ver}"
    else
        warn "MCP SDK not installed. Run './dev.sh setup'"
    fi

    # IDE MCP config files — check for existing taskchampion server entry
    echo ""
    info "Checking IDE MCP configurations..."
    local mcp_configs=(
        "$HOME/.codeium/windsurf/mcp_config.json:Windsurf"
        "$HOME/.cursor/mcp.json:Cursor"
        "$HOME/.vscode/mcp.json:VS Code"
        "${XDG_CONFIG_HOME:-$HOME/.config}/claude/claude_desktop_config.json:Claude Desktop"
    )
    local found_any_config=false
    for entry in "${mcp_configs[@]}"; do
        local cfg_path="${entry%%:*}"
        local cfg_name="${entry##*:}"
        if [ -f "$cfg_path" ]; then
            found_any_config=true
            if grep -qi "taskchampion" "$cfg_path" 2>/dev/null; then
                ok "${cfg_name}: taskchampion entry found in $(basename "$cfg_path")"
            else
                warn "${cfg_name}: config exists but no taskchampion entry (${cfg_path})"
            fi
        fi
    done
    if ! $found_any_config; then
        warn "No IDE MCP config files found. Configure your IDE to use taskchampion-mcp-server."
    fi

    echo ""
    if $all_ok; then
        ok "All required tools are available."
    else
        fail "Some tools are missing. See warnings above."
    fi
}

action_test() {
    _ensure_venv
    info "Running tests..."
    if [ $# -eq 0 ]; then
        "$VENV_DIR/bin/python" -m pytest -v
    else
        "$VENV_DIR/bin/python" -m pytest "$@"
    fi
}

action_lint() {
    _ensure_venv
    info "Running ruff linter..."
    "$VENV_DIR/bin/python" -m ruff check src/ tests/
}

action_format() {
    _ensure_venv
    info "Running ruff formatter..."
    "$VENV_DIR/bin/python" -m ruff format src/ tests/
}

action_run() {
    _ensure_venv
    info "Starting TaskChampion MCP server (stdio)..."
    "$VENV_DIR/bin/python" -m taskchampion_mcp.server
}

action_inspect() {
    _ensure_venv
    info "Starting MCP Inspector..."
    if command -v npx &>/dev/null; then
        npx -y @modelcontextprotocol/inspector "$VENV_DIR/bin/python" -m taskchampion_mcp.server
    else
        warn "npx not found. Install Node.js to use the MCP inspector."
        warn "Alternatively, run: uv run mcp dev src/taskchampion_mcp/server.py"
    fi
}

_remove_mcp_entry() {
    # Remove the 'taskchampion' key from mcpServers in a JSON config file.
    # Uses Python for safe JSON manipulation.
    local cfg_path="$1"
    local cfg_name="$2"
    if [ ! -f "$cfg_path" ]; then
        return
    fi
    if ! grep -qi "taskchampion" "$cfg_path" 2>/dev/null; then
        return
    fi
    info "Removing taskchampion entry from ${cfg_name} config (${cfg_path})..."
    python3 -c "
import json, sys
path = sys.argv[1]
with open(path) as f:
    data = json.load(f)
servers = data.get('mcpServers', {})
if 'taskchampion' in servers:
    del servers['taskchampion']
    with open(path, 'w') as f:
        json.dump(data, f, indent=2)
        f.write('\n')
    print('  Removed.')
else:
    print('  No taskchampion entry found.')
" "$cfg_path"
}

action_clean() {
    info "Cleaning build artifacts and caches..."
    rm -rf "$VENV_DIR"
    rm -rf "$PROJECT_DIR/dist"
    rm -rf "$PROJECT_DIR/build"
    rm -rf "$PROJECT_DIR/.pytest_cache"
    rm -rf "$PROJECT_DIR/.ruff_cache"
    find "$PROJECT_DIR/src" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    find "$PROJECT_DIR/tests" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    rm -rf "$PROJECT_DIR/src/taskchampion_mcp.egg-info"

    # Remove taskchampion entries from IDE MCP config files
    echo ""
    info "Removing taskchampion from IDE MCP configurations..."
    _remove_mcp_entry "$HOME/.codeium/windsurf/mcp_config.json" "Windsurf"
    _remove_mcp_entry "$HOME/.cursor/mcp.json" "Cursor"
    _remove_mcp_entry "$HOME/.vscode/mcp.json" "VS Code"
    _remove_mcp_entry "${XDG_CONFIG_HOME:-$HOME/.config}/claude/claude_desktop_config.json" "Claude Desktop"

    ok "Clean complete."
}

action_list() {
    info "Project installation status:"
    echo ""

    echo "--- Project Files ---"
    echo "  Source:   src/taskchampion_mcp/"
    find "$PROJECT_DIR/src/taskchampion_mcp" -name "*.py" 2>/dev/null | sort | while read -r f; do
        echo "    $(basename "$f")"
    done

    echo "  Schemas:  schemas/"
    ls "$PROJECT_DIR/schemas/"*.toml 2>/dev/null | while read -r f; do
        echo "    $(basename "$f")"
    done

    echo "  Tests:    tests/"
    find "$PROJECT_DIR/tests" -name "test_*.py" 2>/dev/null | sort | while read -r f; do
        echo "    $(basename "$f")"
    done

    echo ""
    echo "--- Virtual Environment ---"
    if [ -d "$VENV_DIR" ]; then
        echo "  Path: $VENV_DIR"
        echo "  Python: $("$VENV_DIR/bin/python" --version 2>/dev/null || echo 'unknown')"
        echo "  Packages:"
        uv pip list --python "$VENV_DIR/bin/python" 2>/dev/null | head -20
        local total
        total=$(uv pip list --python "$VENV_DIR/bin/python" 2>/dev/null | wc -l)
        if [ "$total" -gt 20 ]; then
            echo "  ... and $((total - 20)) more"
        fi
    else
        echo "  Not created. Run './dev.sh setup'"
    fi

    echo ""
    echo "--- Config Locations ---"
    local xdg_config="${XDG_CONFIG_HOME:-$HOME/.config}"
    local xdg_data="${XDG_DATA_HOME:-$HOME/.local/share}"
    echo "  Config: ${xdg_config}/taskchampion-mcp/config.toml"
    echo "  Audit:  ${xdg_data}/taskchampion-mcp/audit.log"
    if [ -f "${xdg_config}/taskchampion-mcp/config.toml" ]; then
        ok "Config file exists"
    else
        warn "Config file not found (will use defaults)"
    fi
}

action_help() {
    echo "TaskChampion MCP — Development Script"
    echo ""
    echo "Usage: ./dev.sh <action>"
    echo ""
    echo "Actions:"
    echo "  setup     Install Python deps, create venv, install dev dependencies"
    echo "  check     Verify all required tools and report versions"
    echo "  test      Run the test suite (pass extra pytest args after)"
    echo "  lint      Run ruff linter on src/ and tests/"
    echo "  format    Run ruff formatter on src/ and tests/"
    echo "  run       Start the MCP server in stdio mode"
    echo "  inspect   Start the MCP Inspector for interactive debugging"
    echo "  clean     Remove build artifacts, caches, and virtual environment"
    echo "  list      Show all project-related installed components"
    echo "  help      Show this help message"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

case "${1:-help}" in
    setup)   action_setup ;;
    check)   action_check ;;
    test)    shift; action_test "$@" ;;
    lint)    action_lint ;;
    format)  action_format ;;
    run)     action_run ;;
    inspect) action_inspect ;;
    clean)   action_clean ;;
    list)    action_list ;;
    help)    action_help ;;
    *)
        fail "Unknown action: $1"
        echo ""
        action_help
        exit 1
        ;;
esac
