# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25

"""TaskChampion MCP — Model Context Protocol server for Taskwarrior 3.x."""

__version__ = "1.0.0"
