# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25

"""Configuration loading and defaults for TaskChampion MCP server."""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib


# ---------------------------------------------------------------------------
# Roles
# ---------------------------------------------------------------------------


class Role:
    CONTRIBUTOR = "CONTRIBUTOR"
    GENERATOR = "GENERATOR"
    MANAGER = "MANAGER"

    _HIERARCHY = [CONTRIBUTOR, GENERATOR, MANAGER]

    @classmethod
    def validate(cls, value: str) -> str:
        upper = value.upper()
        if upper not in cls._HIERARCHY:
            raise ValueError(f"Invalid role '{value}'. Must be one of: {cls._HIERARCHY}")
        return upper

    @classmethod
    def level(cls, role: str) -> int:
        return cls._HIERARCHY.index(role.upper())

    @classmethod
    def has_permission(cls, current_role: str, required_role: str) -> bool:
        return cls.level(current_role) >= cls.level(required_role)


# ---------------------------------------------------------------------------
# Configuration data class
# ---------------------------------------------------------------------------


@dataclass
class ServerConfig:
    role: str = Role.CONTRIBUTOR
    schema_name: str = "minimal"
    schema_path: str | None = None
    task_binary: str = "task"
    timew_binary: str = "timew"

    # Configuration file status
    config_file_exists: bool = False
    explicit_role_configured: bool = False
    explicit_schema_configured:bool = False
    explicit_taxonomy_configured: bool = False
    redacted_fields: list[str] = field(default_factory=list)
    taxonomy_path: str | None = None

    # Security settings
    rate_limit_per_minute: int = 30
    rate_limit_per_hour: int = 200
    create_limit_per_hour: int = 50
    require_confirmation: bool = True
    dry_run_default: bool = False
    audit_log_path: str = ""
    taskwarrior_override_rc: str | None = None


# ---------------------------------------------------------------------------
# Config file locations
# ---------------------------------------------------------------------------


def _xdg_config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))


def _xdg_data_home() -> Path:
    return Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))


def default_config_path() -> Path:
    return _xdg_config_home() / "taskchampion-mcp" / "config.toml"


def default_audit_log_path() -> Path:
    return _xdg_data_home() / "taskchampion-mcp" / "audit.log"


def default_schema_dir() -> Path:
    """Return the bundled schemas/ directory shipped with the package."""
    return Path(__file__).resolve().parent.parent.parent / "schemas"


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def _deep_get(data: dict[str, Any], *keys: str, default: Any = None) -> Any:
    for key in keys:
        if isinstance(data, dict):
            data = data.get(key, default)
        else:
            return default
    return data


def load_config(path: Path | None = None) -> ServerConfig:
    """Load configuration from a TOML file, falling back to defaults."""
    cfg = ServerConfig()

    if path is None:
        path = default_config_path()

    if path.exists():
        with open(path, "rb") as f:
            data = tomllib.load(f)

        server = data.get("server", {})
        cfg.role = Role.validate(server.get("role", cfg.role))
        cfg.schema_name = server.get("schema", cfg.schema_name)
        cfg.schema_path = server.get("schema_path", cfg.schema_path)
        cfg.task_binary = server.get("task_binary", cfg.task_binary)
        cfg.timew_binary = server.get("timew_binary", cfg.timew_binary)

        # Initialisation flags
        cfg.explicit_role_configured = "role" in server
        cfg.explicit_schema_configured = "schema" in server or "schema_path" in server
        cfg.explicit_taxonomy_configured = "taxonomy_path" in server
        cfg.taxonomy_path = server.get("taxonomy_path", cfg.taxonomy_path)

        # Security settings
        security = data.get("security", {})
        cfg.rate_limit_per_minute = security.get("rate_limit_per_minute", cfg.rate_limit_per_minute)
        cfg.rate_limit_per_hour = security.get("rate_limit_per_hour", cfg.rate_limit_per_hour)
        cfg.create_limit_per_hour = security.get("create_limit_per_hour", cfg.create_limit_per_hour)
        cfg.require_confirmation = security.get("require_confirmation", cfg.require_confirmation)
        cfg.dry_run_default = security.get("dry_run_default", cfg.dry_run_default)
        cfg.redacted_fields = security.get("redacted_fields", cfg.redacted_fields)
        cfg.taskwarrior_override_rc = server.get("taskrc", cfg.taskwarrior_override_rc)

        # Logging settings
        logging_section = data.get("logging", {})
        cfg.audit_log_path = logging_section.get("audit_log", cfg.audit_log_path)

    if not cfg.audit_log_path:
        cfg.audit_log_path = str(default_audit_log_path())

    return cfg
