# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25

"""First-run schema initialisation wizard (IDEA-003).

Invoked via ``./dev.sh init`` or ``python -m taskchampion_mcp.init_schema``.
Analyses existing Taskwarrior tasks, optionally parses a taxonomy file,
generates a TOML schema, saves it, and updates ``config.toml``.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib  # type: ignore[no-redef]

from taskchampion_mcp.schema_gen import (
    generate_schema_from_tasks_and_taxonomy,
    save_generated_schema,
)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_XDG_CONFIG = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
_CONFIG_DIR = _XDG_CONFIG / "taskchampion-mcp"
_CONFIG_FILE = _CONFIG_DIR / "config.toml"
_DEFAULT_SCHEMA_OUT = _CONFIG_DIR / "generated_schema.toml"


# ---------------------------------------------------------------------------
# Colours (optional, graceful fallback)
# ---------------------------------------------------------------------------

_CYAN = "\033[0;36m"
_GREEN = "\033[0;32m"
_YELLOW = "\033[1;33m"
_RED = "\033[0;31m"
_NC = "\033[0m"


def _info(msg: str) -> None:
    print(f"{_CYAN}[INFO]{_NC}  {msg}")


def _ok(msg: str) -> None:
    print(f"{_GREEN}[OK]{_NC}    {msg}")


def _warn(msg: str) -> None:
    print(f"{_YELLOW}[WARN]{_NC}  {msg}")


def _fail(msg: str) -> None:
    print(f"{_RED}[FAIL]{_NC}  {msg}")


# ---------------------------------------------------------------------------
# Task export
# ---------------------------------------------------------------------------


def _export_tasks(binary: str = "task") -> list[dict]:
    """Export all tasks via ``task export``."""
    try:
        proc = subprocess.run(
            [binary, "rc.verbose:nothing", "rc.confirmation:off", "export"],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if proc.returncode == 0 and proc.stdout.strip():
            return json.loads(proc.stdout)
    except (FileNotFoundError, subprocess.TimeoutExpired, json.JSONDecodeError) as exc:
        _warn(f"Could not export tasks: {exc}")
    return []


# ---------------------------------------------------------------------------
# Config helpers
# ---------------------------------------------------------------------------


def _read_config() -> dict:
    """Read existing config.toml or return empty dict."""
    if _CONFIG_FILE.exists():
        with open(_CONFIG_FILE, "rb") as f:
            return tomllib.load(f)
    return {}


def _write_config(data: dict) -> None:
    """Write config.toml preserving structure.

    Writes only the ``[server]`` section keys we care about,
    merging with existing content.
    """
    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    # Read existing raw lines to preserve comments and formatting
    existing_lines: list[str] = []
    if _CONFIG_FILE.exists():
        existing_lines = _CONFIG_FILE.read_text().splitlines()

    server = data.get("server", {})

    # Check if schema_path is already in the file
    has_schema_path = any("schema_path" in line for line in existing_lines)
    has_taxonomy_path = any("taxonomy_path" in line for line in existing_lines)

    new_lines: list[str] = []
    in_server = False
    for line in existing_lines:
        stripped = line.strip()
        if stripped == "[server]":
            in_server = True
        elif stripped.startswith("[") and stripped != "[server]":
            # Entering a new section — if we were in [server], append our keys
            if in_server:
                if not has_schema_path and "schema_path" in server:
                    new_lines.append(f'schema_path = "{server["schema_path"]}"')
                if not has_taxonomy_path and "taxonomy_path" in server:
                    new_lines.append(f'taxonomy_path = "{server["taxonomy_path"]}"')
            in_server = False

        # Update existing keys
        if in_server and stripped.startswith("schema_path"):
            if "schema_path" in server:
                new_lines.append(f'schema_path = "{server["schema_path"]}"')
                has_schema_path = True
                continue
        if in_server and stripped.startswith("taxonomy_path"):
            if "taxonomy_path" in server:
                new_lines.append(f'taxonomy_path = "{server["taxonomy_path"]}"')
                has_taxonomy_path = True
                continue
        # Skip commented schema= if we're setting schema_path
        if in_server and stripped.startswith("schema ") and "schema_path" in server:
            new_lines.append(f"# {stripped}  # overridden by schema_path")
            continue

        new_lines.append(line)

    # If we ended while still in [server], append keys
    if in_server:
        if not has_schema_path and "schema_path" in server:
            new_lines.append(f'schema_path = "{server["schema_path"]}"')
        if not has_taxonomy_path and "taxonomy_path" in server:
            new_lines.append(f'taxonomy_path = "{server["taxonomy_path"]}"')

    # If file was empty or had no [server] section, write a basic one
    if not existing_lines or not any(ln.strip() == "[server]" for ln in existing_lines):
        if not any(ln.strip() == "[server]" for ln in new_lines):
            new_lines.insert(0, "[server]")
        if "schema_path" in server:
            new_lines.append(f'schema_path = "{server["schema_path"]}"')
        if "taxonomy_path" in server:
            new_lines.append(f'taxonomy_path = "{server["taxonomy_path"]}"')

    _CONFIG_FILE.write_text("\n".join(new_lines) + "\n")


# ---------------------------------------------------------------------------
# Taxonomy detection
# ---------------------------------------------------------------------------


def _find_taxonomy(project_dir: str | None = None) -> Path | None:
    """Look for a taxonomy file in common locations."""
    candidates: list[Path] = []

    if project_dir:
        p = Path(project_dir)
        candidates += [
            p / "user" / "TAXONOMY.md",
            p / "TAXONOMY.md",
            p / "docs" / "TAXONOMY.md",
            p / "taxonomy.md",
        ]

    candidates += [
        _CONFIG_DIR / "TAXONOMY.md",
        _CONFIG_DIR / "taxonomy.md",
        Path.home() / "TAXONOMY.md",
    ]

    for c in candidates:
        if c.exists():
            return c.resolve()
    return None


# ---------------------------------------------------------------------------
# Main wizard
# ---------------------------------------------------------------------------


def run_init(
    project_dir: str | None = None,
    taxonomy_path: str | None = None,
    output_path: str | None = None,
    schema_name: str | None = None,
    non_interactive: bool = False,
) -> bool:
    """Run the first-time schema initialisation.

    Returns True if a schema was generated and config updated.
    """
    print()
    _info("TaskChampion MCP — First-Run Schema Initialisation")
    print()

    # 1. Check if a custom schema is already configured
    config = _read_config()
    existing_schema_path = config.get("server", {}).get("schema_path")
    if existing_schema_path and Path(existing_schema_path).exists():
        _warn(f"A custom schema is already configured: {existing_schema_path}")
        if not non_interactive:
            answer = input("  Overwrite? [y/N]: ").strip().lower()
            if answer != "y":
                _info("Keeping existing schema. Nothing to do.")
                return False
        else:
            _info("Non-interactive mode: skipping (schema already configured).")
            return False

    # 2. Export existing tasks
    task_binary = config.get("server", {}).get("task_binary", "task")
    _info(f"Exporting existing tasks via '{task_binary} export'...")
    tasks = _export_tasks(task_binary)

    if tasks:
        _ok(f"Found {len(tasks)} tasks.")
    else:
        _warn("No existing tasks found. Schema will be based on taxonomy only.")

    # 3. Find or prompt for taxonomy file
    resolved_taxonomy: Path | None = None

    if taxonomy_path:
        resolved_taxonomy = Path(taxonomy_path).resolve()
        if not resolved_taxonomy.exists():
            _fail(f"Taxonomy file not found: {resolved_taxonomy}")
            return False
    else:
        detected = _find_taxonomy(project_dir)
        if detected:
            _ok(f"Detected taxonomy file: {detected}")
            if not non_interactive:
                answer = input("  Use this file? [Y/n]: ").strip().lower()
                if answer == "n":
                    alt = input("  Enter path to taxonomy file (or Enter to skip): ").strip()
                    if alt:
                        resolved_taxonomy = Path(alt).resolve()
                        if not resolved_taxonomy.exists():
                            _warn(f"File not found: {resolved_taxonomy}. Skipping taxonomy.")
                            resolved_taxonomy = None
                    else:
                        resolved_taxonomy = None
                else:
                    resolved_taxonomy = detected
            else:
                resolved_taxonomy = detected
        else:
            _warn("No taxonomy file detected.")
            if not non_interactive:
                alt = input("  Enter path to taxonomy file (or Enter to skip): ").strip()
                if alt:
                    resolved_taxonomy = Path(alt).resolve()
                    if not resolved_taxonomy.exists():
                        _warn(f"File not found: {resolved_taxonomy}. Skipping taxonomy.")
                        resolved_taxonomy = None

    if resolved_taxonomy:
        _info(f"Using taxonomy: {resolved_taxonomy}")
    else:
        _info("Proceeding without taxonomy file.")

    if not tasks and not resolved_taxonomy:
        _warn("No tasks and no taxonomy file. Cannot generate a schema.")
        _info('Configure a preset schema in config.toml instead (e.g. schema = "minimal").')
        return False

    # 4. Generate schema
    if schema_name:
        name = schema_name
    elif resolved_taxonomy:
        name = "auto_generated_from_taxonomy"
    else:
        name = "auto_generated_from_tasks"
    _info("Generating schema...")
    toml_content = generate_schema_from_tasks_and_taxonomy(
        tasks=tasks,
        taxonomy_path=str(resolved_taxonomy) if resolved_taxonomy else None,
        name=name,
        description=f"Auto-generated from {len(tasks)} tasks"
        + (f" + {resolved_taxonomy.name}" if resolved_taxonomy else ""),
    )

    # 5. Save schema
    out = Path(output_path) if output_path else _DEFAULT_SCHEMA_OUT
    if out.exists():
        if not non_interactive:
            answer = input(f"  Schema file exists: {out}\n  Overwrite? [y/N]: ").strip().lower()
            if answer != "y":
                _info("Aborted. Existing schema kept.")
                return False
        # Remove so save_generated_schema doesn't error
        out.unlink()

    save_generated_schema(toml_content, out)
    _ok(f"Schema saved to: {out}")

    # 6. Update config.toml
    update = {"server": {"schema_path": str(out)}}
    if resolved_taxonomy:
        update["server"]["taxonomy_path"] = str(resolved_taxonomy)
    _write_config(update)
    _ok(f"Config updated: {_CONFIG_FILE}")

    # 7. Summary
    print()
    _ok("Initialisation complete!")
    print(f"  Schema:   {out}")
    if resolved_taxonomy:
        print(f"  Taxonomy: {resolved_taxonomy}")
    print(f"  Config:   {_CONFIG_FILE}")
    print()
    _info("Restart your MCP server to use the new schema.")
    return True


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description="TaskChampion MCP — First-run schema initialisation",
    )
    parser.add_argument(
        "--project-dir",
        default=None,
        help="Project directory to search for taxonomy files",
    )
    parser.add_argument(
        "--taxonomy",
        default=None,
        help="Path to taxonomy markdown file",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output path for the generated schema TOML",
    )
    parser.add_argument(
        "--name",
        default=None,
        help="Schema name (default: auto_generated)",
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="Run without prompts (use defaults)",
    )
    args = parser.parse_args()

    success = run_init(
        project_dir=args.project_dir,
        taxonomy_path=args.taxonomy,
        output_path=args.output,
        schema_name=args.name,
        non_interactive=args.non_interactive,
    )
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
