# Generated by: GPT-5.5 Thinking via ChatGPT
# Reviewed by: gabiup2
# Date: 2026-05-25

"""Runtime first-run onboarding for TaskChampion MCP.

This module is the **single source of truth** for first-run logic.  Both
surfaces — the CLI wizard (``taskchampion_mcp.init_schema``) and the runtime
MCP tools registered in :mod:`taskchampion_mcp.server` — call into the
functions defined here.  The CLI is a thin interactive layer; the MCP tools
are thin JSON adapters.

Design constraints:

1. Analysis and preview functions never mutate filesystem state.
2. The only functions that write to disk are :func:`save_initial_schema` and
   :func:`use_preset_schema`; both are explicit, idempotency-aware, and
   refuse to overwrite without ``overwrite=True``.
3. Default schema names are source-aware so that the resulting TOML
   immediately tells the operator where the schema came from
   (``auto_generated_from_taxonomy``, ``auto_generated_from_tasks``,
   ``auto_generated_from_taxonomy_and_tasks``, or ``preset_<name>``).
4. There is exactly one implementation of taxonomy detection and exactly
   one implementation of ``config.toml`` upsert.  Both are exported so the
   CLI wizard can reuse them.

Onboarding flow (user-facing summary):

1. :func:`get_initialization_status` — read-only status (exposed as `get_initialization_status`).
2. :func:`propose_initialization_options` — present choices to the user
   (exposed as `propose_initialization_options`).
3. Branch on the chosen option:
   - ``use_taxonomy`` / ``infer_from_tasks`` / ``hybrid_taxonomy_plus_tasks``:
     call :func:`generate_schema_preview`, review the TOML, then call
     :func:`save_initial_schema`.
   - ``use_builtin_preset``: call :func:`list_preset_schemas`, pick one,
     then call :func:`use_preset_schema`.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

from taskchampion_mcp.cli import TaskwarriorCLI, TimewarriorCLI
from taskchampion_mcp.config import Role, ServerConfig, default_config_path, default_schema_dir
from taskchampion_mcp.schema_gen import (
    TaxonomyInfo,
    analyze_tasks,
    generate_schema_from_tasks_and_taxonomy,
    parse_taxonomy,
    save_generated_schema,
)

# ---------------------------------------------------------------------------
# Constants and small helpers
# ---------------------------------------------------------------------------

_DEFAULT_SCHEMA_NAME_GENERIC = "auto_generated"
_DEFAULT_SCHEMA_FILE = "generated_schema.toml"


def _config_dir() -> Path:
    return default_config_path().parent


def _default_schema_path() -> Path:
    return _config_dir() / _DEFAULT_SCHEMA_FILE


def default_schema_name_for_source(
    has_taxonomy: bool,
    has_tasks: bool,
) -> str:
    """Return a source-aware default schema name.

    Centralised so the CLI wizard and the runtime preview tool agree.
    """
    if has_taxonomy and has_tasks:
        return "auto_generated_from_taxonomy_and_tasks"
    if has_taxonomy:
        return "auto_generated_from_taxonomy"
    if has_tasks:
        return "auto_generated_from_tasks"
    return _DEFAULT_SCHEMA_NAME_GENERIC


# ---------------------------------------------------------------------------
# Taxonomy detection / resolution (single implementation)
# ---------------------------------------------------------------------------


def _candidate_taxonomy_paths(project_dir: str | None = None) -> list[Path]:
    """Return likely taxonomy locations, ordered from project-local to user-global."""
    candidates: list[Path] = []

    if project_dir:
        root = Path(project_dir).expanduser()
        candidates.extend(
            [
                root / "user" / "TAXONOMY.md",
                root / "TAXONOMY.md",
                root / "docs" / "TAXONOMY.md",
                root / "taxonomy.md",
            ]
        )

    cwd = Path.cwd()
    candidates.extend(
        [
            cwd / "user" / "TAXONOMY.md",
            cwd / "TAXONOMY.md",
            cwd / "docs" / "TAXONOMY.md",
            cwd / "taxonomy.md",
            _config_dir() / "TAXONOMY.md",
            _config_dir() / "taxonomy.md",
            Path.home() / "TAXONOMY.md",
        ]
    )

    seen: set[Path] = set()
    unique: list[Path] = []
    for path in candidates:
        expanded = path.expanduser()
        if expanded not in seen:
            seen.add(expanded)
            unique.append(expanded)
    return unique


def detect_taxonomy_files(project_dir: str | None = None) -> list[str]:
    """Find taxonomy files in common locations."""
    return [str(path.resolve()) for path in _candidate_taxonomy_paths(project_dir) if path.exists()]


def resolve_taxonomy_path(
    config: ServerConfig,
    taxonomy_path: str | None = None,
    project_dir: str | None = None,
) -> Path | None:
    """Resolve an explicit, configured, or auto-detected taxonomy path.

    Returns None if the resolved path does not exist.
    """
    if taxonomy_path:
        path = Path(taxonomy_path).expanduser().resolve()
        return path if path.exists() else None
    if config.taxonomy_path:
        path = Path(config.taxonomy_path).expanduser().resolve()
        return path if path.exists() else None
    detected = detect_taxonomy_files(project_dir)
    return Path(detected[0]) if detected else None


# ---------------------------------------------------------------------------
# Task export wrappers
# ---------------------------------------------------------------------------


def _safe_export_tasks(task_cli: TaskwarriorCLI) -> tuple[list[dict[str, Any]], str | None]:
    try:
        return task_cli.export_tasks(), None
    except Exception as exc:  # noqa: BLE001 - diagnostics are returned to caller
        return [], str(exc)


def _safe_task_count(task_cli: TaskwarriorCLI) -> tuple[int, str | None]:
    tasks, error = _safe_export_tasks(task_cli)
    return len(tasks), error


# ---------------------------------------------------------------------------
# Status / options
# ---------------------------------------------------------------------------


def get_initialization_status(
    config: ServerConfig,
    task_cli: TaskwarriorCLI,
    timew_cli: TimewarriorCLI | None = None,
    project_dir: str | None = None,
) -> dict[str, Any]:
    """Return runtime onboarding status for the connected model.

    ``initialised`` means user-specific semantics are available, not merely
    that the server managed to load the bundled minimal schema.
    """
    cfg_path = default_config_path()
    schema_path = Path(config.schema_path).expanduser() if config.schema_path else None
    taxonomy_path = Path(config.taxonomy_path).expanduser() if config.taxonomy_path else None
    detected_taxonomies = detect_taxonomy_files(project_dir)
    task_count, task_export_error = _safe_task_count(task_cli)

    custom_schema_configured = bool(schema_path)
    custom_schema_exists = bool(schema_path and schema_path.exists())
    taxonomy_configured = bool(taxonomy_path)
    taxonomy_exists = bool(taxonomy_path and taxonomy_path.exists())
    taxonomy_available = taxonomy_exists or bool(detected_taxonomies)

    initialised = custom_schema_exists or taxonomy_exists
    needs_onboarding = not initialised

    recommended_next_action = "none"
    if needs_onboarding:
        if taxonomy_available:
            recommended_next_action = "use_detected_taxonomy"
        elif task_count > 0:
            recommended_next_action = "infer_schema_from_existing_tasks"
        else:
            recommended_next_action = "ask_user_for_taxonomy_or_select_preset"

    role_configured = bool(config.explicit_role_configured)
    needs_role_selection = not role_configured

    return {
        "initialised": initialised,
        "needs_onboarding": needs_onboarding,
        "recommended_next_action": recommended_next_action,
        "config_file": str(cfg_path),
        "config_file_exists": cfg_path.exists(),
        "active_schema_name": config.schema_name,
        "custom_schema_configured": custom_schema_configured,
        "custom_schema_path": str(schema_path) if schema_path else None,
        "custom_schema_exists": custom_schema_exists,
        "taxonomy_configured": taxonomy_configured,
        "taxonomy_path": str(taxonomy_path) if taxonomy_path else None,
        "taxonomy_exists": taxonomy_exists,
        "detected_taxonomy_paths": detected_taxonomies,
        "task_export_available": task_export_error is None,
        "task_export_error": task_export_error,
        "task_count": task_count,
        "timewarrior_available": bool(timew_cli and timew_cli.available()),
        "safe_to_mutate_tasks": False,
        "available_presets": [preset["name"] for preset in _list_presets_raw()],
        # Role configuration is a separate axis: the server stays in onboarding
        # mode whenever either schema *or* role is missing from config.toml.
        "active_role": config.role,
        "role_configured": role_configured,
        "needs_role_selection": needs_role_selection,
        "available_roles": list(Role._HIERARCHY),
        "message_for_model": _status_message(
            needs_onboarding,
            task_count,
            taxonomy_available,
            needs_role_selection=needs_role_selection,
        ),
    }


def _status_message(
    needs_onboarding: bool,
    task_count: int,
    taxonomy_available: bool,
    needs_role_selection: bool = False,
) -> str:
    role_suffix = (
        "  No explicit role is set in config.toml; the server is using a "
        "fallback CONTRIBUTOR role. Ask the user which role to persist "
        "(CONTRIBUTOR / GENERATOR / MANAGER) and pass it to save_initial_schema "
        "or use_preset_schema so the next restart exits onboarding mode."
        if needs_role_selection
        else ""
    )

    if not needs_onboarding:
        base = (
            "User-specific task semantics are configured. "
            "Read schema/taxonomy before modifying tasks."
        )
        return base + role_suffix
    if taxonomy_available:
        base = (
            "No active custom schema is configured, but a taxonomy file is available. "
            "Ask the user whether to use it to generate a reviewed schema."
        )
        return base + role_suffix
    if task_count > 0:
        base = (
            "No taxonomy/schema is configured. Ask the user for a taxonomy file, "
            "offer to infer a draft schema from existing tasks, or select a bundled preset."
        )
        return base + role_suffix
    base = (
        "No taxonomy/schema and no existing tasks are available. Ask the user to provide "
        "a taxonomy file or select a bundled preset via use_preset_schema."
    )
    return base + role_suffix


_ROLE_DESCRIPTIONS: dict[str, str] = {
    Role.CONTRIBUTOR: (
        "Read, annotate, and modify existing tasks. Cannot create or delete "
        "tasks. Safe default for most users."
    ),
    Role.GENERATOR: (
        "Everything CONTRIBUTOR can do, plus create new tasks and tags. "
        "Pick this when the model should actively populate the backlog."
    ),
    Role.MANAGER: (
        "Full lifecycle: everything GENERATOR can do, plus delete/undo and "
        "destructive cleanup. Highest trust level — pick deliberately."
    ),
}


def _role_choice_block(status: dict[str, Any]) -> dict[str, Any]:
    """Self-describing role block for the calling model.

    Surfaces whether a role is already persisted, the recommended default, and
    the full list of valid roles with short descriptions, so the model can
    present a role picker without further introspection.
    """
    role_configured = bool(status.get("role_configured"))
    active_role = status.get("active_role") or Role.CONTRIBUTOR
    return {
        "id": "select_role",
        "label": "Select MCP role (permission level)",
        "required_for_completion": True,
        "currently_configured": role_configured,
        "active_role": active_role,
        "recommended_role": Role.CONTRIBUTOR,
        "next_tools": ["save_initial_schema", "use_preset_schema"],
        "available_roles": [
            {"name": name, "description": _ROLE_DESCRIPTIONS[name]}
            for name in Role._HIERARCHY
        ],
        "description": (
            "Role gates which tools the server registers after restart. "
            "Pass the chosen role to save_initial_schema / use_preset_schema "
            "so it is persisted in config.toml. Without an explicit role the "
            "server stays in onboarding mode."
        ),
    }


def propose_initialization_options(status: dict[str, Any]) -> dict[str, Any]:
    """Build user-facing onboarding options from ``get_initialization_status``.

    Each option is self-describing so the calling LLM can present a clean
    menu to the user without further introspection.

    The returned payload includes a ``roles`` block alongside ``options``
    because role selection is orthogonal to schema selection: both must be
    persisted for the server to leave onboarding mode on next restart.
    """
    task_count = int(status.get("task_count") or 0)
    has_taxonomy = bool(status.get("taxonomy_exists") or status.get("detected_taxonomy_paths"))
    preset_names = status.get("available_presets") or [p["name"] for p in _list_presets_raw()]

    return {
        "needs_onboarding": bool(status.get("needs_onboarding")),
        "needs_role_selection": bool(status.get("needs_role_selection")),
        "recommended_next_action": status.get("recommended_next_action"),
        "roles": _role_choice_block(status),
        "options": [
            {
                "id": "use_taxonomy",
                "label": "Use a taxonomy Markdown file",
                "recommended": has_taxonomy,
                "requires_user_input": not has_taxonomy,
                "next_tools": [
                    "analyze_taxonomy_file",
                    "generate_initial_schema_preview",
                    "save_initial_schema",
                ],
                "description": (
                    "Best option when the user has documented field meanings, lifecycle phases, "
                    "conditional requirements, project naming, and task flow."
                ),
            },
            {
                "id": "infer_from_tasks",
                "label": "Infer a draft schema from existing tasks",
                "recommended": not has_taxonomy and task_count > 0,
                "requires_user_input": False,
                "next_tools": [
                    "analyze_existing_tasks_for_schema",
                    "generate_initial_schema_preview",
                    "save_initial_schema",
                ],
                "description": (
                    "Useful fallback when no taxonomy exists. It detects fields, "
                    "value distributions, likely enums, and likely required fields, "
                    "but the result must be reviewed."
                ),
            },
            {
                "id": "hybrid_taxonomy_plus_tasks",
                "label": "Use taxonomy plus existing tasks",
                "recommended": has_taxonomy and task_count > 0,
                "requires_user_input": False,
                "next_tools": [
                    "analyze_taxonomy_file",
                    "analyze_existing_tasks_for_schema",
                    "generate_initial_schema_preview",
                    "save_initial_schema",
                ],
                "description": (
                    "Strongest option: taxonomy supplies semantics, "
                    "existing tasks supply empirical checks."
                ),
            },
            {
                "id": "use_builtin_preset",
                "label": "Use a bundled preset schema",
                "recommended": not has_taxonomy and task_count == 0,
                "requires_user_input": True,
                "next_tools": ["list_preset_schemas", "use_preset_schema"],
                "available_presets": preset_names,
                "description": (
                    "Lowest-friction fallback. Available presets: "
                    + ", ".join(preset_names)
                    + ". Pick one and call use_preset_schema."
                ),
            },
        ],
    }


# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------


def analyze_existing_tasks(task_cli: TaskwarriorCLI) -> dict[str, Any]:
    """Analyse existing tasks and return field/value statistics for schema design."""
    tasks, error = _safe_export_tasks(task_cli)
    if error:
        return {"error": True, "message": f"Could not export tasks: {error}", "task_count": 0}

    analysis = analyze_tasks(tasks)
    fields: dict[str, Any] = {}
    for name, field in sorted(analysis.fields.items()):
        fields[name] = {
            "occurrence_count": field.occurrence_count,
            "usage_ratio": round(field.usage_ratio, 4),
            "is_uda": field.is_uda,
            "inferred_type": field.inferred_type,
            "inferred_required": field.inferred_required,
            "inferred_values": field.inferred_values,
            "sample_values": field.sample_values,
        }

    return {
        "success": True,
        "task_count": analysis.total_tasks,
        "fields": fields,
        "uda_fields": sorted(analysis.uda_fields().keys()),
        "builtin_fields": sorted(analysis.builtin_fields().keys()),
        "projects": analysis.projects,
        "tags": analysis.tags,
    }


def analyze_taxonomy_file(path: str) -> dict[str, Any]:
    """Parse a taxonomy Markdown file and return extracted semantics."""
    taxonomy_path = Path(path).expanduser().resolve()
    if not taxonomy_path.exists():
        return {"error": True, "message": f"Taxonomy file not found: {taxonomy_path}"}

    taxonomy = parse_taxonomy(taxonomy_path)
    return _taxonomy_summary(taxonomy, taxonomy_path)


def _taxonomy_summary(taxonomy: TaxonomyInfo, taxonomy_path: Path) -> dict[str, Any]:
    return {
        "success": True,
        "taxonomy_path": str(taxonomy_path),
        "field_count": len(taxonomy.fields),
        "condition_count": len(taxonomy.conditions),
        "phase_transition_count": len(taxonomy.phase_transitions),
        "fields": {
            name: {
                "description": field.description,
                "allowed_values": field.allowed_values,
                "type": field.type,
                "required": field.required,
                "uda": field.uda,
                "conditions": field.conditions,
            }
            for name, field in sorted(taxonomy.fields.items())
        },
        "conditions": [
            {
                "name": cond.name,
                "when": cond.when,
                "then_required": cond.then_required,
                "description": cond.description,
            }
            for cond in taxonomy.conditions
        ],
        "phase_transitions": [
            {
                "from_phase": transition.from_phase,
                "to_phase": transition.to_phase,
                "add_fields": transition.add_fields,
                "description": transition.description,
            }
            for transition in taxonomy.phase_transitions
        ],
    }


# ---------------------------------------------------------------------------
# Preview + save (generated schema path)
# ---------------------------------------------------------------------------


def _build_preview_payload(
    *,
    schema_toml: str,
    schema_name: str,
    tasks: list[dict[str, Any]],
    task_error: str | None,
    resolved_taxonomy: Path | None,
) -> dict[str, Any]:
    analysis = analyze_tasks(tasks) if tasks else None
    taxonomy = parse_taxonomy(resolved_taxonomy) if resolved_taxonomy else None

    return {
        "success": True,
        "mutated": False,
        "schema_name": schema_name,
        "task_count": len(tasks),
        "task_export_error": task_error,
        "taxonomy_path": str(resolved_taxonomy) if resolved_taxonomy else None,
        "summary": {
            "fields_from_tasks": sorted(analysis.fields.keys()) if analysis else [],
            "uda_fields_from_tasks": sorted(analysis.uda_fields().keys()) if analysis else [],
            "fields_from_taxonomy": sorted(taxonomy.fields.keys()) if taxonomy else [],
            "conditions_from_taxonomy": len(taxonomy.conditions) if taxonomy else 0,
            "phase_transitions_from_taxonomy": len(taxonomy.phase_transitions) if taxonomy else 0,
        },
        "schema_toml": schema_toml,
        "review_note": (
            "Review schema_toml before saving. Inferred enum/required fields are heuristics; "
            "taxonomy descriptions are treated as higher authority than raw task data."
        ),
    }


def generate_schema_preview(
    config: ServerConfig,
    task_cli: TaskwarriorCLI,
    taxonomy_path: str | None = None,
    project_dir: str | None = None,
    schema_name: str | None = None,
) -> dict[str, Any]:
    """Generate a non-mutating schema preview from tasks, taxonomy, or both.

    If ``schema_name`` is empty/None, a source-aware default is chosen via
    :func:`default_schema_name_for_source`.
    """
    tasks, task_error = _safe_export_tasks(task_cli)
    resolved_taxonomy = resolve_taxonomy_path(config, taxonomy_path, project_dir)

    if resolved_taxonomy and not resolved_taxonomy.exists():
        return {"error": True, "message": f"Taxonomy file not found: {resolved_taxonomy}"}

    if not tasks and not resolved_taxonomy:
        return {
            "error": True,
            "message": "Cannot generate schema preview: no exported tasks and no taxonomy file.",
            "task_export_error": task_error,
        }

    effective_name = (
        schema_name
        if schema_name
        else default_schema_name_for_source(
            has_taxonomy=resolved_taxonomy is not None,
            has_tasks=bool(tasks),
        )
    )

    description = f"Auto-generated from {len(tasks)} tasks"
    if resolved_taxonomy:
        description += f" + {resolved_taxonomy.name}"

    toml_content = generate_schema_from_tasks_and_taxonomy(
        tasks=tasks,
        taxonomy_path=str(resolved_taxonomy) if resolved_taxonomy else None,
        name=effective_name,
        description=description,
    )

    return _build_preview_payload(
        schema_toml=toml_content,
        schema_name=effective_name,
        tasks=tasks,
        task_error=task_error,
        resolved_taxonomy=resolved_taxonomy,
    )


def save_initial_schema(
    schema_toml: str,
    taxonomy_path: str | None = None,
    output_path: str | None = None,
    role: str | None = None,
    overwrite: bool = False,
    update_config: bool = True,
) -> dict[str, Any]:
    """Persist an approved generated schema and optionally update ``config.toml``.

    ``role`` is validated against :class:`Role`.  When ``update_config`` is
    True and no ``role`` is provided, the persisted config defaults to
    ``CONTRIBUTOR`` so that ``ServerConfig.explicit_role_configured`` becomes
    True on the next load and the server leaves onboarding mode.  Pass an
    explicit role (e.g. ``"GENERATOR"`` or ``"MANAGER"``) to grant a higher
    permission level.
    """
    if not schema_toml.strip():
        return {
            "error": True,
            "message": "schema_toml is empty; generate and review a preview first.",
        }

    effective_role: str | None = None
    if update_config:
        candidate = role if role else Role.CONTRIBUTOR
        try:
            effective_role = Role.validate(candidate)
        except ValueError as exc:
            return {"error": True, "message": str(exc)}

    out = Path(output_path).expanduser() if output_path else _default_schema_path()
    if out.exists():
        if not overwrite:
            return {
                "error": True,
                "message": f"Schema file already exists: {out}. Pass overwrite=true to replace it.",
            }
        # Handle race condition: file might be created between check and unlink
        try:
            out.unlink()
        except FileNotFoundError:
            # File was deleted by another process, proceed with save
            pass

    saved_path = save_generated_schema(schema_toml, out)

    cfg_path: Path | None = None
    if update_config:
        cfg_path = upsert_server_config(
            schema_path=str(saved_path),
            taxonomy_path=str(Path(taxonomy_path).expanduser().resolve())
            if taxonomy_path
            else None,
            role=effective_role,
        )

    return {
        "success": True,
        "schema_path": str(saved_path),
        "config_updated": update_config,
        "config_file": str(cfg_path) if cfg_path else None,
        "role": effective_role,
        "message": "Initial schema saved. Restart the MCP server to load it.",
    }


# ---------------------------------------------------------------------------
# Bundled preset support
# ---------------------------------------------------------------------------


def _list_presets_raw() -> list[dict[str, str]]:
    """Return raw preset metadata (name + absolute path).

    Used internally so the slightly more decorated public functions can build
    on a single source of truth.  Returns [] if the bundled directory is
    missing (e.g. unusual install layout) rather than raising.
    """
    schema_dir = default_schema_dir()
    if not schema_dir.exists():
        return []

    presets: list[dict[str, str]] = []
    for path in sorted(schema_dir.glob("*.toml")):
        presets.append({"name": path.stem, "path": str(path.resolve())})
    return presets


def list_preset_schemas() -> dict[str, Any]:
    """List bundled preset schemas with a short description for each.

    Reads the ``[meta]`` block of each preset so the description shown to the
    user is taken directly from the schema file rather than duplicated here.
    """
    raw_presets = _list_presets_raw()
    presets: list[dict[str, Any]] = []

    for preset in raw_presets:
        meta = _read_preset_meta(Path(preset["path"]))
        presets.append(
            {
                "name": preset["name"],
                "path": preset["path"],
                "description": meta.get("description", ""),
                "version": meta.get("version", ""),
                "schema_name": meta.get("name", preset["name"]),
            }
        )

    return {
        "success": True,
        "schema_dir": str(default_schema_dir()),
        "preset_count": len(presets),
        "presets": presets,
    }


def _read_preset_meta(path: Path) -> dict[str, str]:
    """Parse only the ``[meta]`` table of a preset schema.

    Tolerant: returns an empty dict on any parse error so listing never
    fails because one file is malformed.
    """
    try:
        import sys

        if sys.version_info >= (3, 11):
            import tomllib
        else:
            import tomli as tomllib  # type: ignore[no-redef]
        with open(path, "rb") as f:
            data = tomllib.load(f)
        meta = data.get("meta", {})
        return {k: str(v) for k, v in meta.items() if isinstance(v, (str, int, float))}
    except Exception:  # noqa: BLE001
        return {}


def use_preset_schema(
    preset_name: str,
    taxonomy_path: str | None = None,
    output_path: str | None = None,
    role: str | None = None,
    copy: bool = False,
    overwrite: bool = False,
    update_config: bool = True,
) -> dict[str, Any]:
    """Wire a bundled preset into the user's ``config.toml``.

    By default this writes ``[server].schema = <preset_name>`` and clears any
    previous ``schema_path`` override.  This is the simplest, most stable
    integration: the user keeps using the bundled, version-controlled preset
    file.

    Set ``copy=True`` to instead copy the preset into ``output_path`` (or the
    default user config dir) and point ``schema_path`` at the copy.  Use this
    when the user wants a personal copy they can edit without touching the
    package install.

    Refuses to overwrite an existing target file when ``copy=True`` unless
    ``overwrite=True``.

    ``role`` is validated against :class:`Role`.  When ``update_config`` is
    True and no ``role`` is provided, the persisted config defaults to
    ``CONTRIBUTOR`` so that ``ServerConfig.explicit_role_configured`` becomes
    True on the next load and the server leaves onboarding mode.
    """
    raw_presets = _list_presets_raw()
    by_name = {p["name"]: p for p in raw_presets}
    if preset_name not in by_name:
        return {
            "error": True,
            "message": (
                f"Unknown preset '{preset_name}'. Available: " + ", ".join(sorted(by_name.keys()))
            ),
            "available_presets": sorted(by_name.keys()),
        }

    effective_role: str | None = None
    if update_config:
        candidate = role if role else Role.CONTRIBUTOR
        try:
            effective_role = Role.validate(candidate)
        except ValueError as exc:
            return {"error": True, "message": str(exc)}

    preset_path = Path(by_name[preset_name]["path"])

    saved_path: Path | None = None
    if copy:
        target = Path(output_path).expanduser() if output_path else _config_dir() / preset_path.name
        if target.exists() and not overwrite:
            return {
                "error": True,
                "message": (
                    f"Target file already exists: {target}. Pass overwrite=true to replace it."
                ),
            }
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(preset_path, target)
        saved_path = target.resolve()

    cfg_path: Path | None = None
    if update_config:
        cfg_path = upsert_server_config(
            schema_path=str(saved_path) if saved_path else None,
            schema_name=preset_name if not saved_path else None,
            taxonomy_path=str(Path(taxonomy_path).expanduser().resolve())
            if taxonomy_path
            else None,
            role=effective_role,
            clear_schema_path=not saved_path,
        )

    return {
        "success": True,
        "preset_name": preset_name,
        "preset_path": str(preset_path.resolve()),
        "copied_to": str(saved_path) if saved_path else None,
        "config_updated": update_config,
        "config_file": str(cfg_path) if cfg_path else None,
        "role": effective_role,
        "message": (f"Preset '{preset_name}' selected. Restart the MCP server to load it."),
    }


# ---------------------------------------------------------------------------
# Config upsert (single implementation, reused by CLI and MCP)
# ---------------------------------------------------------------------------


def upsert_server_config(
    schema_path: str | None = None,
    schema_name: str | None = None,
    taxonomy_path: str | None = None,
    role: str | None = None,
    clear_schema_path: bool = False,
) -> Path:
    """Insert/update ``[server]`` keys in the user config file.

    Behaviour:

    - ``schema_path``:  if provided, set ``schema_path = "<value>"``.
    - ``schema_name``:  if provided, set ``schema = "<value>"`` (preset selection).
    - ``taxonomy_path``: if provided, set ``taxonomy_path = "<value>"``.
    - ``role``:         if provided, set ``role = "<value>"``. Validated against
      :class:`Role`. Persisting an explicit role is what flips
      ``ServerConfig.explicit_role_configured`` to ``True`` on next load, which
      is required for the server to leave onboarding mode.
    - ``clear_schema_path``: if True, comment out an existing ``schema_path``
      line.  Useful when switching from a generated schema back to a named
      preset.

    The function preserves comments and ordering as much as possible by
    operating on raw lines rather than re-emitting parsed TOML.  This is the
    single implementation; the CLI wizard calls into it.
    """
    validated_role: str | None = Role.validate(role) if role else None

    cfg_path = default_config_path()
    cfg_path.parent.mkdir(parents=True, exist_ok=True)

    lines = cfg_path.read_text(encoding="utf-8").splitlines() if cfg_path.exists() else []
    new_lines: list[str] = []
    in_server = False
    saw_server = False
    wrote_schema_path = False
    wrote_schema_name = False
    wrote_taxonomy = False
    wrote_role = False

    def append_missing_server_keys() -> None:
        nonlocal wrote_schema_path, wrote_schema_name, wrote_taxonomy, wrote_role
        # Role first so the file reads "role = ... ; schema = ..." top-down.
        if validated_role and not wrote_role:
            new_lines.append(f'role = "{validated_role}"')
            wrote_role = True
        if schema_path and not wrote_schema_path:
            new_lines.append(f'schema_path = "{schema_path}"')
            wrote_schema_path = True
        if schema_name and not wrote_schema_name:
            new_lines.append(f'schema = "{schema_name}"')
            wrote_schema_name = True
        if taxonomy_path and not wrote_taxonomy:
            new_lines.append(f'taxonomy_path = "{taxonomy_path}"')
            wrote_taxonomy = True

    for line in lines:
        stripped = line.strip()
        if stripped == "[server]":
            saw_server = True
            in_server = True
            new_lines.append(line)
            continue

        if stripped.startswith("[") and stripped != "[server]":
            if in_server:
                append_missing_server_keys()
            in_server = False
            new_lines.append(line)
            continue

        if in_server and (stripped.startswith("role ") or stripped.startswith("role=")):
            if validated_role:
                new_lines.append(f'role = "{validated_role}"')
                wrote_role = True
                continue
            new_lines.append(line)
            continue

        if in_server and stripped.startswith("schema_path"):
            if schema_path:
                new_lines.append(f'schema_path = "{schema_path}"')
                wrote_schema_path = True
                continue
            if clear_schema_path:
                new_lines.append(f"# {stripped}  # cleared by preset selection")
                continue
            # leave untouched
            new_lines.append(line)
            continue

        if in_server and (stripped.startswith("schema ") or stripped.startswith("schema=")):
            if schema_name:
                new_lines.append(f'schema = "{schema_name}"')
                wrote_schema_name = True
                continue
            if schema_path:
                # generated schema overrides named schema
                new_lines.append(f"# {stripped}  # overridden by schema_path")
                continue
            new_lines.append(line)
            continue

        if in_server and stripped.startswith("taxonomy_path"):
            if taxonomy_path:
                new_lines.append(f'taxonomy_path = "{taxonomy_path}"')
                wrote_taxonomy = True
                continue
            new_lines.append(line)
            continue

        new_lines.append(line)

    if not saw_server:
        if new_lines and new_lines[-1].strip():
            new_lines.append("")
        new_lines.append("[server]")
        in_server = True

    if in_server:
        append_missing_server_keys()

    cfg_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    return cfg_path


# ---------------------------------------------------------------------------
# Post-onboarding reconfiguration (ADR 17)
#
# These functions back the runtime reconfigure_* MCP tools registered at
# CONTRIBUTOR level in server.py.  They are intentionally one-way: schema /
# taxonomy mutation is allowed at any role, role downgrade is allowed, role
# upgrade via MCP is forbidden by design.  See ADR 17 for the threat model.
# ---------------------------------------------------------------------------


_ROLE_ELEVATION_FORBIDDEN_CODE = "role_elevation_forbidden"


def reconfigure_active_schema(
    schema_name: str | None = None,
    schema_path: str | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Switch the active schema by updating ``config.toml``.

    Exactly one of ``schema_name`` (a bundled preset) or ``schema_path``
    (a file path to a custom schema TOML) must be provided.

    When ``dry_run=True``: validate all inputs (preset name exists, schema
    file exists, etc.) and return a preview describing what *would* be
    written, but do not touch ``config.toml``.  Returns ``code="dry_run"``
    per ADR 14.

    Does not mutate Taskwarrior tasks.  Server restart required to apply
    (runtime reload is not yet implemented).
    """
    if not schema_name and not schema_path:
        return {
            "error": True,
            "message": "Provide exactly one of schema_name or schema_path.",
        }
    if schema_name and schema_path:
        return {
            "error": True,
            "message": (
                "Provide exactly one of schema_name or schema_path, not both. "
                "schema_path overrides schema_name when both are set in "
                "config.toml; pass only the one you intend to activate."
            ),
        }

    if schema_name:
        known = {p["name"] for p in _list_presets_raw()}
        if schema_name not in known:
            return {
                "error": True,
                "message": (
                    f"Unknown preset '{schema_name}'. "
                    f"Available: {sorted(known)}"
                ),
                "available_presets": sorted(known),
            }
        if dry_run:
            return {
                "success": True,
                "code": "dry_run",
                "schema_name": schema_name,
                "schema_path": None,
                "restart_required": True,
                "preview": {
                    "would_write": {"schema": schema_name},
                    "would_clear": "schema_path",
                },
                "message": (
                    f"DRY RUN: would set [server].schema = '{schema_name}' "
                    "and clear any existing schema_path. No file written."
                ),
            }
        cfg_path = upsert_server_config(
            schema_name=schema_name,
            clear_schema_path=True,
        )
        return {
            "success": True,
            "schema_name": schema_name,
            "schema_path": None,
            "config_file": str(cfg_path),
            "restart_required": True,
            "message": (
                f"Schema set to preset '{schema_name}'. "
                "Restart the MCP server to load it."
            ),
        }

    # schema_path branch
    resolved = Path(schema_path).expanduser().resolve()
    if not resolved.exists():
        return {
            "error": True,
            "message": f"Schema file not found: {resolved}",
        }
    if dry_run:
        return {
            "success": True,
            "code": "dry_run",
            "schema_name": None,
            "schema_path": str(resolved),
            "restart_required": True,
            "preview": {"would_write": {"schema_path": str(resolved)}},
            "message": (
                f"DRY RUN: would set [server].schema_path = '{resolved}'. "
                "No file written."
            ),
        }
    cfg_path = upsert_server_config(schema_path=str(resolved))
    return {
        "success": True,
        "schema_name": None,
        "schema_path": str(resolved),
        "config_file": str(cfg_path),
        "restart_required": True,
        "message": (
            f"Schema path set to {resolved}. Restart the MCP server to load it."
        ),
    }


def reconfigure_taxonomy_path(path: str, dry_run: bool = False) -> dict[str, Any]:
    """Update the ``taxonomy_path`` entry in ``config.toml``.

    Validates that the target file exists before persisting.  The taxonomy
    file influences how the model interprets task semantics; pointing it at
    a non-existent path would silently disable taxonomy awareness.

    When ``dry_run=True``: run all validation, return a preview, but do not
    write ``config.toml``.  Returns ``code="dry_run"`` per ADR 14.
    """
    if not path or not path.strip():
        return {"error": True, "message": "path must be a non-empty string."}

    resolved = Path(path).expanduser().resolve()
    if not resolved.exists():
        return {
            "error": True,
            "message": f"Taxonomy file not found: {resolved}",
        }
    if not resolved.is_file():
        return {
            "error": True,
            "message": f"Taxonomy path is not a regular file: {resolved}",
        }

    if dry_run:
        return {
            "success": True,
            "code": "dry_run",
            "taxonomy_path": str(resolved),
            "restart_required": True,
            "preview": {"would_write": {"taxonomy_path": str(resolved)}},
            "message": (
                f"DRY RUN: would set [server].taxonomy_path = '{resolved}'. "
                "No file written."
            ),
        }

    cfg_path = upsert_server_config(taxonomy_path=str(resolved))
    return {
        "success": True,
        "taxonomy_path": str(resolved),
        "config_file": str(cfg_path),
        "restart_required": True,
        "message": (
            f"Taxonomy path set to {resolved}. Restart the MCP server to "
            "load it."
        ),
    }


def reconfigure_role(
    current_role: str,
    target_role: str,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Change the persisted role — downgrade only.

    Refuses if ``level(target) > level(current)``.  Self-elevation via MCP
    is forbidden by design (ADR 17); the structured error includes the
    ``role_elevation_forbidden`` code so dashboards / SIEM queries can
    surface attempts.

    A no-op (target == current) succeeds and returns ``success=True`` so
    the tool is idempotent for clients that re-issue on transient failures.

    When ``dry_run=True``: run all validation (including the elevation
    refusal check) and return a preview, but do not write ``config.toml``.
    Returns ``code="dry_run"`` on success per ADR 14.  Refusal-class
    errors (role_elevation_forbidden) trigger regardless of dry_run — a
    forbidden elevation is forbidden whether or not the LLM was just
    "asking".
    """
    try:
        target = Role.validate(target_role)
    except ValueError as exc:
        return {"error": True, "message": str(exc)}

    try:
        current_validated = Role.validate(current_role)
    except ValueError as exc:
        return {
            "error": True,
            "message": f"Current role is invalid: {exc}",
        }

    if Role.level(target) > Role.level(current_validated):
        return {
            "error": True,
            "error_code": _ROLE_ELEVATION_FORBIDDEN_CODE,
            "current_role": current_validated,
            "requested_role": target,
            "message": (
                f"Self-elevation forbidden: cannot raise role from "
                f"{current_validated} to {target} via MCP (ADR 17). "
                "To elevate, run './dev.sh init --role <ROLE>' from a "
                "shell, or hand-edit ~/.config/taskchampion-mcp/config.toml "
                "and restart the MCP server."
            ),
        }

    if dry_run:
        return {
            "success": True,
            "code": "dry_run",
            "previous_role": current_validated,
            "new_role": target,
            "restart_required": True,
            "preview": {"would_write": {"role": target}},
            "message": (
                f"DRY RUN: would set [server].role = '{target}' "
                f"(downgrade from {current_validated}). No file written."
            ),
        }

    cfg_path = upsert_server_config(role=target)
    return {
        "success": True,
        "previous_role": current_validated,
        "new_role": target,
        "config_file": str(cfg_path),
        "restart_required": True,
        "message": (
            f"Role set to {target} (from {current_validated}). "
            "Restart the MCP server to apply."
        ),
    }


__all__ = [
    "analyze_existing_tasks",
    "analyze_taxonomy_file",
    "default_schema_name_for_source",
    "detect_taxonomy_files",
    "generate_schema_preview",
    "get_initialization_status",
    "list_preset_schemas",
    "propose_initialization_options",
    "reconfigure_active_schema",
    "reconfigure_role",
    "reconfigure_taxonomy_path",
    "resolve_taxonomy_path",
    "save_initial_schema",
    "upsert_server_config",
    "use_preset_schema",
    "_default_schema_path",
    "_ROLE_ELEVATION_FORBIDDEN_CODE",
]
