# Generated by: GPT-5.5 Thinking via ChatGPT
# Reviewed by: gabiup2
# Date: 2026-05-25

"""Runtime first-run onboarding for TaskChampion MCP.

The CLI wizard in :mod:`taskchampion_mcp.init_schema` is useful for humans
running ``./dev.sh init``.  This module provides the same idea as safe,
read-first runtime operations that can be exposed as MCP tools:

1. detect whether the server has a user-specific schema/taxonomy;
2. offer sensible onboarding options to the model/user;
3. analyse existing Taskwarrior tasks and/or a taxonomy Markdown file;
4. generate a reviewable schema preview;
5. save the approved schema and wire it into ``config.toml``.

The important design constraint: analysis and preview tools do not mutate
anything.  Only ``save_initial_schema`` writes files, and it is explicit.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from taskchampion_mcp.cli import TaskwarriorCLI, TimewarriorCLI
from taskchampion_mcp.config import ServerConfig, default_config_path
from taskchampion_mcp.schema_gen import (
    TaxonomyInfo,
    analyze_tasks,
    generate_schema_from_tasks_and_taxonomy,
    parse_taxonomy,
    save_generated_schema,
)

_DEFAULT_SCHEMA_NAME = "auto_generated"
_DEFAULT_SCHEMA_FILE = "generated_schema.toml"


def _config_dir() -> Path:
    return default_config_path().parent


def _default_schema_path() -> Path:
    return _config_dir() / _DEFAULT_SCHEMA_FILE


def _candidate_taxonomy_paths(project_dir: str | None = None) -> list[Path]:
    """Return likely taxonomy locations, ordered from project-local to user-global."""
    candidates: list[Path] = []

    if project_dir:
        root = Path(project_dir).expanduser()
        candidates.extend(
            [
                root / "user" / "TAXONOMY.md",
                root / "TAXONOMY.md",
                root / "docs" / "TAXONOMY.md",
                root / "taxonomy.md",
            ]
        )

    cwd = Path.cwd()
    candidates.extend(
        [
            cwd / "user" / "TAXONOMY.md",
            cwd / "TAXONOMY.md",
            cwd / "docs" / "TAXONOMY.md",
            cwd / "taxonomy.md",
            _config_dir() / "TAXONOMY.md",
            _config_dir() / "taxonomy.md",
            Path.home() / "TAXONOMY.md",
        ]
    )

    seen: set[Path] = set()
    unique: list[Path] = []
    for path in candidates:
        expanded = path.expanduser()
        if expanded not in seen:
            seen.add(expanded)
            unique.append(expanded)
    return unique


def detect_taxonomy_files(project_dir: str | None = None) -> list[str]:
    """Find taxonomy files in common locations."""
    return [str(path.resolve()) for path in _candidate_taxonomy_paths(project_dir) if path.exists()]


def resolve_taxonomy_path(
    config: ServerConfig,
    taxonomy_path: str | None = None,
    project_dir: str | None = None,
) -> Path | None:
    """Resolve an explicit, configured, or auto-detected taxonomy path."""
    if taxonomy_path:
        return Path(taxonomy_path).expanduser().resolve()
    if config.taxonomy_path:
        return Path(config.taxonomy_path).expanduser().resolve()
    detected = detect_taxonomy_files(project_dir)
    return Path(detected[0]) if detected else None


def _safe_export_tasks(task_cli: TaskwarriorCLI) -> tuple[list[dict[str, Any]], str | None]:
    try:
        return task_cli.export_tasks(), None
    except Exception as exc:  # noqa: BLE001 - diagnostics are returned to caller
        return [], str(exc)


def _safe_task_count(task_cli: TaskwarriorCLI) -> tuple[int, str | None]:
    tasks, error = _safe_export_tasks(task_cli)
    return len(tasks), error


def get_initialisation_status(
    config: ServerConfig,
    task_cli: TaskwarriorCLI,
    timew_cli: TimewarriorCLI | None = None,
    project_dir: str | None = None,
) -> dict[str, Any]:
    """Return runtime onboarding status for the connected model.

    ``initialised`` means user-specific semantics are available, not merely
    that the server managed to load the bundled minimal schema.
    """
    cfg_path = default_config_path()
    schema_path = Path(config.schema_path).expanduser() if config.schema_path else None
    taxonomy_path = Path(config.taxonomy_path).expanduser() if config.taxonomy_path else None
    detected_taxonomies = detect_taxonomy_files(project_dir)
    task_count, task_export_error = _safe_task_count(task_cli)

    custom_schema_configured = bool(schema_path)
    custom_schema_exists = bool(schema_path and schema_path.exists())
    taxonomy_configured = bool(taxonomy_path)
    taxonomy_exists = bool(taxonomy_path and taxonomy_path.exists())
    taxonomy_available = taxonomy_exists or bool(detected_taxonomies)

    initialised = custom_schema_exists or taxonomy_exists
    needs_onboarding = not initialised

    recommended_next_action = "none"
    if needs_onboarding:
        if taxonomy_available:
            recommended_next_action = "use_detected_taxonomy"
        elif task_count > 0:
            recommended_next_action = "infer_schema_from_existing_tasks"
        else:
            recommended_next_action = "ask_user_for_taxonomy_or_select_preset"

    return {
        "initialised": initialised,
        "needs_onboarding": needs_onboarding,
        "recommended_next_action": recommended_next_action,
        "config_file": str(cfg_path),
        "config_file_exists": cfg_path.exists(),
        "active_schema_name": config.schema_name,
        "custom_schema_configured": custom_schema_configured,
        "custom_schema_path": str(schema_path) if schema_path else None,
        "custom_schema_exists": custom_schema_exists,
        "taxonomy_configured": taxonomy_configured,
        "taxonomy_path": str(taxonomy_path) if taxonomy_path else None,
        "taxonomy_exists": taxonomy_exists,
        "detected_taxonomy_paths": detected_taxonomies,
        "task_export_available": task_export_error is None,
        "task_export_error": task_export_error,
        "task_count": task_count,
        "timewarrior_available": bool(timew_cli and timew_cli.available()),
        "safe_to_mutate_tasks": False,
        "message_for_model": _status_message(needs_onboarding, task_count, taxonomy_available),
    }


def _status_message(needs_onboarding: bool, task_count: int, taxonomy_available: bool) -> str:
    if not needs_onboarding:
        return "User-specific task semantics are configured. Read schema/taxonomy before modifying tasks."
    if taxonomy_available:
        return (
            "No active custom schema is configured, but a taxonomy file is available. "
            "Ask the user whether to use it to generate a reviewed schema."
        )
    if task_count > 0:
        return (
            "No taxonomy/schema is configured. Ask the user for a taxonomy file, "
            "or offer to infer a draft schema from existing tasks for review."
        )
    return (
        "No taxonomy/schema and no existing tasks are available. Ask the user to provide "
        "a taxonomy file or select a bundled preset."
    )


def propose_initialisation_options(status: dict[str, Any]) -> dict[str, Any]:
    """Build user-facing onboarding options from ``get_initialisation_status``."""
    task_count = int(status.get("task_count") or 0)
    has_taxonomy = bool(status.get("taxonomy_exists") or status.get("detected_taxonomy_paths"))

    return {
        "needs_onboarding": bool(status.get("needs_onboarding")),
        "recommended_next_action": status.get("recommended_next_action"),
        "options": [
            {
                "id": "use_taxonomy",
                "label": "Use a taxonomy Markdown file",
                "recommended": has_taxonomy,
                "requires_user_input": not has_taxonomy,
                "description": (
                    "Best option when the user has documented field meanings, lifecycle phases, "
                    "conditional requirements, project naming, and task flow."
                ),
            },
            {
                "id": "infer_from_tasks",
                "label": "Infer a draft schema from existing tasks",
                "recommended": not has_taxonomy and task_count > 0,
                "requires_user_input": False,
                "description": (
                    "Useful fallback when no taxonomy exists. It detects fields, value distributions, "
                    "likely enums, and likely required fields, but the result must be reviewed."
                ),
            },
            {
                "id": "hybrid_taxonomy_plus_tasks",
                "label": "Use taxonomy plus existing tasks",
                "recommended": has_taxonomy and task_count > 0,
                "requires_user_input": False,
                "description": (
                    "Strongest option: taxonomy supplies semantics, existing tasks supply empirical checks."
                ),
            },
            {
                "id": "use_builtin_preset",
                "label": "Use a bundled preset schema",
                "recommended": not has_taxonomy and task_count == 0,
                "requires_user_input": True,
                "description": "Lowest-friction fallback: minimal, GTD, scrum, kanban, or example schema.",
            },
        ],
    }


def analyse_existing_tasks(task_cli: TaskwarriorCLI) -> dict[str, Any]:
    """Analyse existing tasks and return field/value statistics for schema design."""
    tasks, error = _safe_export_tasks(task_cli)
    if error:
        return {"error": True, "message": f"Could not export tasks: {error}", "task_count": 0}

    analysis = analyze_tasks(tasks)
    fields: dict[str, Any] = {}
    for name, field in sorted(analysis.fields.items()):
        fields[name] = {
            "occurrence_count": field.occurrence_count,
            "usage_ratio": round(field.usage_ratio, 4),
            "is_uda": field.is_uda,
            "inferred_type": field.inferred_type,
            "inferred_required": field.inferred_required,
            "inferred_values": field.inferred_values,
            "sample_values": field.sample_values,
        }

    return {
        "success": True,
        "task_count": analysis.total_tasks,
        "fields": fields,
        "uda_fields": sorted(analysis.uda_fields().keys()),
        "builtin_fields": sorted(analysis.builtin_fields().keys()),
        "projects": analysis.projects,
        "tags": analysis.tags,
    }


def analyse_taxonomy_file(path: str) -> dict[str, Any]:
    """Parse a taxonomy Markdown file and return extracted semantics."""
    taxonomy_path = Path(path).expanduser().resolve()
    if not taxonomy_path.exists():
        return {"error": True, "message": f"Taxonomy file not found: {taxonomy_path}"}

    taxonomy = parse_taxonomy(taxonomy_path)
    return _taxonomy_summary(taxonomy, taxonomy_path)


def _taxonomy_summary(taxonomy: TaxonomyInfo, taxonomy_path: Path) -> dict[str, Any]:
    return {
        "success": True,
        "taxonomy_path": str(taxonomy_path),
        "field_count": len(taxonomy.fields),
        "condition_count": len(taxonomy.conditions),
        "phase_transition_count": len(taxonomy.phase_transitions),
        "fields": {
            name: {
                "description": field.description,
                "allowed_values": field.allowed_values,
                "type": field.type,
                "required": field.required,
                "uda": field.uda,
                "conditions": field.conditions,
            }
            for name, field in sorted(taxonomy.fields.items())
        },
        "conditions": [
            {
                "name": cond.name,
                "when": cond.when,
                "then_required": cond.then_required,
                "description": cond.description,
            }
            for cond in taxonomy.conditions
        ],
        "phase_transitions": [
            {
                "from_phase": transition.from_phase,
                "to_phase": transition.to_phase,
                "add_fields": transition.add_fields,
                "description": transition.description,
            }
            for transition in taxonomy.phase_transitions
        ],
    }


def generate_schema_preview(
    config: ServerConfig,
    task_cli: TaskwarriorCLI,
    taxonomy_path: str | None = None,
    project_dir: str | None = None,
    schema_name: str = _DEFAULT_SCHEMA_NAME,
) -> dict[str, Any]:
    """Generate a non-mutating schema preview from tasks, taxonomy, or both."""
    tasks, task_error = _safe_export_tasks(task_cli)
    resolved_taxonomy = resolve_taxonomy_path(config, taxonomy_path, project_dir)

    if resolved_taxonomy and not resolved_taxonomy.exists():
        return {"error": True, "message": f"Taxonomy file not found: {resolved_taxonomy}"}

    if not tasks and not resolved_taxonomy:
        return {
            "error": True,
            "message": "Cannot generate schema preview: no exported tasks and no taxonomy file.",
            "task_export_error": task_error,
        }

    description = f"Auto-generated from {len(tasks)} tasks"
    if resolved_taxonomy:
        description += f" + {resolved_taxonomy.name}"

    toml_content = generate_schema_from_tasks_and_taxonomy(
        tasks=tasks,
        taxonomy_path=str(resolved_taxonomy) if resolved_taxonomy else None,
        name=schema_name or _DEFAULT_SCHEMA_NAME,
        description=description,
    )

    analysis = analyze_tasks(tasks) if tasks else None
    taxonomy = parse_taxonomy(resolved_taxonomy) if resolved_taxonomy else None

    return {
        "success": True,
        "mutated": False,
        "schema_name": schema_name or _DEFAULT_SCHEMA_NAME,
        "task_count": len(tasks),
        "task_export_error": task_error,
        "taxonomy_path": str(resolved_taxonomy) if resolved_taxonomy else None,
        "summary": {
            "fields_from_tasks": sorted(analysis.fields.keys()) if analysis else [],
            "uda_fields_from_tasks": sorted(analysis.uda_fields().keys()) if analysis else [],
            "fields_from_taxonomy": sorted(taxonomy.fields.keys()) if taxonomy else [],
            "conditions_from_taxonomy": len(taxonomy.conditions) if taxonomy else 0,
            "phase_transitions_from_taxonomy": len(taxonomy.phase_transitions) if taxonomy else 0,
        },
        "schema_toml": toml_content,
        "review_note": (
            "Review schema_toml before saving. Inferred enum/required fields are heuristics; "
            "taxonomy descriptions are treated as higher authority than raw task data."
        ),
    }


def save_initial_schema(
    schema_toml: str,
    taxonomy_path: str | None = None,
    output_path: str | None = None,
    overwrite: bool = False,
    update_config: bool = True,
) -> dict[str, Any]:
    """Persist an approved generated schema and optionally update config.toml."""
    if not schema_toml.strip():
        return {
            "error": True,
            "message": "schema_toml is empty; generate and review a preview first.",
        }

    out = Path(output_path).expanduser() if output_path else _default_schema_path()
    if out.exists():
        if not overwrite:
            return {
                "error": True,
                "message": f"Schema file already exists: {out}. Pass overwrite=true to replace it.",
            }
        out.unlink()

    saved_path = save_generated_schema(schema_toml, out)

    cfg_path: Path | None = None
    if update_config:
        cfg_path = _upsert_server_config(
            schema_path=str(saved_path),
            taxonomy_path=str(Path(taxonomy_path).expanduser().resolve())
            if taxonomy_path
            else None,
        )

    return {
        "success": True,
        "schema_path": str(saved_path),
        "config_updated": update_config,
        "config_file": str(cfg_path) if cfg_path else None,
        "message": "Initial schema saved. Restart the MCP server to load it.",
    }


def _upsert_server_config(schema_path: str, taxonomy_path: str | None = None) -> Path:
    """Insert/update schema_path and taxonomy_path in the user config file."""
    cfg_path = default_config_path()
    cfg_path.parent.mkdir(parents=True, exist_ok=True)

    lines = cfg_path.read_text(encoding="utf-8").splitlines() if cfg_path.exists() else []
    new_lines: list[str] = []
    in_server = False
    saw_server = False
    wrote_schema = False
    wrote_taxonomy = False

    def append_missing_server_keys() -> None:
        nonlocal wrote_schema, wrote_taxonomy
        if not wrote_schema:
            new_lines.append(f'schema_path = "{schema_path}"')
            wrote_schema = True
        if taxonomy_path and not wrote_taxonomy:
            new_lines.append(f'taxonomy_path = "{taxonomy_path}"')
            wrote_taxonomy = True

    for line in lines:
        stripped = line.strip()
        if stripped == "[server]":
            saw_server = True
            in_server = True
            new_lines.append(line)
            continue

        if stripped.startswith("[") and stripped != "[server]":
            if in_server:
                append_missing_server_keys()
            in_server = False
            new_lines.append(line)
            continue

        if in_server and stripped.startswith("schema_path"):
            new_lines.append(f'schema_path = "{schema_path}"')
            wrote_schema = True
            continue

        if in_server and taxonomy_path and stripped.startswith("taxonomy_path"):
            new_lines.append(f'taxonomy_path = "{taxonomy_path}"')
            wrote_taxonomy = True
            continue

        if in_server and stripped.startswith("schema "):
            new_lines.append(f"# {stripped}  # overridden by schema_path")
            continue

        new_lines.append(line)

    if not saw_server:
        if new_lines and new_lines[-1].strip():
            new_lines.append("")
        new_lines.append("[server]")
        in_server = True

    if in_server:
        append_missing_server_keys()

    cfg_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    return cfg_path


__all__ = [
    "analyse_existing_tasks",
    "analyse_taxonomy_file",
    "detect_taxonomy_files",
    "generate_schema_preview",
    "get_initialisation_status",
    "propose_initialisation_options",
    "resolve_taxonomy_path",
    "save_initial_schema",
]
