# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25

"""Schema auto-generation from existing tasks and taxonomy files (IDEA-003).

This module provides three capabilities:
1. Analyze exported Taskwarrior tasks to detect fields, value distributions, and usage patterns.
2. Parse a taxonomy markdown file to extract field descriptions, allowed values,
   conditional requirements, and lifecycle process definitions.
3. Generate a draft TOML schema combining both data sources.
"""

from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Built-in Taskwarrior fields (not UDAs)
# ---------------------------------------------------------------------------

BUILTIN_FIELDS: set[str] = {
    "id",
    "uuid",
    "description",
    "status",
    "project",
    "priority",
    "tags",
    "due",
    "wait",
    "until",
    "depends",
    "recur",
    "entry",
    "modified",
    "start",
    "end",
    "urgency",
    "annotations",
    "mask",
    "imask",
    "parent",
    "scheduled",
}

# Fields that should be excluded from schema generation entirely
# (internal/computed fields the user never sets directly)
EXCLUDED_FIELDS: set[str] = {
    "id",
    "uuid",
    "entry",
    "modified",
    "start",
    "end",
    "urgency",
    "mask",
    "imask",
    "parent",
    "status",
}

# Fields that are always type="list" in Taskwarrior JSON
LIST_FIELDS: set[str] = {"tags", "annotations"}

# Fields that are always type="date" in Taskwarrior JSON
DATE_FIELDS: set[str] = {"due", "wait", "until", "scheduled"}


# ---------------------------------------------------------------------------
# Data models — Task Analysis
# ---------------------------------------------------------------------------


@dataclass
class FieldAnalysis:
    """Analysis results for a single field across all tasks."""

    name: str
    occurrence_count: int = 0
    total_tasks: int = 0
    unique_values: Counter = field(default_factory=Counter)
    sample_values: list[str] = field(default_factory=list)
    is_uda: bool = False
    is_list: bool = False
    is_date: bool = False

    @property
    def usage_ratio(self) -> float:
        """Fraction of tasks that have this field (0.0 to 1.0)."""
        return self.occurrence_count / self.total_tasks if self.total_tasks else 0.0

    @property
    def is_likely_enum(self) -> bool:
        """Heuristic: field is enum-like if <=20 unique values and >50% usage."""
        return (
            len(self.unique_values) <= 20
            and self.occurrence_count >= 2
            and not self.is_list
            and not self.is_date
        )

    @property
    def inferred_type(self) -> str:
        if self.is_list:
            return "list"
        if self.is_date:
            return "date"
        return "string"

    @property
    def inferred_required(self) -> bool:
        """Field is likely required if present on >=90% of tasks."""
        return self.usage_ratio >= 0.90

    @property
    def inferred_values(self) -> list[str] | None:
        """Return sorted unique values if the field looks enum-like."""
        if self.is_likely_enum:
            return sorted(self.unique_values.keys())
        return None


@dataclass
class TaskAnalysis:
    """Aggregated analysis of a set of exported tasks."""

    total_tasks: int = 0
    fields: dict[str, FieldAnalysis] = field(default_factory=dict)
    projects: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)

    def uda_fields(self) -> dict[str, FieldAnalysis]:
        return {k: v for k, v in self.fields.items() if v.is_uda}

    def builtin_fields(self) -> dict[str, FieldAnalysis]:
        return {k: v for k, v in self.fields.items() if not v.is_uda}


# ---------------------------------------------------------------------------
# Data models — Taxonomy
# ---------------------------------------------------------------------------


@dataclass
class TaxonomyField:
    """A field definition parsed from a taxonomy document."""

    name: str
    description: str = ""
    allowed_values: list[str] | None = None
    type: str = "string"
    required: bool = False
    uda: bool = False
    conditions: list[str] = field(default_factory=list)


@dataclass
class TaxonomyCondition:
    """A conditional requirement parsed from a taxonomy document."""

    name: str
    when: str
    then_required: list[str] = field(default_factory=list)
    description: str = ""


@dataclass
class TaxonomyPhaseTransition:
    """A phase transition rule parsed from a taxonomy document."""

    from_phase: str
    to_phase: str
    add_fields: list[str] = field(default_factory=list)
    description: str = ""


@dataclass
class TaxonomyInfo:
    """All information extracted from a taxonomy document."""

    fields: dict[str, TaxonomyField] = field(default_factory=dict)
    conditions: list[TaxonomyCondition] = field(default_factory=list)
    phase_transitions: list[TaxonomyPhaseTransition] = field(default_factory=list)
    raw_sections: dict[str, str] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Task analysis
# ---------------------------------------------------------------------------


def analyze_tasks(tasks: list[dict[str, Any]]) -> TaskAnalysis:
    """Analyze a list of exported Taskwarrior tasks to detect field usage patterns.

    Args:
        tasks: List of task dicts (from ``task export`` JSON).

    Returns:
        A ``TaskAnalysis`` with per-field statistics.
    """
    analysis = TaskAnalysis(total_tasks=len(tasks))

    if not tasks:
        return analysis

    all_projects: set[str] = set()
    all_tags: set[str] = set()

    for task in tasks:
        for key, value in task.items():
            if key in EXCLUDED_FIELDS:
                continue

            if key not in analysis.fields:
                is_list = key in LIST_FIELDS or isinstance(value, list)
                is_date = key in DATE_FIELDS
                is_uda = key not in BUILTIN_FIELDS
                analysis.fields[key] = FieldAnalysis(
                    name=key,
                    total_tasks=len(tasks),
                    is_uda=is_uda,
                    is_list=is_list,
                    is_date=is_date,
                )

            fa = analysis.fields[key]
            fa.occurrence_count += 1

            if isinstance(value, list):
                fa.is_list = True
                if key == "tags":
                    for tag in value:
                        all_tags.add(str(tag))
            elif isinstance(value, str) and value:
                fa.unique_values[value] += 1
                if len(fa.sample_values) < 5:
                    fa.sample_values.append(value)

            if key == "project" and isinstance(value, str) and value:
                all_projects.add(value)

    # Ensure total_tasks is set on all fields (for late-discovered fields)
    for fa in analysis.fields.values():
        fa.total_tasks = len(tasks)

    analysis.projects = sorted(all_projects)
    analysis.tags = sorted(all_tags)

    return analysis


# ---------------------------------------------------------------------------
# Taxonomy markdown parser
# ---------------------------------------------------------------------------

# Pattern for UDA field headings like: ### 2.1 `scope` — personal | work
# or: ### 2.1 scope — personal | work
_FIELD_HEADING_RE = re.compile(
    r"^###\s+"
    r"(?:\d+\.\d+\s+)?"  # optional section number like "2.1 "
    r"`?(\w+)`?"  # field name, optionally backticked
    r"\s*(?:—|--|-)\s*"  # separator (em-dash, double-dash, or single dash)
    r"(.+)$",  # rest of heading (may contain allowed values)
    re.MULTILINE,
)

# Pattern for table rows: | value | description |
_TABLE_ROW_RE = re.compile(
    r"^\|\s*`?(\w[\w\-]*)`?\s*\|",
    re.MULTILINE,
)

# Pattern for "Required when" phrases
_REQUIRED_WHEN_RE = re.compile(
    r"[Rr]equired\s+when\s+[`']?(\w+)[`']?\s*(?:is\s+)?[`'\"]?(\w+)[`'\"]?",
)

# Pattern for phase transition sections: ### idea → research
_PHASE_TRANSITION_RE = re.compile(
    r"^(?:#+\s+)?(\w+)\s*(?:→|->|to)\s*(\w+)",
    re.MULTILINE,
)


def parse_taxonomy(path: str | Path) -> TaxonomyInfo:
    """Parse a taxonomy markdown file for field definitions and process rules.

    The parser extracts:
    - **Field definitions** from headings like ``### 2.1 scope — personal | work``
    - **Allowed values** from heading suffixes or markdown tables
    - **Descriptions** from the paragraph following a field heading
    - **Conditional requirements** from "Required when ..." phrases
    - **Phase transitions** from sections describing lifecycle progression

    Args:
        path: Path to the taxonomy markdown file.

    Returns:
        A ``TaxonomyInfo`` populated with extracted information.

    Raises:
        FileNotFoundError: If the taxonomy file does not exist.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Taxonomy file not found: {path}")

    text = path.read_text(encoding="utf-8")
    info = TaxonomyInfo()

    # Split into top-level sections by ## headings
    sections = _split_sections(text)
    info.raw_sections = sections

    # Extract field definitions from UDA-related sections
    _extract_fields(text, info)

    # Extract conditional requirements
    _extract_conditions(text, info)

    # Extract phase transitions
    _extract_phase_transitions(text, info)

    return info


def _split_sections(text: str) -> dict[str, str]:
    """Split markdown into sections keyed by ## heading title."""
    sections: dict[str, str] = {}
    current_title = ""
    current_lines: list[str] = []

    for line in text.split("\n"):
        if line.startswith("## "):
            if current_title:
                sections[current_title] = "\n".join(current_lines)
            current_title = line.lstrip("# ").strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_title:
        sections[current_title] = "\n".join(current_lines)

    return sections


def _extract_fields(text: str, info: TaxonomyInfo) -> None:
    """Extract field definitions from the taxonomy text."""
    # Find all ### field headings
    for match in _FIELD_HEADING_RE.finditer(text):
        field_name = match.group(1).lower()
        heading_rest = match.group(2).strip()
        start_pos = match.end()

        # Find the text until the next ### heading or ## heading
        next_heading = re.search(r"\n##", text[start_pos:])
        if next_heading:
            section_text = text[start_pos : start_pos + next_heading.start()]
        else:
            section_text = text[start_pos:]

        # Determine allowed values from heading (e.g., "personal | work")
        allowed_values = _parse_values_from_heading(heading_rest)

        # Also check for table-based values in the section
        if not allowed_values:
            allowed_values = _parse_values_from_table(section_text)

        # Extract description: first non-empty paragraph after heading
        description = _extract_description(section_text)

        # Detect type
        field_type = "string"
        if field_name in LIST_FIELDS:
            field_type = "list"
        elif field_name in DATE_FIELDS or re.search(r"\bdate\b", heading_rest, re.IGNORECASE):
            field_type = "date"

        # Detect required
        required = False
        required_markers = [
            "required on all tasks",
            "required on every",
            "every task must have",
            "every task should have",
            "must have one",
        ]
        lower_section = section_text.lower()
        if any(marker in lower_section for marker in required_markers):
            required = True

        # Check for "Required when" conditions on this field
        conditions: list[str] = []
        for cond_match in _REQUIRED_WHEN_RE.finditer(section_text):
            conditions.append(f"Required when {cond_match.group(1)}:{cond_match.group(2)}")

        tax_field = TaxonomyField(
            name=field_name,
            description=description,
            allowed_values=allowed_values if allowed_values else None,
            type=field_type,
            required=required,
            uda=field_name not in BUILTIN_FIELDS,
            conditions=conditions,
        )
        info.fields[field_name] = tax_field


def _parse_values_from_heading(heading_rest: str) -> list[str] | None:
    """Parse allowed values from heading suffix like 'personal | work'."""
    # Remove backticks and quotes
    cleaned = heading_rest.replace("`", "").replace("'", "").replace('"', "")

    # Check for pipe-separated values pattern
    if "|" in cleaned:
        parts = [p.strip() for p in cleaned.split("|")]
        # Filter out non-value strings (headings with pipes for other reasons)
        values = [p for p in parts if p and len(p) < 30 and " " not in p]
        if len(values) >= 2:
            return values

    return None


def _parse_values_from_table(section_text: str) -> list[str] | None:
    """Extract values from markdown table rows in a section."""
    values: list[str] = []
    in_table = False

    for line in section_text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("|") and stripped.endswith("|"):
            # Skip header separator rows
            if re.match(r"^\|[\s\-|]+\|$", stripped):
                in_table = True
                continue
            if in_table:
                match = _TABLE_ROW_RE.match(stripped)
                if match:
                    val = match.group(1).strip()
                    # Skip generic header-like values
                    if val.lower() not in ("value", "tag", "command", "factor"):
                        values.append(val)
        elif in_table and stripped and not stripped.startswith("|"):
            # Table ended
            in_table = False

    return values if values else None


def _extract_description(section_text: str) -> str:
    """Extract the first meaningful paragraph from section text."""
    lines: list[str] = []
    started = False

    for line in section_text.split("\n"):
        stripped = line.strip()
        # Skip empty lines before content starts
        if not started and not stripped:
            continue
        # Skip code blocks
        if stripped.startswith("```"):
            if started:
                break
            continue
        # Skip table rows
        if stripped.startswith("|"):
            if started:
                break
            continue
        if stripped:
            started = True
            lines.append(stripped)
        elif started:
            # Empty line after content = end of paragraph
            break

    desc = " ".join(lines)
    # Truncate if too long
    if len(desc) > 500:
        desc = desc[:497] + "..."
    return desc


def _extract_conditions(text: str, info: TaxonomyInfo) -> None:
    """Extract conditional requirement rules from taxonomy text.

    Uses two strategies:
    1. Per-field "Required when" phrases already detected during field extraction.
    2. Line-by-line scanning for "Required when <field> is '<value>'" patterns,
       scoped to lines that also mention a field name from ``info.fields``.
    3. Detect "Work tasks only/must ... client" patterns for scope conditions.
    """
    seen_conditions: set[str] = set()

    # Strategy 1: Build conditions from per-field "Required when" data.
    # Each field in info.fields may have conditions like
    # "Required when phase:research" stored during _extract_fields.
    for fname, tfield in info.fields.items():
        for cond_text in tfield.conditions:
            # Parse "Required when phase:research" or similar
            match = re.match(
                r"Required when (\w+):(\w+)",
                cond_text,
            )
            if match:
                trigger_field = match.group(1).lower()
                trigger_value = match.group(2).lower()
                cond_key = f"{trigger_field}_{trigger_value}_needs_{fname}"
                if cond_key not in seen_conditions:
                    seen_conditions.add(cond_key)
                    info.conditions.append(
                        TaxonomyCondition(
                            name=cond_key,
                            when=f"{trigger_field} == '{trigger_value}'",
                            then_required=[fname],
                            description=(
                                f"{fname} is required when {trigger_field} is {trigger_value}."
                            ),
                        )
                    )

    # Strategy 2: Line-scoped regex for "Required when `phase` is 'value'"
    # patterns that reference a known field name on the same line or
    # within the same ### section.
    req_line_re = re.compile(
        r"[Rr]equired\s+when\s+`?(\w+)`?\s+is\s+[`'\"]?(\w+)[`'\"]?"
        r"(?:\s+or\s+`?\w+`?\s+is\s+[`'\"]?(\w+)[`'\"]?)?",
    )
    # Process line-by-line to stay scoped
    current_field: str | None = None
    for line in text.split("\n"):
        # Track which field section we're in
        heading_match = _FIELD_HEADING_RE.match(line)
        if heading_match:
            current_field = heading_match.group(1).lower()
            continue

        if current_field and current_field in info.fields:
            for rmatch in req_line_re.finditer(line):
                trigger = rmatch.group(1).lower()
                val1 = rmatch.group(2).lower()
                val2 = (
                    rmatch.group(3).lower() if rmatch.lastindex >= 3 and rmatch.group(3) else None
                )
                for val in (val1, val2):
                    if val is None:
                        continue
                    cond_key = f"{trigger}_{val}_needs_{current_field}"
                    if cond_key not in seen_conditions:
                        seen_conditions.add(cond_key)
                        info.conditions.append(
                            TaxonomyCondition(
                                name=cond_key,
                                when=f"{trigger} == '{val}'",
                                then_required=[current_field],
                                description=(
                                    f"{current_field} is required when {trigger} is {val}."
                                ),
                            )
                        )

    # Strategy 3: Detect "Work tasks only/must ... client" patterns
    work_client = re.search(
        r"[Ww]ork\s+tasks?\s+(?:only|must)\b.*?\b(client|org)\b",
        text,
    )
    if work_client:
        cond_key = "work_needs_client"
        if cond_key not in seen_conditions:
            seen_conditions.add(cond_key)
            info.conditions.append(
                TaxonomyCondition(
                    name=cond_key,
                    when="scope == 'work'",
                    then_required=["client"],
                    description="Work tasks must specify the client.",
                )
            )


def _extract_phase_transitions(text: str, info: TaxonomyInfo) -> None:
    """Extract phase transition rules from the taxonomy text."""
    # Handles multiple formats:
    # - "### idea → research" (heading-based)
    # - "idea → research: Add hypothesis" (inline)
    # - "When promoting from `idea` → `research`: Add hypothesis" (prose)
    # - "- **When promoting a task from `idea` → `research`:** Add ..." (list)

    transition_patterns = [
        # Heading-style: ### idea → research
        re.compile(
            r"(?:^|\n)\s*(?:#+\s+)"
            r"`?(\w+)`?\s*(?:→|->)\s*`?(\w+)`?"
            r"\s*(?::|—|-)\s*(.+?)(?:\n|$)",
        ),
        # Prose/list-style: "from `idea` → `research`" with trailing description
        re.compile(
            r"from\s+`?(\w+)`?\s*(?:→|->)\s*`?(\w+)`?"
            r"\s*(?::`?\*?\*?\s*|\s*(?::|—|-)\s*)(.+?)(?:\n|$)",
            re.IGNORECASE,
        ),
        # Simple inline: "idea → research: description"
        re.compile(
            r"(?:^|\n)\s*`?(\w+)`?\s*(?:→|->)\s*`?(\w+)`?"
            r"\s*(?::|—|-)\s*(.+?)(?:\n|$)",
        ),
    ]

    seen_transitions: set[tuple[str, str]] = set()

    for pattern in transition_patterns:
        for match in pattern.finditer(text):
            from_phase = match.group(1).lower()
            to_phase = match.group(2).lower()
            desc = match.group(3).strip().rstrip("*").strip()

            key = (from_phase, to_phase)
            if key in seen_transitions:
                continue
            seen_transitions.add(key)

            # Try to detect "Add <field>" instructions
            add_fields: list[str] = []
            add_match = re.findall(r"[Aa]dd\s+`?(\w+)`?", desc)
            if add_match:
                add_fields = [f.lower() for f in add_match]

            info.phase_transitions.append(
                TaxonomyPhaseTransition(
                    from_phase=from_phase,
                    to_phase=to_phase,
                    add_fields=add_fields,
                    description=desc,
                )
            )


# ---------------------------------------------------------------------------
# Schema TOML generation
# ---------------------------------------------------------------------------


def generate_schema_toml(
    analysis: TaskAnalysis | None = None,
    taxonomy: TaxonomyInfo | None = None,
    name: str = "auto_generated",
    description: str = "",
) -> str:
    """Generate a TOML schema string by combining task analysis and taxonomy info.

    Priority rules when both sources provide data for the same field:
    - Taxonomy descriptions always win over inferred descriptions.
    - Taxonomy allowed_values win; analysis values are used as fallback.
    - required = True if either source says so.
    - Taxonomy conditions are included directly.
    - Analysis-only fields (detected UDAs not in taxonomy) are included with
      inferred metadata and a note.

    Args:
        analysis: Results from ``analyze_tasks()``, or None.
        taxonomy: Results from ``parse_taxonomy()``, or None.
        name: Schema name for the ``[meta]`` section.
        description: Schema description for the ``[meta]`` section.

    Returns:
        A TOML-formatted string ready to be saved as a ``.toml`` file.
    """
    lines: list[str] = []

    if not description:
        description = "Auto-generated schema"
        if analysis:
            description += f" from {analysis.total_tasks} existing tasks"
        if taxonomy:
            description += " with taxonomy enrichment"

    # [meta]
    lines.append("# TaskChampion MCP — Auto-Generated Schema")
    lines.append("# Generated from task analysis and taxonomy file")
    lines.append("# Review and adjust before use.")
    lines.append("")
    lines.append("[meta]")
    lines.append(f'name = "{name}"')
    lines.append('version = "1.0.0"')
    lines.append(f'description = "{_escape_toml(description)}"')
    lines.append('taskwarrior_version = "3.x"')
    lines.append("")

    # Merge fields from both sources
    merged_fields = _merge_fields(analysis, taxonomy)

    # Separate builtin and UDA fields
    builtin = {k: v for k, v in merged_fields.items() if not v.get("uda", False)}
    udas = {k: v for k, v in merged_fields.items() if v.get("uda", False)}

    # Builtin fields
    if builtin:
        lines.append(
            "# ============================================================================="
        )
        lines.append("# Built-in Taskwarrior Fields")
        lines.append(
            "# ============================================================================="
        )
        lines.append("")
        for field_name, fdata in builtin.items():
            lines.extend(_render_field(field_name, fdata))

    # UDA fields
    if udas:
        lines.append(
            "# ============================================================================="
        )
        lines.append("# UDA Fields")
        lines.append(
            "# ============================================================================="
        )
        lines.append("")
        for field_name, fdata in udas.items():
            lines.extend(_render_field(field_name, fdata))

    # Conditions
    conditions = _merge_conditions(analysis, taxonomy)
    if conditions:
        lines.append(
            "# ============================================================================="
        )
        lines.append("# Conditional Requirements")
        lines.append(
            "# ============================================================================="
        )
        lines.append("")
        for cond in conditions:
            cond_name = cond["name"]
            lines.append(f"[conditions.{cond_name}]")
            lines.append(f'when = "{_escape_toml(cond["when"])}"')
            vals = ", ".join(f'"{v}"' for v in cond["then_required"])
            lines.append(f"then_required = [{vals}]")
            if cond.get("description"):
                lines.append(f'description = "{_escape_toml(cond["description"])}"')
            lines.append("")

    # Phase transitions (if taxonomy provided them)
    if taxonomy and taxonomy.phase_transitions:
        lines.append(
            "# ============================================================================="
        )
        lines.append("# Phase Transitions")
        lines.append(
            "# ============================================================================="
        )
        lines.append("")
        lines.append("[phase_transitions]")
        lines.append('description = "Rules for promoting tasks between phases."')
        lines.append("")
        for pt in taxonomy.phase_transitions:
            key = f"{pt.from_phase}_to_{pt.to_phase}"
            lines.append(f"[phase_transitions.{key}]")
            if pt.add_fields:
                vals = ", ".join(f'"{f}"' for f in pt.add_fields)
                lines.append(f"add_fields = [{vals}]")
            lines.append(f'description = "{_escape_toml(pt.description)}"')
            lines.append("")

    # Analysis summary as comments
    if analysis:
        lines.append(
            "# ============================================================================="
        )
        lines.append("# Analysis Summary (for reference, not parsed by schema loader)")
        lines.append(
            "# ============================================================================="
        )
        lines.append(f"# Total tasks analyzed: {analysis.total_tasks}")
        if analysis.projects:
            lines.append(f"# Projects found: {', '.join(analysis.projects[:20])}")
        if analysis.tags:
            lines.append(f"# Tags found: {', '.join(analysis.tags[:30])}")
        lines.append("")

    return "\n".join(lines)


def _merge_fields(
    analysis: TaskAnalysis | None,
    taxonomy: TaxonomyInfo | None,
) -> dict[str, dict[str, Any]]:
    """Merge field information from analysis and taxonomy into a unified dict."""
    merged: dict[str, dict[str, Any]] = {}

    # Start with taxonomy fields (higher authority for descriptions/values)
    if taxonomy:
        for fname, tfield in taxonomy.fields.items():
            merged[fname] = {
                "type": tfield.type,
                "required": tfield.required,
                "description": tfield.description,
                "uda": tfield.uda,
            }
            if tfield.allowed_values:
                merged[fname]["values"] = tfield.allowed_values

    # Layer in analysis data
    if analysis:
        for fname, fa in analysis.fields.items():
            if fname in merged:
                # Enrich existing entry with analysis data
                entry = merged[fname]
                # If taxonomy didn't say required but analysis shows >=90%, mark required
                if not entry["required"] and fa.inferred_required:
                    entry["required"] = True
                # If taxonomy didn't provide values but analysis infers enum
                if "values" not in entry and fa.inferred_values:
                    entry["values"] = fa.inferred_values
                # Add usage stats as a comment hint
                entry["_usage"] = f"{fa.occurrence_count}/{fa.total_tasks}"
            else:
                # New field from analysis only
                entry: dict[str, Any] = {
                    "type": fa.inferred_type,
                    "required": fa.inferred_required,
                    "description": (
                        f"Detected from task data ({fa.occurrence_count}/{fa.total_tasks} tasks)."
                    ),
                    "uda": fa.is_uda,
                    "_usage": f"{fa.occurrence_count}/{fa.total_tasks}",
                }
                if fa.inferred_values:
                    entry["values"] = fa.inferred_values
                merged[fname] = entry

    return merged


def _merge_conditions(
    analysis: TaskAnalysis | None,
    taxonomy: TaxonomyInfo | None,
) -> list[dict[str, Any]]:
    """Merge conditions from taxonomy (analysis doesn't produce conditions)."""
    conditions: list[dict[str, Any]] = []

    if taxonomy:
        for cond in taxonomy.conditions:
            conditions.append(
                {
                    "name": cond.name,
                    "when": cond.when,
                    "then_required": cond.then_required,
                    "description": cond.description,
                }
            )

    return conditions


def _sanitize_toml_key(name: str) -> str:
    """Quote a field name for use as a TOML table key if needed.

    TOML table keys must be alphanumeric, underscores, or dashes only.
    If the field name contains other characters, it is quoted to preserve
    the original field name and avoid collisions.
    """
    if re.match(r"^[a-zA-Z0-9_-]+$", name):
        return name
    # Use quoted key to preserve special characters and avoid name collisions
    return f'"{name}"'


def _render_field(field_name: str, fdata: dict[str, Any]) -> list[str]:
    """Render a single field definition as TOML lines."""
    lines = []
    safe_name = _sanitize_toml_key(field_name)
    lines.append(f"[fields.{safe_name}]")
    lines.append(f'type = "{fdata.get("type", "string")}"')
    lines.append(f"required = {str(fdata.get('required', False)).lower()}")
    if fdata.get("values"):
        vals = ", ".join(f'"{v}"' for v in fdata["values"])
        lines.append(f"values = [{vals}]")
    if fdata.get("uda"):
        lines.append("uda = true")
    desc = fdata.get("description", "")
    if desc:
        if "\n" in desc or len(desc) > 80:
            lines.append(f'description = """{_escape_toml_multiline(desc)}"""')
        else:
            lines.append(f'description = "{_escape_toml(desc)}"')
    lines.append("")
    return lines


def _escape_toml(s: str) -> str:
    """Escape a string for use in a TOML double-quoted value."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _escape_toml_multiline(s: str) -> str:
    """Escape a string for use in a TOML triple-quoted value."""
    return s.replace("\\", "\\\\").replace('"""', '\\"""')


# ---------------------------------------------------------------------------
# High-level convenience function
# ---------------------------------------------------------------------------


def generate_schema_from_tasks_and_taxonomy(
    tasks: list[dict[str, Any]],
    taxonomy_path: str | Path | None = None,
    name: str = "auto_generated",
    description: str = "",
) -> str:
    """One-shot convenience: analyze tasks, optionally parse taxonomy, generate TOML.

    Args:
        tasks: List of task dicts from ``task export``.
        taxonomy_path: Optional path to a taxonomy markdown file.
        name: Schema name.
        description: Schema description.

    Returns:
        TOML schema string.
    """
    analysis = analyze_tasks(tasks) if tasks else None

    taxonomy: TaxonomyInfo | None = None
    if taxonomy_path:
        taxonomy = parse_taxonomy(taxonomy_path)

    return generate_schema_toml(
        analysis=analysis,
        taxonomy=taxonomy,
        name=name,
        description=description,
    )


def save_generated_schema(
    toml_content: str,
    output_path: str | Path,
) -> Path:
    """Write generated TOML schema to a file.

    Creates parent directories if needed. Will NOT overwrite an existing file —
    raises FileExistsError instead.

    Args:
        toml_content: The TOML string to write.
        output_path: Destination file path.

    Returns:
        The resolved Path that was written.
    """
    path = Path(output_path)
    if path.exists():
        raise FileExistsError(
            f"Schema file already exists: {path}. Remove or rename it before generating a new one."
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(toml_content, encoding="utf-8")
    return path.resolve()
