# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25

"""TaskChampion MCP Server — entry point.

Registers MCP tools based on the configured role level (ADR 5)
and starts the stdio transport (ADR 3).
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from mcp.server.fastmcp import FastMCP

from taskchampion_mcp.audit import AuditLogger
from taskchampion_mcp.cli import TaskwarriorCLI, TimewarriorCLI
from taskchampion_mcp.config import (
    Role,
    ServerConfig,
    dump_effective_config,
    load_config,
    load_config_with_sources,
)
from taskchampion_mcp.onboarding import (
    analyse_existing_tasks as onboarding_analyse_existing_tasks,
)
from taskchampion_mcp.onboarding import (
    analyse_taxonomy_file as onboarding_analyze_taxonomy_file,
)
from taskchampion_mcp.onboarding import (
    generate_schema_preview as onboarding_generate_schema_preview,
)
from taskchampion_mcp.onboarding import (
    get_initialisation_status as onboarding_get_initialization_status,
)
from taskchampion_mcp.onboarding import (
    list_preset_schemas as onboarding_list_preset_schemas,
)
from taskchampion_mcp.onboarding import (
    propose_initialisation_options as onboarding_propose_initialization_options,
)
from taskchampion_mcp.onboarding import (
    reconfigure_active_schema as onboarding_reconfigure_active_schema,
)
from taskchampion_mcp.onboarding import (
    reconfigure_role as onboarding_reconfigure_role,
)
from taskchampion_mcp.onboarding import (
    reconfigure_taxonomy_path as onboarding_reconfigure_taxonomy_path,
)
from taskchampion_mcp.onboarding import (
    save_initial_schema as onboarding_save_initial_schema,
)
from taskchampion_mcp.onboarding import (
    use_preset_schema as onboarding_use_preset_schema,
)
from taskchampion_mcp.rate_limiter import RateLimiter
from taskchampion_mcp.schema import TaskSchema, load_schema
from taskchampion_mcp.tools import ToolRegistry

logger = logging.getLogger("taskchampion_mcp")


class _JsonLineFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        payload: dict[str, Any] = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "logger": record.name,
            "level": record.levelname,
            "message": record.getMessage(),
        }
        if record.exc_info:
            payload["exc_info"] = self.formatException(record.exc_info)
        return json.dumps(payload, default=str)


def _resolve_log_level(level_name: str) -> tuple[int, bool]:
    requested = (level_name or "INFO").upper()
    if requested in logging._nameToLevel and logging._nameToLevel[requested]:
        return logging._nameToLevel[requested], False
    return logging.INFO, True


def _configure_logging(stream: Any | None = None) -> None:
    stderr_stream = stream if stream is not None else sys.stderr
    level_name = os.environ.get("TC_MCP_LOG_LEVEL", "INFO")
    level, invalid_level = _resolve_log_level(level_name)

    is_tty = bool(getattr(stderr_stream, "isatty", lambda: False)())
    formatter: logging.Formatter
    if is_tty:
        formatter = logging.Formatter("%(asctime)s [%(name)s] %(levelname)s: %(message)s")
    else:
        formatter = _JsonLineFormatter()

    logging.basicConfig(level=level, stream=stderr_stream, format="%(message)s", force=True)
    for handler in logging.getLogger().handlers:
        handler.setFormatter(formatter)

    if invalid_level:
        logger.warning(
            "Invalid TC_MCP_LOG_LEVEL '%s'; falling back to INFO.",
            level_name,
        )


# ---------------------------------------------------------------------------
# Server factory
# ---------------------------------------------------------------------------


def create_server(
    config: ServerConfig | None = None,
    config_path: Path | None = None,
) -> FastMCP:
    """Build and configure the MCP server with role-appropriate tools."""

    if config is None:
        config = load_config(config_path)

    # --- Detect tools -------------------------------------------------------
    task_cli = TaskwarriorCLI(
        binary=config.task_binary,
        override_rc=config.taskwarrior_override_rc,
    )
    tw_version = task_cli.version()
    if tw_version is None:
        logger.error(
            "Taskwarrior not found on PATH (%s). "
            "Install Taskwarrior 3.x and ensure 'task' is available.",
            config.task_binary,
        )
        sys.exit(1)

    major = tw_version.split(".")[0] if tw_version else "0"
    if major == "2":
        logger.warning(
            "Taskwarrior 2.x detected (%s). This MCP targets 3.x. "
            "Some features may not work correctly.",
            tw_version,
        )
    elif major not in ("3",):
        logger.warning("Unexpected Taskwarrior version: %s", tw_version)

    timew_cli: TimewarriorCLI | None = None
    timew_instance = TimewarriorCLI(binary=config.timew_binary)
    if timew_instance.available():
        timew_cli = timew_instance
        logger.info(
            "Timewarrior detected: %s",
            timew_instance.version(),
        )
    else:
        logger.info("Timewarrior not found. Time tracking tools disabled.")

    # --- Init required ------------------------------------------------------
    def requires_onboarding(config: ServerConfig) -> bool:
        return not (config.explicit_role_configured and config.explicit_schema_configured)

    # --- Load schema --------------------------------------------------------
    schema: TaskSchema
    if config.schema_path:
        schema = load_schema(config.schema_path)
    else:
        schema = load_schema(config.schema_name)
    logger.info("Schema loaded: %s v%s", schema.name, schema.version)

    # --- Build shared state -------------------------------------------------
    rate_limiter = RateLimiter(
        ops_per_minute=config.rate_limit_per_minute,
        ops_per_hour=config.rate_limit_per_hour,
        creates_per_hour=config.create_limit_per_hour,
    )

    audit = AuditLogger(
        config.audit_log_path,
        redacted_fields=config.redacted_fields,
    )
    audit.log_startup(config.role, schema.name, tw_version)

    registry = ToolRegistry(
        config=config,
        task_cli=task_cli,
        timew_cli=timew_cli,
        schema=schema,
        rate_limiter=rate_limiter,
        audit=audit,
    )
    onboarding_required = requires_onboarding(config)

    # --- Create FastMCP server ----------------------------------------------
    mcp = FastMCP(
        "TaskChampion MCP",
        instructions=_build_instructions(
    config,
    schema,
    tw_version,
    onboarding_required=onboarding_required,
),
    )

    # --- Register tools by role level ---------------------------------------
    if onboarding_required:
        _register_onboarding_tools(mcp, registry)
    else:
        _register_contributor_tools(mcp, registry)

        if Role.has_permission(config.role, Role.GENERATOR):
            _register_generator_tools(mcp, registry)

        if Role.has_permission(config.role, Role.MANAGER):
            _register_manager_tools(mcp, registry)

    logger.info(
        "Server ready. Role=%s, Schema=%s, TW=%s",
        config.role,
        schema.name,
        tw_version,
    )

    return mcp


# ---------------------------------------------------------------------------
# Tool registration
# ---------------------------------------------------------------------------


def _register_onboarding_tools(mcp: FastMCP, reg: ToolRegistry) -> None:
    """Register first-run onboarding tools."""

    @mcp.tool()
    def get_initialization_status(project_dir: str = "") -> str:
        """Inspect first-run onboarding state without mutating tasks or config.

        Use this before task creation/modification if the active schema may be
        the bundled minimal default rather than a user-specific taxonomy.
        """
        return json.dumps(
            onboarding_get_initialization_status(
                config=reg.config,
                task_cli=reg.task,
                timew_cli=reg.timew,
                project_dir=project_dir or None,
            )
        )

    @mcp.tool()
    def propose_initialization_options(project_dir: str = "") -> str:
        """Return onboarding choices for the user/model to discuss.

        Options include using a taxonomy file, inferring from existing tasks,
        combining both, or selecting a bundled preset.
        """
        status = onboarding_get_initialization_status(
            config=reg.config,
            task_cli=reg.task,
            timew_cli=reg.timew,
            project_dir=project_dir or None,
        )
        return json.dumps(onboarding_propose_initialization_options(status))

    @mcp.tool()
    def analyze_existing_tasks_for_schema() -> str:
        """Analyse existing Taskwarrior tasks for field/schema inference.

        This is read-only. It returns field occurrence ratios, likely enum
        values, likely required fields, projects, tags, and detected UDAs.
        """
        return json.dumps(onboarding_analyse_existing_tasks(reg.task))

    @mcp.tool()
    def analyze_taxonomy_file(path: str) -> str:
        """Parse a taxonomy Markdown file and return extracted semantics.

        This is read-only. It extracts fields, descriptions, allowed values,
        conditional requirements, and phase transitions when possible.
        """
        return json.dumps(onboarding_analyze_taxonomy_file(path))

    @mcp.tool()
    def generate_initial_schema_preview(
        taxonomy_path: str = "",
        project_dir: str = "",
        schema_name: str = "",
    ) -> str:
        """Generate a reviewable schema TOML preview without writing files.

        The preview combines existing task analysis and, when available, a
        taxonomy Markdown file. The returned schema_toml should be reviewed by
        the user before calling save_initial_schema.
        """
        return json.dumps(
            onboarding_generate_schema_preview(
                config=reg.config,
                task_cli=reg.task,
                taxonomy_path=taxonomy_path or None,
                project_dir=project_dir or None,
                schema_name=schema_name or None,
            )
        )

    @mcp.tool()
    def save_initial_schema(
        schema_toml: str,
        taxonomy_path: str = "",
        output_path: str = "",
        role: str = "",
        overwrite: bool = False,
        update_config: bool = True,
    ) -> str:
        """Persist an approved generated schema and optionally update config.toml.

        This writes schema/config files but does not mutate Taskwarrior tasks.
        Call generate_initial_schema_preview first and show the user a summary
        before saving.

        ``role`` is the MCP permission level to persist in config.toml. Pass
        one of CONTRIBUTOR / GENERATOR / MANAGER (see propose_initialization_options
        for descriptions). When omitted, CONTRIBUTOR is persisted so the server
        leaves onboarding mode on next restart. Without persisting a role the
        server stays stuck on the onboarding tool surface.
        """
        return json.dumps(
            onboarding_save_initial_schema(
                schema_toml=schema_toml,
                taxonomy_path=taxonomy_path or None,
                output_path=output_path or None,
                role=role or None,
                overwrite=overwrite,
                update_config=update_config,
            )
        )

    @mcp.tool()
    def list_preset_schemas() -> str:
        """List bundled preset schemas (minimal, gtd, kanban, scrum, ...).

        Read-only. Returns each preset's name, file path, version and
        description as parsed from the schema's [meta] block. Use this
        before calling use_preset_schema so the user can see what is
        available without you guessing the preset names.
        """
        return json.dumps(onboarding_list_preset_schemas())

    @mcp.tool()
    def use_preset_schema(
        preset_name: str,
        taxonomy_path: str = "",
        output_path: str = "",
        role: str = "",
        copy: bool = False,
        overwrite: bool = False,
        update_config: bool = True,
    ) -> str:
        """Wire a bundled preset schema into the user's config.toml.

        By default this just sets ``schema = "<preset_name>"`` in config.toml
        (lowest friction; keeps using the version-controlled bundled file).
        Pass copy=true to copy the preset into output_path (or the user
        config dir) and reference that copy via schema_path — use this when
        the user wants a personal, editable copy.

        Refuses to overwrite an existing target file when copy=true unless
        overwrite=true.

        ``role`` is the MCP permission level to persist in config.toml. Pass
        one of CONTRIBUTOR / GENERATOR / MANAGER (see propose_initialization_options
        for descriptions). When omitted, CONTRIBUTOR is persisted so the server
        leaves onboarding mode on next restart. Without persisting a role the
        server stays stuck on the onboarding tool surface.
        """
        return json.dumps(
            onboarding_use_preset_schema(
                preset_name=preset_name,
                taxonomy_path=taxonomy_path or None,
                output_path=output_path or None,
                role=role or None,
                copy=copy,
                overwrite=overwrite,
                update_config=update_config,
            )
        )


def _register_contributor_tools(mcp: FastMCP, reg: ToolRegistry) -> None:
    """Register CONTRIBUTOR-level tools (read + annotate + modify)."""

    @mcp.tool()
    def list_tasks(
        filters: str = "",
    ) -> str:
        """List and filter Taskwarrior tasks.

        Returns tasks as JSON. Use Taskwarrior filter syntax:
        - 'status:pending' — pending tasks
        - 'project:work' — tasks in project 'work'
        - 'phase:impl' — tasks in implementation phase
        - '+python' — tasks tagged 'python'
        Combine filters: 'status:pending project:work phase:impl'
        """
        return json.dumps(reg.list_tasks(filters))

    @mcp.tool()
    def get_task(uuid: str) -> str:
        """Get a single task by its UUID.

        Returns full task details including all fields and annotations.
        Always use UUID (not local ID) for reliable identification.
        """
        return json.dumps(reg.get_task(uuid))

    @mcp.tool()
    def search_tasks(
        query: str,
        field: str = "description",
    ) -> str:
        """Search tasks by a specific field.

        Args:
            query: The search term.
            field: Field to search in. Options: 'description',
                   'project', 'tags', or any UDA name.
        """
        return json.dumps(reg.search_tasks(query, field))

    @mcp.tool()
    def annotate_task(uuid: str, annotation: str, dry_run: bool | None = None) -> str:
        """Add an annotation (note, link, or context) to a task.

        Annotations are the preferred way to add narrative context,
        rationale, and reference links to tasks.
        """
        return json.dumps(reg.annotate_task(uuid, annotation, dry_run))

    @mcp.tool()
    def modify_task(
        uuid: str,
        fields: dict[str, str | list[str]],
        dry_run: bool | None = None,
    ) -> str:
        """Modify fields on an existing task.

        Args:
            uuid: Task UUID.
            fields: Field:value pairs to modify.
                    Example: {"priority": "H", "phase": "impl"}
                    For adding tags: {"tags_add": ["python"]}
                    For removing tags: {"tags_remove": ["old"]}
        """
        return json.dumps(reg.modify_task(uuid, fields, dry_run))

    @mcp.tool()
    def start_task(uuid: str, dry_run: bool | None = None) -> str:
        """Start working on a task.

        If Timewarrior hook is installed, this also starts
        time tracking with the task's tags.
        """
        return json.dumps(reg.start_task(uuid, dry_run))

    @mcp.tool()
    def stop_task(uuid: str, dry_run: bool | None = None) -> str:
        """Stop working on a task.

        If Timewarrior hook is installed, this also stops
        time tracking for the task.
        """
        return json.dumps(reg.stop_task(uuid, dry_run))

    @mcp.tool()
    def get_projects() -> str:
        """List all project names in the Taskwarrior database."""
        return json.dumps(reg.get_projects())

    @mcp.tool()
    def get_tags() -> str:
        """List all tags used in the Taskwarrior database."""
        return json.dumps(reg.get_tags())

    @mcp.tool()
    def get_active_context() -> str:
        """Show the currently active Taskwarrior context filter."""
        return json.dumps(reg.get_active_context())

    @mcp.tool()
    def get_schema_info() -> str:
        """Get the active task schema definition.

        Returns field definitions, required fields, allowed values,
        and conditional requirements. Use this to understand what
        fields are available before creating or modifying tasks.
        """
        return json.dumps(reg.get_schema_info())

    if reg.timew:

        @mcp.tool()
        def get_time_summary(period: str = ":day") -> str:
            """Get Timewarrior time tracking summary.

            Args:
                period: Time period — ':day', ':week', ':month',
                        or a date range like '2026-05-01 - 2026-05-25'.
            """
            return json.dumps(reg.timew_summary(period))

        @mcp.tool()
        def get_time_status() -> str:
            """Check if Timewarrior is currently tracking time."""
            return json.dumps(reg.timew_status())

    # -----------------------------------------------------------------------
    # Post-onboarding reconfiguration (ADR 17)
    #
    # Schema / taxonomy mutation: allowed at any role (changes the lens,
    # not the capabilities).  Role change: downgrade only — self-elevation
    # is forbidden by design.  All three audit-log every successful and
    # every failed call so the trail of LLM-driven config mutations is
    # queryable.  See ADR 17 for the threat model.
    # -----------------------------------------------------------------------

    def _audit_reconfigure(tool_name: str, params: dict, result: dict) -> None:
        """Emit one audit-log entry per reconfigure call (success or error)."""
        ok = bool(result.get("success"))
        summary_keys = (
            "previous_role",
            "new_role",
            "schema_name",
            "schema_path",
            "taxonomy_path",
            "error_code",
        )
        summary = {k: result.get(k) for k in summary_keys if k in result}
        reg.audit.log(
            tool_name=tool_name,
            parameters=params,
            result=json.dumps(summary, default=str),
            result_code=result.get("code"),
            success=ok,
            error=None if ok else (result.get("message") or "unknown error"),
        )

    @mcp.tool()
    def set_active_schema(
        schema_name: str = "",
        schema_path: str = "",
    ) -> str:
        """Switch the active task schema.

        Exactly one of ``schema_name`` (a bundled preset such as
        'minimal' / 'gtd' / 'kanban' / 'scrum') or ``schema_path``
        (an absolute path to a custom TOML schema) must be provided.

        Updates config.toml; takes effect on next MCP server restart
        (runtime reload is not yet implemented). Does not mutate any
        Taskwarrior tasks. Available at CONTRIBUTOR level and above —
        switching the validation lens is a horizontal move, not a
        privilege change (ADR 17).
        """
        params = {
            "schema_name": schema_name or None,
            "schema_path": schema_path or None,
        }
        result = onboarding_reconfigure_active_schema(
            schema_name=schema_name or None,
            schema_path=schema_path or None,
        )
        _audit_reconfigure("set_active_schema", params, result)
        return json.dumps(result)

    @mcp.tool()
    def set_taxonomy_path(path: str) -> str:
        """Update the taxonomy file path persisted in config.toml.

        The taxonomy informs the model's interpretation of task
        semantics. The target path must exist and be a regular file;
        the tool refuses non-existent or directory targets to prevent
        silently disabling taxonomy awareness.

        Takes effect on next MCP server restart. Available at
        CONTRIBUTOR level (informational input, not a capability).
        """
        params = {"path": path}
        result = onboarding_reconfigure_taxonomy_path(path)
        _audit_reconfigure("set_taxonomy_path", params, result)
        return json.dumps(result)

    @mcp.tool()
    def set_role(target_role: str) -> str:
        """Change the persisted MCP role — DOWNGRADE ONLY.

        Valid roles: CONTRIBUTOR, GENERATOR, MANAGER (cumulative;
        see ADR 5). This tool will set the persisted role to
        ``target_role`` IF AND ONLY IF its level is less than or
        equal to the currently-loaded role.

        Self-elevation via MCP is forbidden by design (ADR 17).
        Attempts to elevate return a structured error with
        error_code='role_elevation_forbidden'. To elevate, run
        './dev.sh init --role <ROLE>' from a shell or hand-edit
        ~/.config/taskchampion-mcp/config.toml and restart the
        MCP server.

        Takes effect on next MCP server restart.
        """
        params = {"target_role": target_role, "current_role": reg.config.role}
        result = onboarding_reconfigure_role(
            current_role=reg.config.role,
            target_role=target_role,
        )
        _audit_reconfigure("set_role", params, result)
        return json.dumps(result)


def _register_generator_tools(mcp: FastMCP, reg: ToolRegistry) -> None:
    """Register GENERATOR-level tools (create)."""

    @mcp.tool()
    def create_task(
        description: str,
        project: str = "",
        priority: str = "",
        tags: list[str] | None = None,
        due: str = "",
        extra_fields: dict[str, str] | None = None,
        dry_run: bool | None = None,
    ) -> str:
        """Create a new Taskwarrior task with schema validation.

        Args:
            description: Task description (imperative, actionable).
            project: Project name in dot-notation (e.g. 'work.acme').
            priority: H, M, or L.
            tags: List of tags (e.g. ["python", "docker"]).
            due: Due date (ISO format or Taskwarrior relative like 'eow').
            extra_fields: Additional UDA fields.
                Example: {"scope": "personal", "phase": "impl"}

        Call get_schema_info first to see required and available fields.
        """
        tag_list = [t.strip() for t in tags if t and t.strip()] if tags else None
        udas: dict[str, str] = dict(extra_fields or {})
        return json.dumps(
            reg.create_task(
                description=description,
                project=project,
                priority=priority,
                tags=tag_list,
                due=due,
                dry_run=dry_run,
                **udas,
            )
        )

    @mcp.tool()
    def create_subtask(
        parent_uuid: str,
        description: str,
        project: str = "",
        priority: str = "",
        tags: str = "",
        due: str = "",
        extra_fields: str = "",
        dry_run: bool | None = None,
    ) -> str:
        """Create a subtask with depends: linking to a parent task.

        Args:
            parent_uuid: UUID of the parent task this subtask depends on.
            description: Task description (imperative, actionable).
            project: Project name in dot-notation (e.g. 'work.acme').
            priority: H, M, or L.
            tags: Comma-separated tags (e.g. 'python,docker').
            due: Due date (ISO format or Taskwarrior relative like 'eow').
            extra_fields: JSON object of additional UDA fields.
                Example: '{"scope": "personal", "phase": "impl"}'

        The subtask will have a 'depends' field set to the parent UUID.
        Call get_schema_info first to see required and available fields.
        """
        tag_list = [t.strip() for t in tags.split(",") if t.strip()] if tags else None
        udas: dict[str, str] = {}
        if extra_fields:
            udas = json.loads(extra_fields)
        return json.dumps(
            reg.create_subtask(
                parent_uuid=parent_uuid,
                description=description,
                project=project,
                priority=priority,
                tags=tag_list,
                due=due,
                dry_run=dry_run,
                **udas,
            )
        )


def _register_manager_tools(mcp: FastMCP, reg: ToolRegistry) -> None:
    """Register MANAGER-level tools (lifecycle control)."""

    @mcp.tool()
    def complete_task(
        uuid: str,
        dry_run: bool | None = None,
        confirm_token: str = "",
    ) -> str:
        """Mark a task as done (completed).

        Args:
            uuid: Task UUID.
            dry_run: If true, preview the action without executing.

        Destructive operation — may require confirmation depending
        on server configuration.
        """
        return json.dumps(reg.complete_task(uuid, dry_run, confirm_token))

    @mcp.tool()
    def delete_task(
        uuid: str,
        dry_run: bool | None = None,
        confirm_token: str = "",
    ) -> str:
        """Delete a task from Taskwarrior.

        Args:
            uuid: Task UUID.
            dry_run: If true, preview the action without executing.

        Destructive operation — may require confirmation depending
        on server configuration. Prefer completing over deleting.
        """
        return json.dumps(reg.delete_task(uuid, dry_run, confirm_token))

    @mcp.tool()
    def undo_last_action(dry_run: bool | None = None, confirm_token: str = "") -> str:
        """Undo the last Taskwarrior operation.

        Reverts the most recent change. Use with caution.
        """
        return json.dumps(reg.undo(dry_run=dry_run, confirm_token=confirm_token))

    @mcp.tool()
    def sync_tasks(dry_run: bool | None = None) -> str:
        """Trigger task sync with the TaskChampion sync server.

        Pushes local changes and pulls remote changes.
        """
        return json.dumps(reg.sync(dry_run=dry_run))


# ---------------------------------------------------------------------------
# Instructions for LLM
# ---------------------------------------------------------------------------


def _build_instructions(
    config: ServerConfig,
    schema: TaskSchema,
    tw_version: str | None,
    *,
    onboarding_required: bool,
) -> str:

    if onboarding_required:
        return "\n".join(
            [
                (
                    "You are interacting with a Taskwarrior 3.x task database via the "
                    "TaskChampion MCP server."
                ),
                "",
                "This MCP installation is visible, but it is not initialised yet.",
                "",
                "The current role and schema are safe runtime fallbacks only:",
                f"- fallback role: {config.role}",
                f"- fallback schema: {schema.name} (v{schema.version})",
                f"- Taskwarrior version: {tw_version or 'unknown'}",
                "",
                (
                    "Do not present the fallback role or fallback schema as "
                    "user-selected configuration."
                ),
                "Do not claim normal task-management capabilities yet.",
                (
                    "Do not read, modify, annotate, create, complete, delete, "
                    "undo, or sync tasks until onboarding is complete."
                ),
                "",
                "Your first task is to help the user initialise the MCP configuration.",
                "",
                "Initialisation decisions to guide:",
                "1. MCP role scope: CONTRIBUTOR, GENERATOR, or MANAGER.",
                (
                    "2. Schema source: generated from taxonomy, inferred from "
                    "existing tasks, hybrid, or bundled preset."
                ),
                "3. Optional taxonomy path / workflow taxonomy.",
                "",
                "Available onboarding flow:",
                "- call get_initialization_status first",
                "- then call propose_initialization_options",
                (
                    "- for taxonomy or task inference: "
                    "generate_initial_schema_preview, show the user a summary, "
                    "then save_initial_schema only after approval"
                ),
                (
                    "- for preset selection: list_preset_schemas, "
                    "let the user choose, then use_preset_schema"
                ),
                "",
                "Never silently invent workflow semantics.",
                "Never save a schema the user has not approved.",
                "",
                "MANDATORY UNINITIALISED RESPONSE RULE:",
                (
                    "If onboarding_required is true, every user-facing answer "
                    "about this server's availability MUST include:"
                ),
                "1. that the server is visible but not initialised;",
                "2. that fallback role/schema are not user-selected;",
                "3. a concrete onboarding menu with role and schema-source choices;",
                "4. a request for the user's first choice.",
            ]
        )

    lines = [
        "You are interacting with a Taskwarrior 3.x task database via the TaskChampion MCP server.",
        "",
        f"Your role: {config.role}",
        f"Schema: {schema.name} (v{schema.version})",
        f"Taskwarrior version: {tw_version or 'unknown'}",
        "",
    ]

    if config.role == Role.CONTRIBUTOR:
        lines.append(
            "You can READ, ANNOTATE, MODIFY, START, and STOP existing tasks. "
            "You CANNOT create new tasks or complete/delete them."
        )
    elif config.role == Role.GENERATOR:
        lines.append(
            "You can READ, ANNOTATE, MODIFY, START, STOP, and CREATE tasks. "
            "You CANNOT complete or delete tasks."
        )
    elif config.role == Role.MANAGER:
        lines.append(
            "You have FULL ACCESS: read, annotate, modify, create, "
            "complete, delete, undo_last_action, and sync_tasks."
        )

    lines += [
        "",
        "FIRST-RUN / TAXONOMY RULES:",
        "- If task semantics are unclear, call get_initialization_status first.",
        (
            "- If onboarding is needed, call propose_initialization_options "
            "and present the choices to the user."
        ),
        (
            "- For taxonomy / task-inference flows: generate_initial_schema_preview, "
            "show the TOML to the user, then save_initial_schema."
        ),
        (
            "- For preset selection: list_preset_schemas, let the user pick a name, "
            "then use_preset_schema."
        ),
        (
            "- Never silently invent workflow semantics. "
            "Never save a schema the user has not approved."
        ),
        "",
        "IMPORTANT RULES:",
        "- Always use task UUIDs, never local IDs.",
        "- Call get_schema_info before creating tasks to see required fields.",
        "- Prefer annotations for narrative context.",
        "- Do not modify gen_model/gen_persona/gen_harness on existing tasks.",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """CLI entry point for taskchampion-mcp-server."""
    _configure_logging()
    parser = _build_parser()
    args = parser.parse_args()

    cli_overrides: dict[str, tuple[Any, str]] = {}
    if args.role:
        cli_overrides["server.role"] = (args.role, "cli:--role")
    if args.schema:
        cli_overrides["server.schema"] = (args.schema, "cli:--schema")

    config_path = Path(args.config).expanduser() if args.config else None
    cfg, sources = load_config_with_sources(
        path=config_path,
        cwd=Path.cwd(),
        cli_overrides=cli_overrides,
    )

    if args.config_dump:
        print(json.dumps(dump_effective_config(cfg, sources), indent=2, sort_keys=True))
        return

    mcp = create_server(config=cfg, config_path=config_path)
    mcp.run(transport="stdio")


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="TaskChampion MCP server")
    parser.add_argument(
        "--config",
        default="",
        help="Path to user config TOML (defaults to XDG path).",
    )
    parser.add_argument(
        "--role",
        choices=Role._HIERARCHY,
        help="Override effective role for this process.",
    )
    parser.add_argument(
        "--schema",
        default="",
        help="Override effective schema name for this process.",
    )
    parser.add_argument(
        "--config-dump",
        action="store_true",
        help="Print effective config with provenance as JSON and exit.",
    )
    return parser


if __name__ == "__main__":
    main()
