# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25

"""TaskChampion MCP Server — entry point.

Registers MCP tools based on the configured role level (ADR 5)
and starts the stdio transport (ADR 3).
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

from mcp.server.fastmcp import FastMCP

from taskchampion_mcp.audit import AuditLogger
from taskchampion_mcp.cli import TaskwarriorCLI, TimewarriorCLI
from taskchampion_mcp.config import Role, ServerConfig, load_config
from taskchampion_mcp.onboarding import (
    analyse_existing_tasks as onboarding_analyse_existing_tasks,
    analyse_taxonomy_file as onboarding_analyse_taxonomy_file,
    generate_schema_preview as onboarding_generate_schema_preview,
    get_initialisation_status as onboarding_get_initialisation_status,
    propose_initialisation_options as onboarding_propose_initialisation_options,
    save_initial_schema as onboarding_save_initial_schema,
)
from taskchampion_mcp.rate_limiter import RateLimiter
from taskchampion_mcp.schema import TaskSchema, load_schema
from taskchampion_mcp.tools import ToolRegistry

logger = logging.getLogger("taskchampion_mcp")


# ---------------------------------------------------------------------------
# Server factory
# ---------------------------------------------------------------------------


def create_server(
    config: ServerConfig | None = None,
    config_path: Path | None = None,
) -> FastMCP:
    """Build and configure the MCP server with role-appropriate tools."""

    if config is None:
        config = load_config(config_path)

    # --- Detect tools -------------------------------------------------------
    task_cli = TaskwarriorCLI(
        binary=config.task_binary,
        override_rc=config.taskwarrior_override_rc,
    )
    tw_version = task_cli.version()
    if tw_version is None:
        logger.error(
            "Taskwarrior not found on PATH (%s). "
            "Install Taskwarrior 3.x and ensure 'task' is available.",
            config.task_binary,
        )
        sys.exit(1)

    major = tw_version.split(".")[0] if tw_version else "0"
    if major == "2":
        logger.warning(
            "Taskwarrior 2.x detected (%s). This MCP targets 3.x. "
            "Some features may not work correctly.",
            tw_version,
        )
    elif major not in ("3",):
        logger.warning("Unexpected Taskwarrior version: %s", tw_version)

    timew_cli: TimewarriorCLI | None = None
    timew_instance = TimewarriorCLI(binary=config.timew_binary)
    if timew_instance.available():
        timew_cli = timew_instance
        logger.info(
            "Timewarrior detected: %s",
            timew_instance.version(),
        )
    else:
        logger.info("Timewarrior not found. Time tracking tools disabled.")

    # --- Load schema --------------------------------------------------------
    schema: TaskSchema
    if config.schema_path:
        schema = load_schema(config.schema_path)
    else:
        schema = load_schema(config.schema_name)
    logger.info("Schema loaded: %s v%s", schema.name, schema.version)

    # --- Build shared state -------------------------------------------------
    rate_limiter = RateLimiter(
        ops_per_minute=config.rate_limit_per_minute,
        ops_per_hour=config.rate_limit_per_hour,
        creates_per_hour=config.create_limit_per_hour,
    )

    audit = AuditLogger(config.audit_log_path)
    audit.log_startup(config.role, schema.name, tw_version)

    registry = ToolRegistry(
        config=config,
        task_cli=task_cli,
        timew_cli=timew_cli,
        schema=schema,
        rate_limiter=rate_limiter,
        audit=audit,
    )

    # --- Create FastMCP server ----------------------------------------------
    mcp = FastMCP(
        "TaskChampion MCP",
        instructions=_build_instructions(config, schema, tw_version),
    )

    # --- Register tools by role level ---------------------------------------
    _register_contributor_tools(mcp, registry)

    if Role.has_permission(config.role, Role.GENERATOR):
        _register_generator_tools(mcp, registry)

    if Role.has_permission(config.role, Role.MANAGER):
        _register_manager_tools(mcp, registry)

    logger.info(
        "Server ready. Role=%s, Schema=%s, TW=%s",
        config.role,
        schema.name,
        tw_version,
    )

    return mcp


# ---------------------------------------------------------------------------
# Tool registration
# ---------------------------------------------------------------------------


def _register_contributor_tools(mcp: FastMCP, reg: ToolRegistry) -> None:
    """Register CONTRIBUTOR-level tools (read + annotate + modify)."""

    @mcp.tool()
    def get_initialisation_status(project_dir: str = "") -> str:
        """Inspect first-run onboarding state without mutating tasks or config.

        Use this before task creation/modification if the active schema may be
        the bundled minimal default rather than a user-specific taxonomy.
        """
        return json.dumps(
            onboarding_get_initialisation_status(
                config=reg.config,
                task_cli=reg.task,
                timew_cli=reg.timew,
                project_dir=project_dir or None,
            )
        )

    @mcp.tool()
    def propose_initialisation_options(project_dir: str = "") -> str:
        """Return onboarding choices for the user/model to discuss.

        Options include using a taxonomy file, inferring from existing tasks,
        combining both, or selecting a bundled preset.
        """
        status = onboarding_get_initialisation_status(
            config=reg.config,
            task_cli=reg.task,
            timew_cli=reg.timew,
            project_dir=project_dir or None,
        )
        return json.dumps(onboarding_propose_initialisation_options(status))

    @mcp.tool()
    def analyse_existing_tasks_for_schema() -> str:
        """Analyse existing Taskwarrior tasks for field/schema inference.

        This is read-only. It returns field occurrence ratios, likely enum
        values, likely required fields, projects, tags, and detected UDAs.
        """
        return json.dumps(onboarding_analyse_existing_tasks(reg.task))

    @mcp.tool()
    def analyse_taxonomy_file(path: str) -> str:
        """Parse a taxonomy Markdown file and return extracted semantics.

        This is read-only. It extracts fields, descriptions, allowed values,
        conditional requirements, and phase transitions when possible.
        """
        return json.dumps(onboarding_analyse_taxonomy_file(path))

    @mcp.tool()
    def generate_initial_schema_preview(
        taxonomy_path: str = "",
        project_dir: str = "",
        schema_name: str = "auto_generated",
    ) -> str:
        """Generate a reviewable schema TOML preview without writing files.

        The preview combines existing task analysis and, when available, a
        taxonomy Markdown file. The returned schema_toml should be reviewed by
        the user before calling save_initial_schema.
        """
        return json.dumps(
            onboarding_generate_schema_preview(
                config=reg.config,
                task_cli=reg.task,
                taxonomy_path=taxonomy_path or None,
                project_dir=project_dir or None,
                schema_name=schema_name or "auto_generated",
            )
        )

    @mcp.tool()
    def save_initial_schema(
        schema_toml: str,
        taxonomy_path: str = "",
        output_path: str = "",
        overwrite: bool = False,
        update_config: bool = True,
    ) -> str:
        """Persist an approved generated schema and optionally update config.toml.

        This writes schema/config files but does not mutate Taskwarrior tasks.
        Call generate_initial_schema_preview first and show the user a summary
        before saving.
        """
        return json.dumps(
            onboarding_save_initial_schema(
                schema_toml=schema_toml,
                taxonomy_path=taxonomy_path or None,
                output_path=output_path or None,
                overwrite=overwrite,
                update_config=update_config,
            )
        )

    @mcp.tool()
    def list_tasks(
        filters: str = "",
    ) -> str:
        """List and filter Taskwarrior tasks.

        Returns tasks as JSON. Use Taskwarrior filter syntax:
        - 'status:pending' — pending tasks
        - 'project:work' — tasks in project 'work'
        - 'phase:impl' — tasks in implementation phase
        - '+python' — tasks tagged 'python'
        Combine filters: 'status:pending project:work phase:impl'
        """
        return json.dumps(reg.list_tasks(filters))

    @mcp.tool()
    def get_task(uuid: str) -> str:
        """Get a single task by its UUID.

        Returns full task details including all fields and annotations.
        Always use UUID (not local ID) for reliable identification.
        """
        return json.dumps(reg.get_task(uuid))

    @mcp.tool()
    def search_tasks(
        query: str,
        field: str = "description",
    ) -> str:
        """Search tasks by a specific field.

        Args:
            query: The search term.
            field: Field to search in. Options: 'description',
                   'project', 'tags', or any UDA name.
        """
        return json.dumps(reg.search_tasks(query, field))

    @mcp.tool()
    def annotate_task(uuid: str, annotation: str) -> str:
        """Add an annotation (note, link, or context) to a task.

        Annotations are the preferred way to add narrative context,
        rationale, and reference links to tasks.
        """
        return json.dumps(reg.annotate_task(uuid, annotation))

    @mcp.tool()
    def modify_task(uuid: str, fields: str) -> str:
        """Modify fields on an existing task.

        Args:
            uuid: Task UUID.
            fields: JSON object of field:value pairs to modify.
                    Example: '{"priority": "H", "phase": "impl"}'
                    For adding tags: '{"tags_add": ["python"]}'
                    For removing tags: '{"tags_remove": ["old"]}'
        """
        parsed = json.loads(fields)
        return json.dumps(reg.modify_task(uuid, parsed))

    @mcp.tool()
    def start_task(uuid: str) -> str:
        """Start working on a task.

        If Timewarrior hook is installed, this also starts
        time tracking with the task's tags.
        """
        return json.dumps(reg.start_task(uuid))

    @mcp.tool()
    def stop_task(uuid: str) -> str:
        """Stop working on a task.

        If Timewarrior hook is installed, this also stops
        time tracking for the task.
        """
        return json.dumps(reg.stop_task(uuid))

    @mcp.tool()
    def get_projects() -> str:
        """List all project names in the Taskwarrior database."""
        return json.dumps(reg.get_projects())

    @mcp.tool()
    def get_tags() -> str:
        """List all tags used in the Taskwarrior database."""
        return json.dumps(reg.get_tags())

    @mcp.tool()
    def get_active_context() -> str:
        """Show the currently active Taskwarrior context filter."""
        return json.dumps(reg.get_active_context())

    @mcp.tool()
    def get_schema_info() -> str:
        """Get the active task schema definition.

        Returns field definitions, required fields, allowed values,
        and conditional requirements. Use this to understand what
        fields are available before creating or modifying tasks.
        """
        return json.dumps(reg.get_schema_info())

    if reg.timew:

        @mcp.tool()
        def timew_summary(period: str = ":day") -> str:
            """Get Timewarrior time tracking summary.

            Args:
                period: Time period — ':day', ':week', ':month',
                        or a date range like '2026-05-01 - 2026-05-25'.
            """
            return json.dumps(reg.timew_summary(period))

        @mcp.tool()
        def timew_status() -> str:
            """Check if Timewarrior is currently tracking time."""
            return json.dumps(reg.timew_status())


def _register_generator_tools(mcp: FastMCP, reg: ToolRegistry) -> None:
    """Register GENERATOR-level tools (create)."""

    @mcp.tool()
    def create_task(
        description: str,
        project: str = "",
        priority: str = "",
        tags: str = "",
        due: str = "",
        extra_fields: str = "",
    ) -> str:
        """Create a new Taskwarrior task with schema validation.

        Args:
            description: Task description (imperative, actionable).
            project: Project name in dot-notation (e.g. 'work.acme').
            priority: H, M, or L.
            tags: Comma-separated tags (e.g. 'python,docker').
            due: Due date (ISO format or Taskwarrior relative like 'eow').
            extra_fields: JSON object of additional UDA fields.
                Example: '{"scope": "personal", "phase": "impl"}'

        Call get_schema_info first to see required and available fields.
        """
        tag_list = [t.strip() for t in tags.split(",") if t.strip()] if tags else None
        udas: dict[str, str] = {}
        if extra_fields:
            udas = json.loads(extra_fields)
        return json.dumps(
            reg.create_task(
                description=description,
                project=project,
                priority=priority,
                tags=tag_list,
                due=due,
                **udas,
            )
        )


def _register_manager_tools(mcp: FastMCP, reg: ToolRegistry) -> None:
    """Register MANAGER-level tools (lifecycle control)."""

    @mcp.tool()
    def complete_task(uuid: str, dry_run: bool = False) -> str:
        """Mark a task as done (completed).

        Args:
            uuid: Task UUID.
            dry_run: If true, preview the action without executing.

        Destructive operation — may require confirmation depending
        on server configuration.
        """
        return json.dumps(reg.complete_task(uuid, dry_run))

    @mcp.tool()
    def delete_task(uuid: str, dry_run: bool = False) -> str:
        """Delete a task from Taskwarrior.

        Args:
            uuid: Task UUID.
            dry_run: If true, preview the action without executing.

        Destructive operation — may require confirmation depending
        on server configuration. Prefer completing over deleting.
        """
        return json.dumps(reg.delete_task(uuid, dry_run))

    @mcp.tool()
    def undo() -> str:
        """Undo the last Taskwarrior operation.

        Reverts the most recent change. Use with caution.
        """
        return json.dumps(reg.undo())

    @mcp.tool()
    def sync() -> str:
        """Trigger task sync with the TaskChampion sync server.

        Pushes local changes and pulls remote changes.
        """
        return json.dumps(reg.sync())


# ---------------------------------------------------------------------------
# Instructions for LLM
# ---------------------------------------------------------------------------


def _build_instructions(
    config: ServerConfig,
    schema: TaskSchema,
    tw_version: str | None,
) -> str:
    lines = [
        "You are interacting with a Taskwarrior 3.x task database via the TaskChampion MCP server.",
        "",
        f"Your role: {config.role}",
        f"Schema: {schema.name} (v{schema.version})",
        f"Taskwarrior version: {tw_version or 'unknown'}",
        "",
    ]

    if config.role == Role.CONTRIBUTOR:
        lines.append(
            "You can READ, ANNOTATE, and MODIFY existing tasks. "
            "You CANNOT create new tasks or complete/delete them."
        )
    elif config.role == Role.GENERATOR:
        lines.append(
            "You can READ, ANNOTATE, MODIFY, and CREATE tasks. You CANNOT complete or delete tasks."
        )
    elif config.role == Role.MANAGER:
        lines.append(
            "You have FULL ACCESS: read, annotate, modify, create, "
            "complete, delete, undo, and sync."
        )

    lines += [
        "",
        "FIRST-RUN / TAXONOMY RULES:",
        "- If task semantics are unclear, call get_initialisation_status first.",
        "- If no custom schema or taxonomy is configured, ask the user for a taxonomy file or offer schema inference from existing tasks.",
        "- Generate schema previews before saving; do not silently invent workflow semantics.",
        "",
        "IMPORTANT RULES:",
        "- Always use task UUIDs, never local IDs.",
        "- Call get_schema_info before creating tasks to see required fields.",
        "- Prefer annotations for narrative context.",
        "- Do not modify gen_model/gen_persona/gen_harness on existing tasks.",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """CLI entry point for taskchampion-mcp-server."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
        stream=sys.stderr,
    )
    mcp = create_server()
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
