# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25

"""MCP tool definitions for TaskChampion MCP server.

Tools are organized by role level (ADR 5):
  CONTRIBUTOR — read + annotate + modify
  GENERATOR   — + create
  MANAGER     — + lifecycle (done, delete, undo, sync)
"""

from __future__ import annotations

import re
import time
from typing import Any

from taskchampion_mcp.audit import AuditLogger
from taskchampion_mcp.cli import TaskwarriorCLI, TimewarriorCLI
from taskchampion_mcp.config import ServerConfig
from taskchampion_mcp.rate_limiter import RateLimiter, RateLimitError
from taskchampion_mcp.sanitizer import (
    SanitizationError,
    sanitize_annotation,
    sanitize_description,
    sanitize_enum,
    sanitize_field_value,
    sanitize_filter_expression,
    sanitize_project,
    sanitize_tag,
    sanitize_uuid,
)
from taskchampion_mcp.schema import TaskSchema, validate_task

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SUCCESS_CODES = {"ok", "dry_run", "confirmation_required"}
_ERROR_CODES = {
    "validation_error",
    "not_found",
    "rate_limit",
    "cli_error",
    "schema_unset",
    "role_insufficient",
    "confirmation_required",
    "dry_run",
    "internal_error",
}
_REPORT_NAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def _validate_code(code: str, allowed: set[str]) -> str:
    if code not in allowed:
        raise ValueError(f"Invalid result code '{code}'. Must be one of: {sorted(allowed)}")
    return code


def _redact_fields(task: dict[str, Any], redacted: list[str]) -> dict[str, Any]:
    """Remove sensitive fields from a task dict before returning to LLM."""
    if not redacted:
        return task
    return {k: v for k, v in task.items() if k not in redacted}


def _redact_list(tasks: list[dict[str, Any]], redacted: list[str]) -> list[dict[str, Any]]:
    return [_redact_fields(t, redacted) for t in tasks]


def _make_error(msg: str) -> dict[str, Any]:
    return {"error": True, "message": msg, "code": _validate_code("internal_error", _ERROR_CODES)}


def _make_success(msg: str, code: str = "ok", **extra: Any) -> dict[str, Any]:
    result: dict[str, Any] = {
        "success": True,
        "message": msg,
        "code": _validate_code(code, _SUCCESS_CODES),
    }
    result.update(extra)
    return result


def _make_coded_error(
    msg: str,
    code: str,
    *,
    details: dict[str, Any] | None = None,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "error": True,
        "message": msg,
        "code": _validate_code(code, _ERROR_CODES),
    }
    if details:
        result["details"] = details
    return result


def _error_from_known_exception(exc: Exception) -> dict[str, Any]:
    if isinstance(exc, RateLimitError):
        return _make_coded_error(
            str(exc),
            "rate_limit",
            details={
                "bucket": exc.bucket,
                "limit": exc.limit,
                "retry_after_s": exc.window_seconds,
            },
        )
    if isinstance(exc, SanitizationError):
        return _make_coded_error(str(exc), "validation_error")
    return _make_coded_error(str(exc), "internal_error")


def _result_code_from_exception(exc: Exception) -> str:
    if isinstance(exc, RateLimitError):
        return "rate_limit"
    if isinstance(exc, SanitizationError):
        return "validation_error"
    return "internal_error"


def _timed_call(fn, *args, **kwargs):
    """Call fn and return (result, duration_ms)."""
    t0 = time.monotonic()
    result = fn(*args, **kwargs)
    return result, (time.monotonic() - t0) * 1000


# ---------------------------------------------------------------------------
# Tool registry class
# ---------------------------------------------------------------------------


class ToolRegistry:
    """Holds references to shared state and provides MCP tool implementations.

    All mutable runtime state lives here so that ``reload()`` can refresh it
    in-place without re-registering tools (ADR 19).
    """

    def __init__(
        self,
        config: ServerConfig,
        task_cli: TaskwarriorCLI,
        timew_cli: TimewarriorCLI | None,
        schema: TaskSchema,
        rate_limiter: RateLimiter,
        audit: AuditLogger,
        config_path: Any | None = None,
    ) -> None:
        self.config = config
        self.task = task_cli
        self.timew = timew_cli
        self.schema = schema
        self.limiter = rate_limiter
        self.audit = audit
        self._config_path = config_path

    @property
    def initialized(self) -> bool:
        """True when both role and schema are explicitly configured."""
        return bool(
            self.config.explicit_role_configured and self.config.explicit_schema_configured
        )

    def reload(self) -> list[str]:
        """Re-read config from disk and refresh all internal state (ADR 19).

        Returns the list of subsystems that were successfully reloaded.
        Failures are logged but do not prevent other subsystems from reloading.
        """
        import logging

        from taskchampion_mcp.config import load_config
        from taskchampion_mcp.schema import load_schema

        _logger = logging.getLogger("taskchampion_mcp")
        reloaded: list[str] = []

        new_config = load_config(self._config_path)
        self.config = new_config
        reloaded.append("config")

        try:
            if new_config.schema_path:
                self.schema = load_schema(new_config.schema_path)
            else:
                self.schema = load_schema(new_config.schema_name)
            reloaded.append("schema")
        except Exception as exc:
            _logger.warning("Schema reload failed (keeping previous): %s", exc)

        self.limiter = RateLimiter(
            ops_per_minute=new_config.rate_limit_per_minute,
            ops_per_hour=new_config.rate_limit_per_hour,
            creates_per_hour=new_config.create_limit_per_hour,
        )
        reloaded.append("rate_limiter")

        from taskchampion_mcp.audit import AuditLogger as _AuditLogger

        self.audit = _AuditLogger(
            new_config.audit_log_path,
            redacted_fields=new_config.redacted_fields,
        )
        reloaded.append("audit")

        self.task = TaskwarriorCLI(
            binary=new_config.task_binary,
            override_rc=new_config.taskwarrior_override_rc,
        )
        reloaded.append("task_cli")

        timew_instance = TimewarriorCLI(binary=new_config.timew_binary)
        self.timew = timew_instance if timew_instance.available() else None
        reloaded.append("timew_cli")

        return reloaded

    def _guard_rate(self, *, is_create: bool = False) -> None:
        self.limiter.check_and_record(is_create=is_create)

    def _log(
        self,
        tool: str,
        params: dict,
        result_str: str,
        ok: bool,
        ms: float,
        err: str | None = None,
        result_code: str | None = None,
    ) -> None:
        self.audit.log(tool, params, result_str, result_code, ok, ms, err)

    def _effective_dry_run(self, dry_run: bool | None) -> bool:
        return dry_run if dry_run is not None else self.config.dry_run_default

    def _confirmation_token(self, action: str, subject: str = "") -> str:
        return f"{action}:{subject[:8]}" if subject else action

    # -----------------------------------------------------------------------
    # CONTRIBUTOR tools
    # -----------------------------------------------------------------------

    def list_tasks(self, filters: str = "") -> dict[str, Any]:
        """List/filter tasks via task export."""
        params = {"filters": filters}
        try:
            self._guard_rate()
            filter_parts = []
            if filters:
                sanitized = sanitize_filter_expression(filters)
                filter_parts = sanitized.split()
            tasks, ms = _timed_call(self.task.export_tasks, *filter_parts)
            tasks = _redact_list(tasks, self.config.redacted_fields)
            self._log("list_tasks", params, f"{len(tasks)} tasks", True, ms)
            return _make_success(f"Found {len(tasks)} tasks.", tasks=tasks, count=len(tasks))
        except (RateLimitError, SanitizationError) as e:
            self._log(
                "list_tasks",
                params,
                "",
                False,
                0,
                str(e),
                result_code=_result_code_from_exception(e),
            )
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("list_tasks", params, "", False, 0, str(e), result_code="internal_error")
            return _make_coded_error(f"Failed to list tasks: {e}", "internal_error")

    def get_task(self, uuid: str) -> dict[str, Any]:
        """Get a single task by UUID."""
        params = {"uuid": uuid}
        try:
            self._guard_rate()
            clean_uuid = sanitize_uuid(uuid)
            task_data, ms = _timed_call(self.task.get_task, clean_uuid)
            if not task_data:
                self._log("get_task", params, "not found", False, ms, result_code="not_found")
                return _make_coded_error(f"Task {clean_uuid} not found.", "not_found")
            task_data = _redact_fields(task_data, self.config.redacted_fields)
            self._log("get_task", params, "found", True, ms)
            return _make_success("Task found.", task=task_data)
        except (RateLimitError, SanitizationError) as e:
            self._log(
                "get_task",
                params,
                "",
                False,
                0,
                str(e),
                result_code=_result_code_from_exception(e),
            )
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("get_task", params, "", False, 0, str(e), result_code="internal_error")
            return _make_coded_error(f"Failed to get task: {e}", "internal_error")

    def search_tasks(self, query: str, field: str = "description") -> dict[str, Any]:
        """Search tasks by description, project, tags, or UDA values."""
        params = {"query": query, "field": field}
        try:
            self._guard_rate()
            sanitized_query = sanitize_filter_expression(query)
            if field == "description":
                filter_expr = f"description.contains:{sanitized_query}"
            elif field == "project":
                filter_expr = f"project:{sanitized_query}"
            elif field == "tags":
                filter_expr = f"+{sanitize_tag(sanitized_query)}"
            else:
                filter_expr = f"{field}:{sanitized_query}"
            tasks, ms = _timed_call(self.task.export_tasks, filter_expr)
            tasks = _redact_list(tasks, self.config.redacted_fields)
            self._log("search_tasks", params, f"{len(tasks)} results", True, ms)
            return _make_success(
                f"Found {len(tasks)} matching tasks.",
                tasks=tasks,
                count=len(tasks),
            )
        except (RateLimitError, SanitizationError) as e:
            self._log(
                "search_tasks",
                params,
                "",
                False,
                0,
                str(e),
                result_code=_result_code_from_exception(e),
            )
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("search_tasks", params, "", False, 0, str(e), result_code="internal_error")
            return _make_coded_error(f"Search failed: {e}", "internal_error")

    def annotate_task(
        self,
        uuid: str,
        annotation: str,
        dry_run: bool | None = None,
    ) -> dict[str, Any]:
        """Add an annotation to a task."""
        params = {"uuid": uuid, "annotation": annotation, "dry_run": dry_run}
        try:
            self._guard_rate()
            clean_uuid = sanitize_uuid(uuid)
            clean_annotation = sanitize_annotation(annotation)
            if self._effective_dry_run(dry_run):
                self._log("annotate_task", params, "dry_run", True, 0, result_code="dry_run")
                return _make_success(
                    f"DRY RUN: Would annotate task {clean_uuid}.",
                    code="dry_run",
                    dry_run=True,
                    preview={"uuid": clean_uuid, "annotation": clean_annotation},
                )
            result, ms = _timed_call(self.task.annotate_task, clean_uuid, clean_annotation)
            if result.ok:
                self._log("annotate_task", params, "ok", True, ms)
                return _make_success(f"Annotation added to task {clean_uuid}.")
            self._log("annotate_task", params, result.stderr, False, ms, result.stderr)
            return _make_coded_error(f"Failed to annotate task: {result.stderr}", "cli_error")
        except (RateLimitError, SanitizationError) as e:
            self._log("annotate_task", params, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("annotate_task", params, "", False, 0, str(e))
            return _make_coded_error(f"Annotation failed: {e}", "internal_error")

    def modify_task(
        self,
        uuid: str,
        fields: dict[str, str | list[str]],
        dry_run: bool | None = None,
    ) -> dict[str, Any]:
        """Modify fields on an existing task."""
        params = {"uuid": uuid, "fields": fields, "dry_run": dry_run}
        try:
            self._guard_rate()
            clean_uuid = sanitize_uuid(uuid)
            sanitized: dict[str, Any] = {}
            for key, value in fields.items():
                if key == "project":
                    sanitized[key] = sanitize_project(value)
                elif key in ("tags_add", "tags_remove"):
                    if isinstance(value, list):
                        sanitized[key] = [sanitize_tag(t) for t in value]
                    else:
                        sanitized[key] = sanitize_tag(value)
                elif key in self.schema.enum_fields():
                    sanitized[key] = sanitize_enum(value, key, self.schema.enum_fields()[key])
                else:
                    sanitized[key] = sanitize_field_value(value, key)
            if self._effective_dry_run(dry_run):
                self._log("modify_task", params, "dry_run", True, 0, result_code="dry_run")
                return _make_success(
                    f"DRY RUN: Would modify task {clean_uuid}.",
                    code="dry_run",
                    dry_run=True,
                    preview={"uuid": clean_uuid, "fields": sanitized},
                )
            result, ms = _timed_call(self.task.modify_task, clean_uuid, **sanitized)
            if result.ok:
                self._log("modify_task", params, "ok", True, ms)
                return _make_success(
                    f"Task {clean_uuid} modified.",
                    fields_modified=list(sanitized.keys()),
                )
            self._log("modify_task", params, result.stderr, False, ms, result.stderr)
            return _make_coded_error(f"Modify failed: {result.stderr}", "cli_error")
        except (RateLimitError, SanitizationError) as e:
            self._log("modify_task", params, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("modify_task", params, "", False, 0, str(e))
            return _make_coded_error(f"Modify failed: {e}", "internal_error")

    def start_task(self, uuid: str, dry_run: bool | None = None) -> dict[str, Any]:
        """Start working on a task (triggers Timewarrior via hook)."""
        params = {"uuid": uuid, "dry_run": dry_run}
        try:
            self._guard_rate()
            clean_uuid = sanitize_uuid(uuid)
            if self._effective_dry_run(dry_run):
                self._log("start_task", params, "dry_run", True, 0, result_code="dry_run")
                return _make_success(
                    f"DRY RUN: Would start task {clean_uuid}.",
                    code="dry_run",
                    dry_run=True,
                    preview={"uuid": clean_uuid},
                )
            result, ms = _timed_call(self.task.start_task, clean_uuid)
            if result.ok:
                self._log("start_task", params, "ok", True, ms)
                return _make_success(f"Task {clean_uuid} started.")
            self._log("start_task", params, result.stderr, False, ms, result.stderr)
            return _make_coded_error(f"Start failed: {result.stderr}", "cli_error")
        except (RateLimitError, SanitizationError) as e:
            self._log("start_task", params, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("start_task", params, "", False, 0, str(e))
            return _make_coded_error(f"Start failed: {e}", "internal_error")

    def stop_task(self, uuid: str, dry_run: bool | None = None) -> dict[str, Any]:
        """Stop working on a task."""
        params = {"uuid": uuid, "dry_run": dry_run}
        try:
            self._guard_rate()
            clean_uuid = sanitize_uuid(uuid)
            if self._effective_dry_run(dry_run):
                self._log("stop_task", params, "dry_run", True, 0, result_code="dry_run")
                return _make_success(
                    f"DRY RUN: Would stop task {clean_uuid}.",
                    code="dry_run",
                    dry_run=True,
                    preview={"uuid": clean_uuid},
                )
            result, ms = _timed_call(self.task.stop_task, clean_uuid)
            if result.ok:
                self._log("stop_task", params, "ok", True, ms)
                return _make_success(f"Task {clean_uuid} stopped.")
            self._log("stop_task", params, result.stderr, False, ms, result.stderr)
            return _make_coded_error(f"Stop failed: {result.stderr}", "cli_error")
        except (RateLimitError, SanitizationError) as e:
            self._log("stop_task", params, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("stop_task", params, "", False, 0, str(e))
            return _make_coded_error(f"Stop failed: {e}", "internal_error")

    def get_projects(self) -> dict[str, Any]:
        """List all Taskwarrior projects."""
        try:
            self._guard_rate()
            projects, ms = _timed_call(self.task.projects)
            self._log("get_projects", {}, f"{len(projects)} projects", True, ms)
            return _make_success(f"Found {len(projects)} projects.", projects=projects)
        except RateLimitError as e:
            self._log("get_projects", {}, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("get_projects", {}, "", False, 0, str(e))
            return _make_coded_error(f"Failed: {e}", "internal_error")

    def get_tags(self) -> dict[str, Any]:
        """List all Taskwarrior tags."""
        try:
            self._guard_rate()
            tags, ms = _timed_call(self.task.tags)
            self._log("get_tags", {}, f"{len(tags)} tags", True, ms)
            return _make_success(f"Found {len(tags)} tags.", tags=tags)
        except RateLimitError as e:
            self._log("get_tags", {}, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("get_tags", {}, "", False, 0, str(e))
            return _make_coded_error(f"Failed: {e}", "internal_error")

    def get_active_context(self) -> dict[str, Any]:
        """Show the current Taskwarrior context."""
        try:
            self._guard_rate()
            ctx, ms = _timed_call(self.task.context)
            self._log("get_active_context", {}, ctx or "none", True, ms)
            return _make_success("Context retrieved.", context=ctx or "none")
        except RateLimitError as e:
            self._log("get_active_context", {}, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("get_active_context", {}, "", False, 0, str(e))
            return _make_coded_error(f"Failed: {e}", "internal_error")

    def get_schema_info(self) -> dict[str, Any]:
        """Return the loaded schema definition for LLM context."""
        return _make_success(
            f"Schema '{self.schema.name}' loaded.",
            schema_name=self.schema.name,
            schema_version=self.schema.version,
            description=self.schema.description,
            fields=self.schema.field_context_for_llm(),
            required_fields=self.schema.required_field_names(),
            enum_fields=self.schema.enum_fields(),
        )

    def get_task_report(self, report_name: str, filters: str = "") -> dict[str, Any]:
        """Run a named Taskwarrior report."""
        params = {"report_name": report_name, "filters": filters}
        try:
            self._guard_rate()
            clean_report = report_name.strip()
            if not clean_report or not _REPORT_NAME_RE.match(clean_report):
                return _make_coded_error(
                    "Invalid report name. Use alphanumerics, '.', '_' or '-'.",
                    "validation_error",
                )

            filter_parts: list[str] = []
            if filters:
                filter_parts = sanitize_filter_expression(filters).split()
            result, ms = _timed_call(self.task.run_report, clean_report, *filter_parts)
            if result.ok:
                self._log("get_task_report", params, "ok", True, ms)
                return _make_success(
                    f"Report '{clean_report}' retrieved.",
                    report=result.stdout,
                    report_name=clean_report,
                )
            self._log("get_task_report", params, result.stderr, False, ms, result.stderr)
            return _make_coded_error(
                f"Failed to run report '{clean_report}': {result.stderr}",
                "cli_error",
            )
        except (RateLimitError, SanitizationError) as e:
            self._log(
                "get_task_report",
                params,
                "",
                False,
                0,
                str(e),
                result_code=_result_code_from_exception(e),
            )
            return _error_from_known_exception(e)
        except Exception as e:
            self._log(
                "get_task_report",
                params,
                "",
                False,
                0,
                str(e),
                result_code="internal_error",
            )
            return _make_coded_error(f"Failed to run report: {e}", "internal_error")

    def timew_summary(self, period: str = ":day") -> dict[str, Any]:
        """Get Timewarrior time summary."""
        params = {"period": period}
        if not self.timew:
            return _make_coded_error("Timewarrior is not available.", "cli_error")
        try:
            self._guard_rate()
            summary, ms = _timed_call(self.timew.summary, period)
            self._log("timew_summary", params, "ok", True, ms)
            return _make_success("Timewarrior summary.", summary=summary)
        except RateLimitError as e:
            self._log("timew_summary", params, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("timew_summary", params, "", False, 0, str(e))
            return _make_coded_error(f"Failed: {e}", "internal_error")

    def timew_status(self) -> dict[str, Any]:
        """Check if Timewarrior is currently tracking."""
        if not self.timew:
            return _make_coded_error("Timewarrior is not available.", "cli_error")
        try:
            self._guard_rate()
            status, ms = _timed_call(self.timew.status)
            self._log("timew_status", {}, "ok", True, ms)
            return _make_success("Timewarrior status.", **status)
        except RateLimitError as e:
            self._log("timew_status", {}, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("timew_status", {}, "", False, 0, str(e))
            return _make_coded_error(f"Failed: {e}", "internal_error")

    # -----------------------------------------------------------------------
    # GENERATOR tools
    # -----------------------------------------------------------------------

    def create_task(
        self,
        description: str,
        project: str = "",
        priority: str = "",
        tags: list[str] | None = None,
        due: str = "",
        dry_run: bool | None = None,
        **udas: str,
    ) -> dict[str, Any]:
        """Create a new task with schema validation."""
        params = {
            "description": description,
            "project": project,
            "priority": priority,
            "tags": tags,
            "dry_run": dry_run,
            **udas,
        }
        try:
            self._guard_rate(is_create=True)

            clean_desc = sanitize_description(description)
            task_data: dict[str, Any] = {"description": clean_desc}

            if project:
                task_data["project"] = sanitize_project(project)
            if priority:
                task_data["priority"] = sanitize_enum(priority, "priority", ["H", "M", "L"])
            if due:
                task_data["due"] = sanitize_field_value(due, "due")

            clean_tags: list[str] = []
            if tags:
                clean_tags = [sanitize_tag(t) for t in tags]
                task_data["tags"] = clean_tags

            for key, value in udas.items():
                if value:
                    if key in self.schema.enum_fields():
                        task_data[key] = sanitize_enum(value, key, self.schema.enum_fields()[key])
                    else:
                        task_data[key] = sanitize_field_value(value, key)

            validation_errors = validate_task(task_data, self.schema)
            if validation_errors:
                self._log(
                    "create_task",
                    params,
                    "validation failed",
                    False,
                    0,
                    "; ".join(validation_errors),
                    result_code="validation_error",
                )
                return _make_coded_error(
                    f"Schema validation failed: {'; '.join(validation_errors)}",
                    "validation_error",
                )

            cli_fields: dict[str, str] = {}
            for key, value in task_data.items():
                if key in ("description", "tags"):
                    continue
                cli_fields[key] = value
            if clean_tags:
                cli_fields["tags"] = clean_tags

            if self._effective_dry_run(dry_run):
                self._log("create_task", params, "dry_run", True, 0, result_code="dry_run")
                return _make_success(
                    f"DRY RUN: Would create task '{clean_desc}'.",
                    code="dry_run",
                    dry_run=True,
                    preview={"description": clean_desc, "fields": cli_fields},
                )

            result, ms = _timed_call(self.task.add_task, clean_desc, **cli_fields)
            if result.ok:
                self._log("create_task", params, result.stdout, True, ms)
                return _make_success(f"Task created. {result.stdout.strip()}")
            self._log("create_task", params, result.stderr, False, ms, result.stderr)
            return _make_coded_error(f"Create failed: {result.stderr}", "cli_error")
        except (RateLimitError, SanitizationError) as e:
            self._log("create_task", params, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("create_task", params, "", False, 0, str(e))
            return _make_coded_error(f"Create failed: {e}", "internal_error")

    def create_subtask(
        self,
        parent_uuid: str,
        description: str,
        project: str = "",
        priority: str = "",
        tags: list[str] | None = None,
        due: str = "",
        dry_run: bool | None = None,
        **udas: str,
    ) -> dict[str, Any]:
        """Create a subtask with depends: linking to a parent task."""
        params = {
            "parent_uuid": parent_uuid,
            "description": description,
            "project": project,
            "priority": priority,
            "tags": tags,
            "dry_run": dry_run,
            **udas,
        }
        try:
            self._guard_rate(is_create=True)

            clean_parent_uuid = sanitize_uuid(parent_uuid)
            parent_task = self.task.get_task(clean_parent_uuid)
            if not parent_task:
                self._log(
                    "create_subtask",
                    params,
                    "parent not found",
                    False,
                    0,
                    f"Parent task {clean_parent_uuid} not found",
                    result_code="not_found",
                )
                return _make_coded_error(
                    f"Parent task {clean_parent_uuid} not found.",
                    "not_found",
                )

            clean_desc = sanitize_description(description)
            task_data: dict[str, Any] = {
                "description": clean_desc,
                "depends": clean_parent_uuid,
            }

            if project:
                task_data["project"] = sanitize_project(project)
            if priority:
                task_data["priority"] = sanitize_enum(priority, "priority", ["H", "M", "L"])
            if due:
                task_data["due"] = sanitize_field_value(due, "due")

            clean_tags: list[str] = []
            if tags:
                clean_tags = [sanitize_tag(t) for t in tags]
                task_data["tags"] = clean_tags

            for key, value in udas.items():
                if value:
                    if key in self.schema.enum_fields():
                        task_data[key] = sanitize_enum(value, key, self.schema.enum_fields()[key])
                    else:
                        task_data[key] = sanitize_field_value(value, key)

            validation_errors = validate_task(task_data, self.schema)
            if validation_errors:
                self._log(
                    "create_subtask",
                    params,
                    "validation failed",
                    False,
                    0,
                    "; ".join(validation_errors),
                    result_code="validation_error",
                )
                return _make_coded_error(
                    f"Schema validation failed: {'; '.join(validation_errors)}",
                    "validation_error",
                )

            cli_fields: dict[str, str] = {}
            for key, value in task_data.items():
                if key in ("description", "tags"):
                    continue
                cli_fields[key] = value
            if clean_tags:
                cli_fields["tags"] = clean_tags

            if self._effective_dry_run(dry_run):
                self._log("create_subtask", params, "dry_run", True, 0, result_code="dry_run")
                return _make_success(
                    f"DRY RUN: Would create subtask under {clean_parent_uuid}.",
                    code="dry_run",
                    dry_run=True,
                    preview={"description": clean_desc, "fields": cli_fields},
                )

            result, ms = _timed_call(self.task.add_task, clean_desc, **cli_fields)
            if result.ok:
                self._log("create_subtask", params, result.stdout, True, ms)
                return _make_success(
                    f"Subtask created with parent {clean_parent_uuid}. {result.stdout.strip()}"
                )
            self._log("create_subtask", params, result.stderr, False, ms, result.stderr)
            return _make_coded_error(f"Create subtask failed: {result.stderr}", "cli_error")
        except (RateLimitError, SanitizationError) as e:
            self._log("create_subtask", params, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("create_subtask", params, "", False, 0, str(e))
            return _make_coded_error(f"Create subtask failed: {e}", "internal_error")

    def batch_create_tasks(
        self,
        tasks: list[dict[str, Any]],
        dry_run: bool | None = None,
    ) -> dict[str, Any]:
        """Create multiple tasks with partial-result reporting."""
        params = {"task_count": len(tasks), "dry_run": dry_run}
        if not tasks:
            return _make_coded_error("No tasks provided for batch creation.", "validation_error")

        results: list[dict[str, Any]] = []
        created_count = 0
        failed_count = 0

        for idx, item in enumerate(tasks):
            if not isinstance(item, dict):
                failed_count += 1
                results.append(
                    {
                        "index": idx,
                        "result": _make_coded_error(
                            "Each batch entry must be an object.",
                            "validation_error",
                        ),
                    }
                )
                continue

            raw_tags = item.get("tags")
            if isinstance(raw_tags, str):
                tag_list: list[str] | None = [t.strip() for t in raw_tags.split(",") if t.strip()]
            elif isinstance(raw_tags, list):
                tag_list = raw_tags
            else:
                tag_list = None

            raw_extra = item.get("extra_fields")
            extra_fields: dict[str, Any] = raw_extra if isinstance(raw_extra, dict) else {}

            task_result = self.create_task(
                description=str(item.get("description", "")),
                project=str(item.get("project", "")),
                priority=str(item.get("priority", "")),
                tags=tag_list,
                due=str(item.get("due", "")),
                dry_run=dry_run,
                **extra_fields,
            )

            results.append({"index": idx, "result": task_result})
            if task_result.get("success"):
                created_count += 1
                continue

            failed_count += 1
            if task_result.get("code") == "rate_limit":
                self._log(
                    "batch_create_tasks",
                    params,
                    "rate limit",
                    False,
                    0,
                    result_code="rate_limit",
                )
                return _make_coded_error(
                    "Batch creation stopped by rate limit.",
                    "rate_limit",
                    details={
                        "created_count": created_count,
                        "failed_count": failed_count,
                        "total": len(tasks),
                        "failed_index": idx,
                        "results": results,
                        **dict(task_result.get("details") or {}),
                    },
                )

        self._log(
            "batch_create_tasks",
            params,
            f"created={created_count} failed={failed_count}",
            True,
            0,
            result_code="ok" if failed_count == 0 else "validation_error",
        )
        if failed_count == 0:
            return _make_success(
                f"Batch create succeeded for {created_count} tasks.",
                created_count=created_count,
                failed_count=0,
                results=results,
            )
        return _make_coded_error(
            f"Batch create completed with {failed_count} failures.",
            "validation_error",
            details={
                "created_count": created_count,
                "failed_count": failed_count,
                "total": len(tasks),
                "results": results,
            },
        )

    # -----------------------------------------------------------------------
    # MANAGER tools
    # -----------------------------------------------------------------------

    def bulk_modify(
        self,
        filters: str,
        fields: dict[str, str | list[str]],
        dry_run: bool | None = None,
        confirm_token: str = "",
    ) -> dict[str, Any]:
        """Modify all tasks matching a filter expression."""
        params = {
            "filters": filters,
            "fields": fields,
            "dry_run": dry_run,
            "confirm_token": bool(confirm_token),
        }
        try:
            self._guard_rate()
            clean_filters = sanitize_filter_expression(filters)
            filter_parts = clean_filters.split() if clean_filters else []
            tasks, ms = _timed_call(self.task.export_tasks, *filter_parts)
            if not tasks:
                self._log("bulk_modify", params, "no tasks", False, ms, result_code="not_found")
                return _make_coded_error(
                    f"No tasks matched filter '{clean_filters}'.",
                    "not_found",
                )

            task_count = len(tasks)
            task_uuids = [str(task.get("uuid", "")) for task in tasks if task.get("uuid")]
            if self._effective_dry_run(dry_run):
                self._log("bulk_modify", params, "dry_run", True, ms, result_code="dry_run")
                return _make_success(
                    f"DRY RUN: Would modify {task_count} tasks.",
                    code="dry_run",
                    dry_run=True,
                    preview={"task_count": task_count, "task_uuids": task_uuids, "fields": fields},
                )

            if self.config.require_confirmation:
                token_subject = f"{clean_filters}:{task_count}"
                required_token = self._confirmation_token("bulk_modify", token_subject)
                if confirm_token != required_token:
                    self._log(
                        "bulk_modify",
                        params,
                        "confirmation_required",
                        True,
                        ms,
                        result_code="confirmation_required",
                    )
                    return _make_success(
                        (
                            f"CONFIRMATION REQUIRED: Modify {task_count} tasks "
                            f"matching '{clean_filters}'. Re-call bulk_modify "
                            "with confirm_token from details."
                        ),
                        code="confirmation_required",
                        needs_confirmation=True,
                        details={
                            "confirmation_token": required_token,
                            "task_count": task_count,
                        },
                    )

            modified_count = 0
            failed: list[dict[str, Any]] = []
            for uuid in task_uuids:
                modify_result = self.modify_task(uuid=uuid, fields=fields, dry_run=False)
                if modify_result.get("success"):
                    modified_count += 1
                    continue
                failed.append({"uuid": uuid, "result": modify_result})
                if modify_result.get("code") == "rate_limit":
                    self._log(
                        "bulk_modify",
                        params,
                        "rate limit",
                        False,
                        0,
                        result_code="rate_limit",
                    )
                    return _make_coded_error(
                        "Bulk modify stopped by rate limit.",
                        "rate_limit",
                        details={
                            "modified_count": modified_count,
                            "failed_count": len(failed),
                            "task_count": task_count,
                            "failed": failed,
                            **dict(modify_result.get("details") or {}),
                        },
                    )

            if failed:
                self._log(
                    "bulk_modify",
                    params,
                    f"partial success modified={modified_count} failed={len(failed)}",
                    False,
                    0,
                    result_code="validation_error",
                )
                return _make_coded_error(
                    f"Bulk modify completed with {len(failed)} failures.",
                    "validation_error",
                    details={
                        "modified_count": modified_count,
                        "failed_count": len(failed),
                        "task_count": task_count,
                        "failed": failed,
                    },
                )

            self._log(
                "bulk_modify",
                params,
                f"modified={modified_count}",
                True,
                0,
            )
            return _make_success(
                f"Modified {modified_count} tasks.",
                modified_count=modified_count,
                task_count=task_count,
            )
        except (RateLimitError, SanitizationError) as e:
            self._log(
                "bulk_modify",
                params,
                "",
                False,
                0,
                str(e),
                result_code=_result_code_from_exception(e),
            )
            return _error_from_known_exception(e)
        except Exception as e:
            self._log(
                "bulk_modify",
                params,
                "",
                False,
                0,
                str(e),
                result_code="internal_error",
            )
            return _make_coded_error(f"Bulk modify failed: {e}", "internal_error")

    def complete_task(
        self,
        uuid: str,
        dry_run: bool | None = None,
        confirm_token: str = "",
    ) -> dict[str, Any]:
        """Mark a task as done."""
        params = {"uuid": uuid, "dry_run": dry_run, "confirm_token": bool(confirm_token)}
        effective_dry = self._effective_dry_run(dry_run)
        try:
            self._guard_rate()
            clean_uuid = sanitize_uuid(uuid)

            if effective_dry:
                task_data = self.task.get_task(clean_uuid)
                if not task_data:
                    return _make_coded_error(f"Task {clean_uuid} not found.", "not_found")
                self._log("complete_task", params, "dry_run", True, 0, result_code="dry_run")
                return _make_success(
                    f"DRY RUN: Would complete task '{task_data.get('description', '')}'.",
                    code="dry_run",
                    dry_run=True,
                    task=_redact_fields(task_data, self.config.redacted_fields),
                )

            if self.config.require_confirmation:
                task_data = self.task.get_task(clean_uuid)
                if not task_data:
                    return _make_coded_error(f"Task {clean_uuid} not found.", "not_found")
                required_token = self._confirmation_token("complete_task", clean_uuid)
                if confirm_token != required_token:
                    self._log(
                        "complete_task",
                        params,
                        "confirmation_required",
                        True,
                        0,
                        result_code="confirmation_required",
                    )
                    return _make_success(
                        "CONFIRMATION REQUIRED: Complete task "
                        f"'{task_data.get('description', '')}'. "
                        "Re-call complete_task with confirm_token from details.",
                        code="confirmation_required",
                        details={"confirmation_token": required_token},
                        needs_confirmation=True,
                        task=_redact_fields(task_data, self.config.redacted_fields),
                    )

            result, ms = _timed_call(self.task.done_task, clean_uuid)
            if result.ok:
                self._log("complete_task", params, "ok", True, ms)
                return _make_success(f"Task {clean_uuid} completed.")
            self._log("complete_task", params, result.stderr, False, ms, result.stderr)
            return _make_coded_error(f"Complete failed: {result.stderr}", "cli_error")
        except (RateLimitError, SanitizationError) as e:
            self._log("complete_task", params, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("complete_task", params, "", False, 0, str(e))
            return _make_coded_error(f"Complete failed: {e}", "internal_error")

    def delete_task(
        self,
        uuid: str,
        dry_run: bool | None = None,
        confirm_token: str = "",
    ) -> dict[str, Any]:
        """Delete a task."""
        params = {"uuid": uuid, "dry_run": dry_run, "confirm_token": bool(confirm_token)}
        effective_dry = self._effective_dry_run(dry_run)
        try:
            self._guard_rate()
            clean_uuid = sanitize_uuid(uuid)

            if effective_dry:
                task_data = self.task.get_task(clean_uuid)
                if not task_data:
                    return _make_coded_error(f"Task {clean_uuid} not found.", "not_found")
                self._log("delete_task", params, "dry_run", True, 0, result_code="dry_run")
                return _make_success(
                    f"DRY RUN: Would delete task '{task_data.get('description', '')}'.",
                    code="dry_run",
                    dry_run=True,
                    task=_redact_fields(task_data, self.config.redacted_fields),
                )

            if self.config.require_confirmation:
                task_data = self.task.get_task(clean_uuid)
                if not task_data:
                    return _make_coded_error(f"Task {clean_uuid} not found.", "not_found")
                required_token = self._confirmation_token("delete_task", clean_uuid)
                if confirm_token != required_token:
                    self._log(
                        "delete_task",
                        params,
                        "confirmation_required",
                        True,
                        0,
                        result_code="confirmation_required",
                    )
                    return _make_success(
                        "CONFIRMATION REQUIRED: Delete task "
                        f"'{task_data.get('description', '')}'. "
                        "Re-call delete_task with confirm_token from details.",
                        code="confirmation_required",
                        details={"confirmation_token": required_token},
                        needs_confirmation=True,
                        task=_redact_fields(task_data, self.config.redacted_fields),
                    )

            result, ms = _timed_call(self.task.delete_task, clean_uuid)
            if result.ok:
                self._log("delete_task", params, "ok", True, ms)
                return _make_success(f"Task {clean_uuid} deleted.")
            self._log("delete_task", params, result.stderr, False, ms, result.stderr)
            return _make_coded_error(f"Delete failed: {result.stderr}", "cli_error")
        except (RateLimitError, SanitizationError) as e:
            self._log("delete_task", params, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("delete_task", params, "", False, 0, str(e))
            return _make_coded_error(f"Delete failed: {e}", "internal_error")

    def undo(
        self,
        dry_run: bool | None = None,
        confirm_token: str = "",
    ) -> dict[str, Any]:
        """Undo the last Taskwarrior operation."""
        params = {"dry_run": dry_run, "confirm_token": bool(confirm_token)}
        try:
            self._guard_rate()
            if self._effective_dry_run(dry_run):
                self._log("undo", params, "dry_run", True, 0, result_code="dry_run")
                return _make_success(
                    "DRY RUN: Would undo the last Taskwarrior operation.",
                    code="dry_run",
                    dry_run=True,
                )

            if self.config.require_confirmation:
                required_token = self._confirmation_token("undo")
                if confirm_token != required_token:
                    self._log(
                        "undo",
                        params,
                        "confirmation_required",
                        True,
                        0,
                        result_code="confirmation_required",
                    )
                    return _make_success(
                        "CONFIRMATION REQUIRED: Undo the last operation. "
                        "Re-call undo with confirm_token from details.",
                        code="confirmation_required",
                        details={"confirmation_token": required_token},
                        needs_confirmation=True,
                    )

            result, ms = _timed_call(self.task.undo)
            if result.ok:
                self._log("undo", {}, "ok", True, ms)
                return _make_success("Undo successful.")
            self._log("undo", {}, result.stderr, False, ms, result.stderr)
            return _make_coded_error(f"Undo failed: {result.stderr}", "cli_error")
        except RateLimitError as e:
            self._log("undo", {}, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("undo", {}, "", False, 0, str(e))
            return _make_coded_error(f"Undo failed: {e}", "internal_error")

    def sync(self, dry_run: bool | None = None) -> dict[str, Any]:
        """Trigger task sync with TaskChampion server."""
        params = {"dry_run": dry_run}
        try:
            self._guard_rate()
            if self._effective_dry_run(dry_run):
                self._log("sync", params, "dry_run", True, 0, result_code="dry_run")
                return _make_success(
                    "DRY RUN: Would run task sync against the configured server.",
                    code="dry_run",
                    dry_run=True,
                )
            result, ms = _timed_call(self.task.sync)
            if result.ok:
                self._log("sync", {}, "ok", True, ms)
                return _make_success(f"Sync complete. {result.stdout.strip()}")
            self._log("sync", {}, result.stderr, False, ms, result.stderr)
            return _make_coded_error(f"Sync failed: {result.stderr}", "cli_error")
        except RateLimitError as e:
            self._log("sync", {}, "", False, 0, str(e))
            return _error_from_known_exception(e)
        except Exception as e:
            self._log("sync", {}, "", False, 0, str(e))
            return _make_coded_error(f"Sync failed: {e}", "internal_error")
