# Generated by: Claude claude-sonnet-4-20250514 via Windsurf Cascade
# Reviewed by: gabiup2
# Date: 2026-05-25

"""Tests for configuration loading."""

from __future__ import annotations

import textwrap

import pytest

from taskchampion_mcp.config import Role, ServerConfig, load_config


class TestRole:
    def test_validate_lowercase(self):
        assert Role.validate("contributor") == "CONTRIBUTOR"

    def test_validate_uppercase(self):
        assert Role.validate("MANAGER") == "MANAGER"

    def test_validate_invalid(self):
        with pytest.raises(ValueError, match="Invalid role"):
            Role.validate("ADMIN")

    def test_hierarchy(self):
        assert Role.level("CONTRIBUTOR") < Role.level("GENERATOR")
        assert Role.level("GENERATOR") < Role.level("MANAGER")

    def test_has_permission(self):
        assert Role.has_permission("MANAGER", "CONTRIBUTOR") is True
        assert Role.has_permission("MANAGER", "GENERATOR") is True
        assert Role.has_permission("MANAGER", "MANAGER") is True
        assert Role.has_permission("CONTRIBUTOR", "MANAGER") is False
        assert Role.has_permission("CONTRIBUTOR", "GENERATOR") is False
        assert Role.has_permission("CONTRIBUTOR", "CONTRIBUTOR") is True


class TestLoadConfig:
    def test_defaults_when_no_file(self, tmp_path):
        cfg = load_config(tmp_path / "nonexistent.toml")
        assert cfg.role == "CONTRIBUTOR"
        assert cfg.schema_name == "minimal"
        assert cfg.rate_limit_per_minute == 30

    def test_loads_toml_file(self, tmp_path):
        audit_path = tmp_path / "audit.log"
        config_file = tmp_path / "config.toml"
        config_file.write_text(
            textwrap.dedent(
                f"[server]\n"
                f'role = "GENERATOR"\n'
                f'schema = "gtd"\n'
                f'task_binary = "/usr/local/bin/task"\n'
                f"\n"
                f"[security]\n"
                f"rate_limit_per_minute = 50\n"
                f"require_confirmation = false\n"
                f'redacted_fields = ["hypothesis", "client"]\n'
                f"\n"
                f"[logging]\n"
                f'audit_log = "{audit_path}"\n'
            )
        )
        cfg = load_config(config_file)
        assert cfg.role == "GENERATOR"
        assert cfg.schema_name == "gtd"
        assert cfg.task_binary == "/usr/local/bin/task"
        assert cfg.rate_limit_per_minute == 50
        assert cfg.require_confirmation is False
        assert cfg.redacted_fields == ["hypothesis", "client"]
        assert cfg.audit_log_path == str(audit_path)

    def test_invalid_role_raises(self, tmp_path):
        config_file = tmp_path / "config.toml"
        config_file.write_text(
            textwrap.dedent("""\
            [server]
            role = "SUPERADMIN"
        """)
        )
        with pytest.raises(ValueError, match="Invalid role"):
            load_config(config_file)


class TestServerConfig:
    def test_default_values(self):
        cfg = ServerConfig()
        assert cfg.role == "CONTRIBUTOR"
        assert cfg.schema_name == "minimal"
        assert cfg.task_binary == "task"
        assert cfg.timew_binary == "timew"
        assert cfg.rate_limit_per_minute == 30
        assert cfg.rate_limit_per_hour == 200
        assert cfg.create_limit_per_hour == 50
        assert cfg.require_confirmation is True
        assert cfg.dry_run_default is False
        assert cfg.redacted_fields == []
