# Generated by: GPT-5.5 Thinking via ChatGPT
# Reviewed by: pending
# Date: 2026-05-25

"""Tests for runtime first-run onboarding tools."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from taskchampion_mcp.config import ServerConfig
from taskchampion_mcp.onboarding import (
    analyse_existing_tasks,
    analyse_taxonomy_file,
    generate_schema_preview,
    get_initialisation_status,
    propose_initialisation_options,
    save_initial_schema,
)


class FakeTaskCLI:
    def __init__(self, tasks: list[dict[str, Any]] | None = None, error: Exception | None = None):
        self._tasks = tasks or []
        self._error = error

    def export_tasks(self, *filters: str) -> list[dict[str, Any]]:
        if self._error:
            raise self._error
        return self._tasks


class FakeTimewCLI:
    def __init__(self, available: bool = True):
        self._available = available

    def available(self) -> bool:
        return self._available


@pytest.fixture
def sample_tasks() -> list[dict[str, Any]]:
    return [
        {
            "id": 1,
            "uuid": "11111111-1111-1111-1111-111111111111",
            "status": "pending",
            "description": "Configure TaskChampion sync over VPN",
            "project": "personal.infra.athena.services",
            "scope": "personal",
            "area": "infra",
            "phase": "impl",
            "effort": "M",
            "confidence": "H",
            "tags": ["linux", "taskwarrior"],
        },
        {
            "id": 2,
            "uuid": "22222222-2222-2222-2222-222222222222",
            "status": "pending",
            "description": "Research Timewarrior reporting taxonomy",
            "project": "personal.tooling.taskwarrior",
            "scope": "personal",
            "area": "tooling",
            "phase": "research",
            "hypothesis": "Timewarrior tags can encode work-session semantics cleanly",
            "effort": "S",
            "confidence": "M",
            "tags": ["timewarrior"],
        },
    ]


@pytest.fixture
def taxonomy_file(tmp_path: Path) -> Path:
    path = tmp_path / "TAXONOMY.md"
    path.write_text(
        """# Test Taxonomy

## UDA Reference

### 2.1 `scope` — personal | work
**Required on all tasks.** Top-level discriminator.

### 2.2 `phase` — idea | research | impl | validate | blocked
Every task should have a phase.

### 2.3 `hypothesis` — free string
Required when `phase` is `research`.

### 2.4 `effort` — XS | S | M | L | XL
T-shirt size estimate.

## Maintenance

- **When promoting a task from `idea` → `research`:** Add `hypothesis` describing what you are trying to answer.
""",
        encoding="utf-8",
    )
    return path


def test_status_needs_onboarding_when_only_minimal_schema(sample_tasks: list[dict[str, Any]]):
    config = ServerConfig(schema_name="minimal", schema_path=None, taxonomy_path=None)
    status = get_initialisation_status(config, FakeTaskCLI(sample_tasks), FakeTimewCLI(True))

    assert status["initialised"] is False
    assert status["needs_onboarding"] is True
    assert status["task_count"] == 2
    assert status["recommended_next_action"] == "infer_schema_from_existing_tasks"
    assert status["safe_to_mutate_tasks"] is False


def test_status_initialised_with_existing_schema(tmp_path: Path, sample_tasks: list[dict[str, Any]]):
    schema = tmp_path / "schema.toml"
    schema.write_text("[meta]\nname = 'x'\n", encoding="utf-8")
    config = ServerConfig(schema_path=str(schema))

    status = get_initialisation_status(config, FakeTaskCLI(sample_tasks))

    assert status["initialised"] is True
    assert status["needs_onboarding"] is False
    assert status["custom_schema_exists"] is True


def test_propose_options_recommends_taxonomy_when_available(taxonomy_file: Path):
    status = {
        "needs_onboarding": True,
        "recommended_next_action": "use_detected_taxonomy",
        "task_count": 2,
        "taxonomy_exists": False,
        "detected_taxonomy_paths": [str(taxonomy_file)],
    }

    options = propose_initialisation_options(status)
    by_id = {item["id"]: item for item in options["options"]}

    assert by_id["use_taxonomy"]["recommended"] is True
    assert by_id["hybrid_taxonomy_plus_tasks"]["recommended"] is True
    assert by_id["infer_from_tasks"]["recommended"] is False


def test_analyse_existing_tasks_detects_udas(sample_tasks: list[dict[str, Any]]):
    result = analyse_existing_tasks(FakeTaskCLI(sample_tasks))

    assert result["success"] is True
    assert result["task_count"] == 2
    assert "scope" in result["uda_fields"]
    assert "phase" in result["uda_fields"]
    assert result["fields"]["scope"]["inferred_values"] == ["personal"]


def test_analyse_existing_tasks_reports_export_error():
    result = analyse_existing_tasks(FakeTaskCLI(error=RuntimeError("boom")))

    assert result["error"] is True
    assert "boom" in result["message"]


def test_analyse_taxonomy_file_extracts_fields(taxonomy_file: Path):
    result = analyse_taxonomy_file(str(taxonomy_file))

    assert result["success"] is True
    assert "scope" in result["fields"]
    assert result["fields"]["scope"]["allowed_values"] == ["personal", "work"]
    assert result["condition_count"] >= 1


def test_generate_schema_preview_is_non_mutating(
    sample_tasks: list[dict[str, Any]], taxonomy_file: Path
):
    config = ServerConfig(taxonomy_path=str(taxonomy_file))

    result = generate_schema_preview(config, FakeTaskCLI(sample_tasks))

    assert result["success"] is True
    assert result["mutated"] is False
    assert "[meta]" in result["schema_toml"]
    assert "[fields.scope]" in result["schema_toml"]
    assert result["summary"]["conditions_from_taxonomy"] >= 1


def test_generate_schema_preview_requires_tasks_or_taxonomy():
    config = ServerConfig()

    result = generate_schema_preview(config, FakeTaskCLI([]))

    assert result["error"] is True
    assert "no exported tasks and no taxonomy" in result["message"]


def test_save_initial_schema_writes_schema_without_config_update(tmp_path: Path):
    out = tmp_path / "generated.toml"
    schema_toml = "[meta]\nname = \"auto_generated\"\n"

    result = save_initial_schema(
        schema_toml=schema_toml,
        output_path=str(out),
        update_config=False,
    )

    assert result["success"] is True
    assert out.exists()
    assert out.read_text(encoding="utf-8") == schema_toml
    assert result["config_updated"] is False


def test_save_initial_schema_refuses_overwrite_without_flag(tmp_path: Path):
    out = tmp_path / "generated.toml"
    out.write_text("old", encoding="utf-8")

    result = save_initial_schema(
        schema_toml="[meta]\nname = \"new\"\n",
        output_path=str(out),
        update_config=False,
    )

    assert result["error"] is True
    assert "already exists" in result["message"]
    assert out.read_text(encoding="utf-8") == "old"
